from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryClickhouseConfigRepository(InMemoryConfigRepository):
    def __init__(self):
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'plume_provision_node_1day',
                'type': 'stats',
                'server_id': None,
                'work_dir': '',
                'src_query': """
                select
                fecha_extraccion, serialnumber, paquete, id, connectionState, model, mac, nickname, ip, wanIp,
                backhaulType, defaultName, serialNumber, connectedDeviceCount, connectionStateChangeAt, networkMode,
                residentialGateway, startedAt, gateway, status, isp, download, upload, rtt, downloadDuration,
                uploadDuration, duration, testType, health_status, health_score, observacion, nro_cliente, plan,
                plano_pap, tecnologia, region, ubigeo, departamento, hub, device_name, tipo_equipo
                from superset.plume_provision_node_1day
                where {fecha_ini:DateTime} <= fecha_extraccion and fecha_extraccion < {fecha_fin:DateTime}
                """,
                "src_query_finder": """select fecha_extraccion as fecha from superset.plume_provision_node_1day WHERE fecha_extraccion > now() - interval '6' day group by fecha_extraccion """,
                'file_pattern': 'plume_provision_node_1day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'chunk_limit': 5000,
                'tablename': "plume_provision_node_1day",
                'queue_id': "ch_rep.plume_provision_node_1day",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 6}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': 'test',
                'fields': [
                    {'fieldname': "fecha_extraccion", 'src_fieldname': "fecha_extraccion", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "serialnumber", 'src_fieldname': "serialnumber", 'type': "varchar2"},
                    {'fieldname': "paquete", 'src_fieldname': "paquete", 'type': "varchar2"},
                    {'fieldname': "id", 'src_fieldname': "id", 'type': "varchar2"},
                    {'fieldname': "connectionState", 'src_fieldname': "connectionState", 'type': "varchar2"},
                    {'fieldname': "model", 'src_fieldname': "model", 'type': "varchar2"},
                    {'fieldname': "mac", 'src_fieldname': "mac", 'type': "varchar2"},
                    {'fieldname': "nickname", 'src_fieldname': "nickname", 'type': "varchar2"},
                    {'fieldname': "ip", 'src_fieldname': "ip", 'type': "varchar2"},
                    {'fieldname': "wanIp", 'src_fieldname': "wanIp", 'type': "varchar2"},
                    {'fieldname': "backhaulType", 'src_fieldname': "backhaulType", 'type': "varchar2"},
                    {'fieldname': "defaultName", 'src_fieldname': "defaultName", 'type': "varchar2"},
                    {'fieldname': "serialNumber2", 'src_fieldname': "serialNumber", 'type': "varchar2"},
                    {'fieldname': "connectedDeviceCount", 'src_fieldname': "connectedDeviceCount", 'type': "varchar2"},
                    {'fieldname': "connectionStateChangeAt", 'src_fieldname': "connectionStateChangeAt", 'type': "varchar2"},
                    {'fieldname': "networkMode", 'src_fieldname': "networkMode", 'type': "varchar2"},
                    {'fieldname': "residentialGateway", 'src_fieldname': "residentialGateway", 'type': "varchar2"},
                    {'fieldname': "startedAt", 'src_fieldname': "startedAt", 'type': "varchar2"},
                    {'fieldname': "gateway", 'src_fieldname': "gateway", 'type': "varchar2"},
                    {'fieldname': "status", 'src_fieldname': "status", 'type': "varchar2"},
                    {'fieldname': "isp", 'src_fieldname': "isp", 'type': "varchar2"},
                    {'fieldname': "download", 'src_fieldname': "download", 'type': "varchar2"},
                    {'fieldname': "upload", 'src_fieldname': "upload", 'type': "varchar2"},
                    {'fieldname': "rtt", 'src_fieldname': "rtt", 'type': "varchar2"},
                    {'fieldname': "downloadDuration", 'src_fieldname': "downloadDuration", 'type': "varchar2"},
                    {'fieldname': "uploadDuration", 'src_fieldname': "uploadDuration", 'type': "varchar2"},
                    {'fieldname': "duration", 'src_fieldname': "duration", 'type': "varchar2"},
                    {'fieldname': "testType", 'src_fieldname': "testType", 'type': "varchar2"},
                    {'fieldname': "health_status", 'src_fieldname': "health_status", 'type': "varchar2"},
                    {'fieldname': "health_score", 'src_fieldname': "health_score", 'type': "varchar2"},
                    {'fieldname': "observacion", 'src_fieldname': "observacion", 'type': "varchar2"},
                    {'fieldname': "nro_cliente", 'src_fieldname': "nro_cliente", 'type': "varchar2"},
                    {'fieldname': "plan", 'src_fieldname': "plan", 'type': "varchar2"},
                    {'fieldname': "plano_pap", 'src_fieldname': "plano_pap", 'type': "varchar2"},
                    {'fieldname': "tecnologia", 'src_fieldname': "tecnologia", 'type': "varchar2"},
                    {'fieldname': "region", 'src_fieldname': "region", 'type': "varchar2"},
                    {'fieldname': "ubigeo", 'src_fieldname': "ubigeo", 'type': "varchar2"},
                    {'fieldname': "departamento", 'src_fieldname': "departamento", 'type': "varchar2"},
                    {'fieldname': "hub", 'src_fieldname': "hub", 'type': "varchar2"},
                    {'fieldname': "device_name", 'src_fieldname': "device_name", 'type': "varchar2"},
                    {'fieldname': "tipo_equipo", 'src_fieldname': "tipo_equipo", 'type': "varchar2"},
                ]
            },
            "2": {
                'id': '2',
                'name': 'plume_provision_dispositivos_1day',
                'type': 'stats',
                'server_id': None,
                'work_dir': '',
                'src_query': """
                select
                fecha_extraccion, serialnumber, paquete, mac, hostName, medium, connectionState, connectionStateChangeAt, ip,
                channel, freqBand, name, icon, iconV2, iconV3, category, brand, osName, score, status, id, nickname, accessZone,
                firstConnectedAt, radio24, radio50, radio60, kind_id, kind_type_id, kind_type_category, kind_type_brand,
                kind_type_name, kind_type_model, kind_type_icon, kind_type_iconV2, kind_type_iconV3, kind_type_osName,
                kind_type_osVersion, kind_type_source, kind_type_confidence, kind_type_stationary, observacion, nro_cliente,
                plan, plano_pap, tecnologia, region, ubigeo, departamento, hub, device_name, tipo_equipo, category_ok
                from superset.plume_provision_dispositivos_1day
                where {fecha_ini:DateTime} <= fecha_extraccion and fecha_extraccion < {fecha_fin:DateTime}
                """,
                "src_query_finder": """select fecha_extraccion as fecha from superset.plume_provision_dispositivos_1day
                WHERE fecha_extraccion > now() - interval '6' day group by fecha_extraccion """,
                'file_pattern': 'plume_provision_dispositivos_1day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'chunk_limit': 5000,
                'tablename': "plume_provision_dispositivos_1day",
                'queue_id': "ch_rep.plume_provision_dispositivos_1day",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 6}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': 'test',
                'fields': [
                    {'fieldname': "fecha_extraccion", 'src_fieldname': "fecha_extraccion", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "serialnumber", 'src_fieldname': "serialnumber", 'type': "varchar2"},
                    {'fieldname': "paquete", 'src_fieldname': "paquete", 'type': "varchar2"},
                    {'fieldname': "mac", 'src_fieldname': "mac", 'type': "varchar2"},
                    {'fieldname': "hostName", 'src_fieldname': "hostName", 'type': "varchar2"},
                    {'fieldname': "medium", 'src_fieldname': "medium", 'type': "varchar2"},
                    {'fieldname': "connectionState", 'src_fieldname': "connectionState", 'type': "varchar2"},
                    {'fieldname': "connectionStateChangeAt", 'src_fieldname': "connectionStateChangeAt", 'type': "varchar2"},
                    {'fieldname': "ip", 'src_fieldname': "ip", 'type': "varchar2"},
                    {'fieldname': "channel", 'src_fieldname': "channel", 'type': "varchar2"},
                    {'fieldname': "freqBand", 'src_fieldname': "freqBand", 'type': "varchar2"},
                    {'fieldname': "name", 'src_fieldname': "name", 'type': "varchar2"},
                    {'fieldname': "icon", 'src_fieldname': "icon", 'type': "varchar2"},
                    {'fieldname': "iconV2", 'src_fieldname': "iconV2", 'type': "varchar2"},
                    {'fieldname': "iconV3", 'src_fieldname': "iconV3", 'type': "varchar2"},
                    {'fieldname': "category", 'src_fieldname': "category", 'type': "varchar2"},
                    {'fieldname': "brand", 'src_fieldname': "brand", 'type': "varchar2"},
                    {'fieldname': "osName", 'src_fieldname': "osName", 'type': "varchar2"},
                    {'fieldname': "score", 'src_fieldname': "score", 'type': "varchar2"},
                    {'fieldname': "status", 'src_fieldname': "status", 'type': "varchar2"},
                    {'fieldname': "id", 'src_fieldname': "id", 'type': "varchar2"},
                    {'fieldname': "nickname", 'src_fieldname': "nickname", 'type': "varchar2"},
                    {'fieldname': "accessZone", 'src_fieldname': "accessZone", 'type': "varchar2"},
                    {'fieldname': "firstConnectedAt", 'src_fieldname': "firstConnectedAt", 'type': "varchar2"},
                    {'fieldname': "radio24", 'src_fieldname': "radio24", 'type': "varchar2"},
                    {'fieldname': "radio50", 'src_fieldname': "radio50", 'type': "varchar2"},
                    {'fieldname': "radio60", 'src_fieldname': "radio60", 'type': "varchar2"},
                    {'fieldname': "kind_id", 'src_fieldname': "kind_id", 'type': "varchar2"},
                    {'fieldname': "kind_type_id", 'src_fieldname': "kind_type_id", 'type': "varchar2"},
                    {'fieldname': "kind_type_category", 'src_fieldname': "kind_type_category", 'type': "varchar2"},
                    {'fieldname': "kind_type_brand", 'src_fieldname': "kind_type_brand", 'type': "varchar2"},
                    {'fieldname': "kind_type_name", 'src_fieldname': "kind_type_name", 'type': "varchar2"},
                    {'fieldname': "kind_type_model", 'src_fieldname': "kind_type_model", 'type': "varchar2"},
                    {'fieldname': "kind_type_icon", 'src_fieldname': "kind_type_icon", 'type': "varchar2"},
                    {'fieldname': "kind_type_iconV2", 'src_fieldname': "kind_type_iconV2", 'type': "varchar2"},
                    {'fieldname': "kind_type_iconV3", 'src_fieldname': "kind_type_iconV3", 'type': "varchar2"},
                    {'fieldname': "kind_type_osName", 'src_fieldname': "kind_type_osName", 'type': "varchar2"},
                    {'fieldname': "kind_type_osVersion", 'src_fieldname': "kind_type_osVersion", 'type': "varchar2"},
                    {'fieldname': "kind_type_source", 'src_fieldname': "kind_type_source", 'type': "varchar2"},
                    {'fieldname': "kind_type_confidence", 'src_fieldname': "kind_type_confidence", 'type': "varchar2"},
                    {'fieldname': "kind_type_stationary", 'src_fieldname': "kind_type_stationary", 'type': "varchar2"},
                    {'fieldname': "observacion", 'src_fieldname': "observacion", 'type': "varchar2"},
                    {'fieldname': "nro_cliente", 'src_fieldname': "nro_cliente", 'type': "varchar2"},
                    {'fieldname': "plan", 'src_fieldname': "plan", 'type': "varchar2"},
                    {'fieldname': "plano_pap", 'src_fieldname': "plano_pap", 'type': "varchar2"},
                    {'fieldname': "tecnologia", 'src_fieldname': "tecnologia", 'type': "varchar2"},
                    {'fieldname': "region", 'src_fieldname': "region", 'type': "varchar2"},
                    {'fieldname': "ubigeo", 'src_fieldname': "ubigeo", 'type': "varchar2"},
                    {'fieldname': "departamento", 'src_fieldname': "departamento", 'type': "varchar2"},
                    {'fieldname': "hub", 'src_fieldname': "hub", 'type': "varchar2"},
                    {'fieldname': "device_name", 'src_fieldname': "device_name", 'type': "varchar2"},
                    {'fieldname': "tipo_equipo", 'src_fieldname': "tipo_equipo", 'type': "varchar2"},
                    {'fieldname': "category_ok", 'src_fieldname': "category_ok", 'type': "varchar2"},
                ]
            },
            "3": {
                'id': '3',
                'name': 'base_speedtest_vs_velCont_7flag',
                'type': 'stats',
                'server_id': None,
                'work_dir': '',
                'src_query': """
                select
                fecha_extraccion, startedAt, serialnumber, download, upload, rtt, tecnologia,
                plan, plano_pap, velo_ds_hfc, velo_ds_ftth, flag, if(isInfinite(porcentaje), null, porcentaje) porcentaje, porcentaje_grupo
                from superset.base_speedtest_vs_velocidadContratada_7flag
                where {fecha_ini:DateTime} <= fecha_extraccion and fecha_extraccion < {fecha_fin:DateTime}
                """,
                "src_query_finder": """select fecha_extraccion as fecha from superset.base_speedtest_vs_velocidadContratada_7flag
                WHERE fecha_extraccion > now() - interval '6' day group by fecha_extraccion """,
                'file_pattern': 'base_speedtest_vs_velCont_7flag_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'chunk_limit': 5000,
                'tablename': "plume_base_speedtest_vs_velocidadContratada_7flag",
                'queue_id': "ch_rep.base_speedtest_vs_velCont_7flag",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 6}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': 'test',
                'fields': [
                    {'fieldname': "fecha_extraccion", 'src_fieldname': "fecha_extraccion", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "startedAt", 'src_fieldname': "startedAt", 'type': "date"},
                    {'fieldname': "serialnumber", 'src_fieldname': "serialnumber", 'type': "varchar2"},
                    {'fieldname': "download", 'src_fieldname': "download", 'type': "number"},
                    {'fieldname': "upload", 'src_fieldname': "upload", 'type': "number"},
                    {'fieldname': "rtt", 'src_fieldname': "rtt", 'type': "number"},
                    {'fieldname': "tecnologia", 'src_fieldname': "tecnologia", 'type': "varchar2"},
                    {'fieldname': "plan", 'src_fieldname': "plan", 'type': "varchar2"},
                    {'fieldname': "plano_pap", 'src_fieldname': "plano_pap", 'type': "varchar2"},
                    {'fieldname': "velo_ds_hfc", 'src_fieldname': "velo_ds_hfc", 'type': "number"},
                    {'fieldname': "velo_ds_ftth", 'src_fieldname': "velo_ds_ftth", 'type': "number"},
                    {'fieldname': "flag", 'src_fieldname': "flag", 'type': "varchar2"},
                    {'fieldname': "porcentaje", 'src_fieldname': "porcentaje", 'type': "number"},
                    {'fieldname': "porcentaje_grupo", 'src_fieldname': "porcentaje_grupo", 'type': "number"},
                ]
            },
            "4": {
                'id': '4',
                'name': 'base_clientes_prov_plume_1day_rx',
                'type': 'stats',
                'server_id': None,
                'work_dir': '',
                'src_query': """
                SELECT
                customerid_codcli, tipo_cliente, tipo_servicio, serviceidentifier, serviceid, serialnumber,
                estado_servicio, fec_equipo_aprovisionado, estado_equipo, paquete, modelo_equipo,
                marca_equipo, tipo_equipo, fecha_foto_extraccion
                FROM api_plume.base_clientes_prov_plume_1day_rx
                where {fecha_ini:DateTime} <= fecha_foto_extraccion and fecha_foto_extraccion < {fecha_fin:DateTime}
                """,
                "src_query_finder": """select fecha_foto_extraccion as fecha from api_plume.base_clientes_prov_plume_1day_rx
                WHERE fecha_foto_extraccion > now() - interval '6' day group by fecha_foto_extraccion """,
                'file_pattern': 'base_clientes_prov_plume_1day_rx_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'chunk_limit': 5000,
                'tablename': "plume_base_clientes_prov_plume_1day_rx",
                'queue_id': "ch_rep.base_clientes_prov_plume_1day_rx",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 6}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': 'test',
                'fields': [
                    {'fieldname': "customerid_codcli", 'src_fieldname': "customerid_codcli", 'type': "varchar2"},
                    {'fieldname': "tipo_cliente", 'src_fieldname': "tipo_cliente", 'type': "varchar2"},
                    {'fieldname': "tipo_servicio", 'src_fieldname': "tipo_servicio", 'type': "varchar2"},
                    {'fieldname': "serviceidentifier", 'src_fieldname': "serviceidentifier", 'type': "varchar2"},
                    {'fieldname': "serviceid", 'src_fieldname': "serviceid", 'type': "varchar2"},
                    {'fieldname': "serialnumber", 'src_fieldname': "serialnumber", 'type': "varchar2"},
                    {'fieldname': "estado_servicio", 'src_fieldname': "estado_servicio", 'type': "varchar2"},
                    {'fieldname': "fec_equipo_aprovisionado", 'src_fieldname': "fec_equipo_aprovisionado", 'type': "date"},
                    {'fieldname': "estado_equipo", 'src_fieldname': "estado_equipo", 'type': "varchar2"},
                    {'fieldname': "paquete", 'src_fieldname': "paquete", 'type': "varchar2"},
                    {'fieldname': "modelo_equipo", 'src_fieldname': "modelo_equipo", 'type': "varchar2"},
                    {'fieldname': "marca_equipo", 'src_fieldname': "marca_equipo", 'type': "varchar2"},
                    {'fieldname': "tipo_equipo", 'src_fieldname': "tipo_equipo", 'type': "varchar2"},
                    {'fieldname': "fecha_foto_extraccion", 'src_fieldname': "fecha_foto_extraccion", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                ]
            },
            "5": {
                'id': '5',
                'name': 'data_pods_1day',
                'type': 'stats',
                'server_id': None,
                'work_dir': '',
                'src_query': """
                SELECT
                id, connectionState, model, mac, nickname, ip, wanIp, backhaulType, defaultName, serialNumber,
                connectedDeviceCount, connectionStateChangeAt, networkMode, residentialGateway, startedAt,
                gateway, status, isp, download, upload, rtt, downloadDuration, uploadDuration, duration,
                testType, health_status, health_score, sn_mac, dia
                FROM api_plume.data_pods_1day
                where {fecha_ini:DateTime} <= dia and dia < {fecha_fin:DateTime}
                """,
                "src_query_finder": """select date_trunc('day', dia) as fecha from api_plume.data_pods_1day
                WHERE date_trunc('day', dia) > now() - interval '6' day group by date_trunc('day', dia) """,
                'file_pattern': 'data_pods_1day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'chunk_limit': 5000,
                'tablename': "plume_data_pods_1day",
                'queue_id': "ch_rep.data_pods_1day",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 6}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': 'test',
                'fields': [
                    {'fieldname': "id", 'src_fieldname': "id", 'type': "varchar2"},
                    {'fieldname': "connectionState", 'src_fieldname': "connectionState", 'type': "varchar2"},
                    {'fieldname': "model", 'src_fieldname': "model", 'type': "varchar2"},
                    {'fieldname': "mac", 'src_fieldname': "mac", 'type': "varchar2"},
                    {'fieldname': "nickname", 'src_fieldname': "nickname", 'type': "varchar2"},
                    {'fieldname': "ip", 'src_fieldname': "ip", 'type': "varchar2"},
                    {'fieldname': "wanIp", 'src_fieldname': "wanIp", 'type': "varchar2"},
                    {'fieldname': "backhaulType", 'src_fieldname': "backhaulType", 'type': "varchar2"},
                    {'fieldname': "defaultName", 'src_fieldname': "defaultName", 'type': "varchar2"},
                    {'fieldname': "serialNumber", 'src_fieldname': "serialNumber", 'type': "varchar2"},
                    {'fieldname': "connectedDeviceCount", 'src_fieldname': "connectedDeviceCount", 'type': "varchar2"},
                    {'fieldname': "connectionStateChangeAt", 'src_fieldname': "connectionStateChangeAt", 'type': "varchar2"},
                    {'fieldname': "networkMode", 'src_fieldname': "networkMode", 'type': "varchar2"},
                    {'fieldname': "residentialGateway", 'src_fieldname': "residentialGateway", 'type': "varchar2"},
                    {'fieldname': "startedAt", 'src_fieldname': "startedAt", 'type': "varchar2"},
                    {'fieldname': "gateway", 'src_fieldname': "gateway", 'type': "varchar2"},
                    {'fieldname': "status", 'src_fieldname': "status", 'type': "varchar2"},
                    {'fieldname': "isp", 'src_fieldname': "isp", 'type': "varchar2"},
                    {'fieldname': "download", 'src_fieldname': "download", 'type': "varchar2"},
                    {'fieldname': "upload", 'src_fieldname': "upload", 'type': "varchar2"},
                    {'fieldname': "rtt", 'src_fieldname': "rtt", 'type': "varchar2"},
                    {'fieldname': "downloadDuration", 'src_fieldname': "downloadDuration", 'type': "varchar2"},
                    {'fieldname': "uploadDuration", 'src_fieldname': "uploadDuration", 'type': "varchar2"},
                    {'fieldname': "duration", 'src_fieldname': "duration", 'type': "varchar2"},
                    {'fieldname': "testType", 'src_fieldname': "testType", 'type': "varchar2"},
                    {'fieldname': "health_status", 'src_fieldname': "health_status", 'type': "varchar2"},
                    {'fieldname': "health_score", 'src_fieldname': "health_score", 'type': "varchar2"},
                    {'fieldname': "sn_mac", 'src_fieldname': "sn_mac", 'type': "varchar2"},
                    {'fieldname': "dia", 'src_fieldname': "dia", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                ]
            },
            "6": {
                'id': '6',
                'name': 'data_dispositivos_1day',
                'type': 'stats',
                'server_id': None,
                'work_dir': '',
                'src_query': """
                SELECT
                mac, hostName, medium, connectionState, connectionStateChangeAt, ip, channel, freqBand,
                name, icon, iconV2, iconV3, category, brand, osName, score, status, id, nickname,
                accessZone, firstConnectedAt, radio24, radio50, radio60, kind_id, kind_type_id,
                kind_type_category, kind_type_brand, kind_type_name, kind_type_model, kind_type_icon,
                kind_type_iconV2, kind_type_iconV3, kind_type_osName, kind_type_osVersion,
                kind_type_source, kind_type_confidence, kind_type_stationary, sn_mac, dia
                FROM api_plume.data_dispositivos_1day
                where {fecha_ini:DateTime} <= dia and dia < {fecha_fin:DateTime}
                """,
                "src_query_finder": """select date_trunc('day', dia) as fecha from api_plume.data_dispositivos_1day
                WHERE date_trunc('day', dia) > now() - interval '6' day group by date_trunc('day', dia) """,
                'file_pattern': 'data_dispositivos_1day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'chunk_limit': 5000,
                'tablename': "plume_data_dispositivos_1day",
                'queue_id': "ch_rep.data_dispositivos_1day",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 6}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': 'test',
                'fields': [
                    {'fieldname': "mac", 'src_fieldname': "mac", 'type': "varchar2"},
                    {'fieldname': "hostName", 'src_fieldname': "hostName", 'type': "varchar2"},
                    {'fieldname': "medium", 'src_fieldname': "medium", 'type': "varchar2"},
                    {'fieldname': "connectionState", 'src_fieldname': "connectionState", 'type': "varchar2"},
                    {'fieldname': "connectionStateChangeAt", 'src_fieldname': "connectionStateChangeAt", 'type': "varchar2"},
                    {'fieldname': "ip", 'src_fieldname': "ip", 'type': "varchar2"},
                    {'fieldname': "channel", 'src_fieldname': "channel", 'type': "varchar2"},
                    {'fieldname': "freqBand", 'src_fieldname': "freqBand", 'type': "varchar2"},
                    {'fieldname': "name", 'src_fieldname': "name", 'type': "varchar2"},
                    {'fieldname': "icon", 'src_fieldname': "icon", 'type': "varchar2"},
                    {'fieldname': "iconV2", 'src_fieldname': "iconV2", 'type': "varchar2"},
                    {'fieldname': "iconV3", 'src_fieldname': "iconV3", 'type': "varchar2"},
                    {'fieldname': "category", 'src_fieldname': "category", 'type': "varchar2"},
                    {'fieldname': "brand", 'src_fieldname': "brand", 'type': "varchar2"},
                    {'fieldname': "osName", 'src_fieldname': "osName", 'type': "varchar2"},
                    {'fieldname': "score", 'src_fieldname': "score", 'type': "varchar2"},
                    {'fieldname': "status", 'src_fieldname': "status", 'type': "varchar2"},
                    {'fieldname': "id", 'src_fieldname': "id", 'type': "varchar2"},
                    {'fieldname': "nickname", 'src_fieldname': "nickname", 'type': "varchar2"},
                    {'fieldname': "accessZone", 'src_fieldname': "accessZone", 'type': "varchar2"},
                    {'fieldname': "firstConnectedAt", 'src_fieldname': "firstConnectedAt", 'type': "varchar2"},
                    {'fieldname': "radio24", 'src_fieldname': "radio24", 'type': "varchar2"},
                    {'fieldname': "radio50", 'src_fieldname': "radio50", 'type': "varchar2"},
                    {'fieldname': "radio60", 'src_fieldname': "radio60", 'type': "varchar2"},
                    {'fieldname': "kind_id", 'src_fieldname': "kind_id", 'type': "varchar2"},
                    {'fieldname': "kind_type_id", 'src_fieldname': "kind_type_id", 'type': "varchar2"},
                    {'fieldname': "kind_type_category", 'src_fieldname': "kind_type_category", 'type': "varchar2"},
                    {'fieldname': "kind_type_brand", 'src_fieldname': "kind_type_brand", 'type': "varchar2"},
                    {'fieldname': "kind_type_name", 'src_fieldname': "kind_type_name", 'type': "varchar2"},
                    {'fieldname': "kind_type_model", 'src_fieldname': "kind_type_model", 'type': "varchar2"},
                    {'fieldname': "kind_type_icon", 'src_fieldname': "kind_type_icon", 'type': "varchar2"},
                    {'fieldname': "kind_type_iconV2", 'src_fieldname': "kind_type_iconV2", 'type': "varchar2"},
                    {'fieldname': "kind_type_iconV3", 'src_fieldname': "kind_type_iconV3", 'type': "varchar2"},
                    {'fieldname': "kind_type_osName", 'src_fieldname': "kind_type_osName", 'type': "varchar2"},
                    {'fieldname': "kind_type_osVersion", 'src_fieldname': "kind_type_osVersion", 'type': "varchar2"},
                    {'fieldname': "kind_type_source", 'src_fieldname': "kind_type_source", 'type': "varchar2"},
                    {'fieldname': "kind_type_confidence", 'src_fieldname': "kind_type_confidence", 'type': "varchar2"},
                    {'fieldname': "kind_type_stationary", 'src_fieldname': "kind_type_stationary", 'type': "varchar2"},
                    {'fieldname': "sn_mac", 'src_fieldname': "sn_mac", 'type': "varchar2"},
                    {'fieldname': "dia", 'src_fieldname': "dia", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                ]
            },
        }