from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryZTEConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'fm-active-timingreport-Daily_Rep',
                'type': 'stats',
                'server_id': 'zte',
                'work_dir': '/fm-active/timing/active/E755288/Daily_Rep.Desemp.Red/{date}',
                'wk_date_format': '%Y-%m-%d',
                'file_pattern': 'fm-active-timingreport-Daily_Rep.Desemp.Red-E755288-([0-9]{14}).zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "alarmas_zte",
                'queue_id': "zte.timingreport_daily_rep_alarm",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "me", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alam_code_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "relevancy", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "resource_type", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_code", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "occurrence_time", 'src_fieldname': "5", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "specific_problem", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alam_severity", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ack_state", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_id", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "ack_unack_user", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "server_time", 'src_fieldname': "11", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_unack_time", 'src_fieldname': "12", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "changed_time", 'src_fieldname': "13", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_unack_system", 'src_fieldname': "14", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ack_unack_information", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "link", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "aid", 'src_fieldname': "17", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_type", 'src_fieldname': "18", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "moc", 'src_fieldname': "19", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_user", 'src_fieldname': "20", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_system", 'src_fieldname': "21", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_time", 'src_fieldname': "22", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "position", 'src_fieldname': "23", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "slice_and_sub_slice", 'src_fieldname': "24", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_information", 'src_fieldname': "25", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "additional_information", 'src_fieldname': "26", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_uuid", 'src_fieldname': "27", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_state", 'src_fieldname': "28", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_id", 'src_fieldname': "29", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_ip", 'src_fieldname': "30", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "related_me_name", 'src_fieldname': "31", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "related_me", 'src_fieldname': "32", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "repeat_count", 'src_fieldname': "33", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "business", 'src_fieldname': "34", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_type", 'src_fieldname': "35", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "admc", 'src_fieldname': "36", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "affected_client_service_number", 'src_fieldname': "37", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "intermittence_count", 'src_fieldname': "38", 'type': "number", 'to_reload': None},
                    {'fieldname': "melevel", 'src_fieldname': "39", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "associating_a_physical_interface", 'src_fieldname': "40", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "commfailedcause", 'src_fieldname': "41", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "datatype", 'src_fieldname': "42", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "threshold", 'src_fieldname': "43", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "granularity", 'src_fieldname': "44", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "l3vpn_peer_ne", 'src_fieldname': "45", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "memo", 'src_fieldname': "46", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pmthresholdtype", 'src_fieldname': "47", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protect_group_id", 'src_fieldname': "48", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protectgroupstate", 'src_fieldname': "49", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protectiongrouptype", 'src_fieldname': "50", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "reversionmode", 'src_fieldname': "51", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switchreason", 'src_fieldname': "52", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pm_value", 'src_fieldname': "53", 'type': "number", 'to_reload': None},
                    {'fieldname': "affected_customer_number", 'src_fieldname': "54", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "l3peer_affected", 'src_fieldname': "55", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_title", 'src_fieldname': "56", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "area_information", 'src_fieldname': "57", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "maintain_status", 'src_fieldname': "58", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "port_role", 'src_fieldname': "59", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "service_consistency", 'src_fieldname': "60", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switchfrom", 'src_fieldname': "61", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switchto", 'src_fieldname': "62", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "2": {
                'id': '2',
                'name': '031_11101_System Information',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/{date}/ip_systemunit',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_11101_System Information_([0-9]{14})_.+.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_system_information_stats",
                'queue_id': "zte.system_information_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 16}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "memUtility", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "cpuUtility", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "peakCPUUtility", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "memUsed", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                ]
            },
            "3": {
                'id': '3',
                'name': '031_11304_Ping Statistic',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/{date}/ip_system',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_11304_Ping Statistic_([0-9]{14})_.+.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_ping_stats",
                'queue_id': "zte.ping_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 16}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sendPkts", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "recivePkts", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "avgResponseTime", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "maxResponseTime", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "minResponseTime", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "packetLossRate", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "isTimeOut", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                ]
            },
            "4": {
                'id': '4',
                'name': '1031_30004_Qos Queue',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/{date}/ip_qosqueue',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_30004_Qos Queue_([0-9]{14})_.+.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_qos_queue_stats",
                'queue_id': "zte.qos_queue_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 16}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ifName", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "qosqueue_name", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ReceivedBitsRate", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "TransmitBitsRate", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "ReceivedUtilization", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "TransmitUtilization", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                ]
            }
        }
