from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryZTEConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'fm-active-timingreport-Daily_Rep',
                'type': 'stats',
                'server_id': 'zte',
                'work_dir': '/fm-active/timing/active/E755288/Daily_Rep.Desemp.Red/{date}',
                'wk_date_format': '%Y-%m-%d',
                'file_pattern': 'fm-active-timingreport-Daily_Rep.Desemp.Red-E755288-([0-9]{14}).zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "alarmas_zte",
                'queue_id': "zte.timingreport_daily_rep_alarm",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    INSERT INTO ZTE_ALARM_COLA_ARCH_PROCESADOS(archivo,estado,fecha_insercion,tipo_carga) VALUES ('{filename}', 0, SYSDATE,'C');
                    COMMIT;
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "archivo", 'src_fieldname': "0", 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': None},
                    {'fieldname': "me", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alam_code_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "relevancy", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "resource_type", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_code", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "occurrence_time", 'src_fieldname': "5", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "specific_problem", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alam_severity", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ack_state", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_id", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "ack_unack_user", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "server_time", 'src_fieldname': "11", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_unack_time", 'src_fieldname': "12", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "changed_time", 'src_fieldname': "13", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_unack_system", 'src_fieldname': "14", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ack_unack_information", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "link", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "aid", 'src_fieldname': "17", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_type", 'src_fieldname': "18", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "moc", 'src_fieldname': "19", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_user", 'src_fieldname': "20", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_system", 'src_fieldname': "21", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_time", 'src_fieldname': "22", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "position", 'src_fieldname': "23", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "slice_and_sub_slice", 'src_fieldname': "24", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_information", 'src_fieldname': "25", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "additional_information", 'src_fieldname': "26", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_uuid", 'src_fieldname': "27", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_state", 'src_fieldname': "28", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_id", 'src_fieldname': "29", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_ip", 'src_fieldname': "30", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "related_me_name", 'src_fieldname': "31", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "related_me", 'src_fieldname': "32", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "repeat_count", 'src_fieldname': "33", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "business", 'src_fieldname': "34", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_type", 'src_fieldname': "35", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "admc", 'src_fieldname': "36", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "affected_client_service_number", 'src_fieldname': "37", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "intermittence_count", 'src_fieldname': "38", 'type': "number", 'to_reload': None},
                    {'fieldname': "melevel", 'src_fieldname': "39", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "associating_a_physical_interface", 'src_fieldname': "40", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "commfailedcause", 'src_fieldname': "41", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "datatype", 'src_fieldname': "42", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "threshold", 'src_fieldname': "43", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "granularity", 'src_fieldname': "44", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "l3vpn_peer_ne", 'src_fieldname': "45", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "memo", 'src_fieldname': "46", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pmthresholdtype", 'src_fieldname': "47", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protect_group_id", 'src_fieldname': "48", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protectgroupstate", 'src_fieldname': "49", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protectiongrouptype", 'src_fieldname': "50", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "reversionmode", 'src_fieldname': "51", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switchreason", 'src_fieldname': "52", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pm_value", 'src_fieldname': "53", 'type': "number", 'to_reload': None},
                    {'fieldname': "affected_customer_number", 'src_fieldname': "54", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "l3peer_affected", 'src_fieldname': "55", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_title", 'src_fieldname': "56", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "area_information", 'src_fieldname': "57", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "maintain_status", 'src_fieldname': "58", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "port_role", 'src_fieldname': "59", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "service_consistency", 'src_fieldname': "60", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switchfrom", 'src_fieldname': "61", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switchto", 'src_fieldname': "62", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "2": {
                'id': '2',
                'name': '031_11101_System Information',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/ip_systemunit',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_11101_System Information_([0-9]{14})_.+.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_system_information_stats",
                'queue_id': "zte.system_information_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "memUtility", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "cpuUtility", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "peakCPUUtility", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "memUsed", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                ]
            },
            "3": {
                'id': '3',
                'name': '031_11304_Ping Statistic',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/ip_system',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_11304_Ping Statistic_([0-9]{14})_.+.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_ping_stats",
                'queue_id': "zte.ping_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sendPkts", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "recivePkts", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "avgResponseTime", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "maxResponseTime", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "minResponseTime", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "packetLossRate", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "isTimeOut", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                ]
            },
            "4": {
                'id': '4',
                'name': '1031_30004_Qos Queue',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/ip_qosqueue',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_30004_Qos Queue_([0-9]{14})_.+.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_qos_queue_stats",
                'queue_id': "zte.qos_queue_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ifName", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "qosqueue_name", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ReceivedBitsRate", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "TransmitBitsRate", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "ReceivedUtilization", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "TransmitUtilization", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                ]
            },
            "5": {
                'id': '5',
                'name': '1031_00050_OpticalPower',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_00050_OpticalPower_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_optical_stats",
                'queue_id': "zte.optical_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "InputOpticalPower", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "OutputOpticalPower", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxValueofOutputOpticalPower", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinValueofOutputOpticalPower", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxValueofInputOpticalPower", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinValueofInputOpticalPower", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': '1031_00098_ValueOfDetectingPointTemperature(Celsius)',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_00098_ValueOfDetectingPointTemperature\(Celsius\)_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_point_temperature_celsius_stats",
                'queue_id': "zte.point_temperature_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_ZTE_FILE_SUCCESS('zte.point_temperature_stats', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ValuePointTemperature", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxValuePointTemperature", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                ]
            },
            "7": {
                'id': '7',
                'name': '1031_00239_LaserBiasCurrent',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_00239_LaserBiasCurrent_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_laser_bias_current_stats",
                'queue_id': "zte.laser_bias_current_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "LaserBiasCurrent", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxValueofLaserBiasCurrent", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinValueofLaserBiasCurrent", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "8": {
                'id': '8',
                'name': '1031_00559_RateOfBytesEnteredQueue(MBps)',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_00559_RateOfBytesEnteredQueue\(MBps\)_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_rate_bytes_entered_queue_mbps_stats",
                'queue_id': "zte.rate_bytes_entered_queue_mbps_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RateOfBytesEnteredQueue", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxRateOfBytesEnteredQueue", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinRateOfBytesEnteredQueue", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "9": {
                'id': '9',
                'name': '1031_00560_RateOfBytesLeavedQueue(MBps)',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_00560_RateOfBytesLeavedQueue\(MBps\)_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_rate_bytes_leaved_queue_mbps_stats",
                'queue_id': "zte.rate_bytes_leaved_queue_mbps_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RateOfBytesLeavedQueue", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxRateOfBytesLeavedQueue", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinRateOfBytesLeavedQueue", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "10": {
                'id': '10',
                'name': '1031_00561_RateOfBytesDrop(MBps)',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_00561_RateOfBytesDrop\(MBps\)_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_rate_bytes_drop_mbps_stats",
                'queue_id': "zte.rate_bytes_drop_mbps_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RateOfBytesDrop", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxRateOfBytesDrop", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinRateOfBytesDrop", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "11": {
                'id': '11',
                'name': '1031_01990_ReceiveTrafficRate',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_01990_ReceiveTrafficRate_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_receive_traffic_rate_stats",
                'queue_id': "zte.receive_traffic_rate_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': 'file',
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_ZTE_FILE_SUCCESS('zte.receive_traffic_rate_stats', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ReceiveTrafficRate", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxReceiveTrafficRate", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinReceiveTrafficRate", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "12": {
                'id': '12',
                'name': '1031_01991_SendTrafficRate',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_01991_SendTrafficRate_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_send_traffic_rate_stats",
                'queue_id': "zte.send_traffic_rate_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_ZTE_FILE_SUCCESS('zte.send_traffic_rate_stats', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SendTrafficRate", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "MaxSendTrafficRate", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "MinSendTrafficRate", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "13": {
                'id': '13',
                'name': '1031_03120_PhysicalInterfaceStatus',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_03120_PhysicalInterfaceStatus_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_physical_int_status_stats",
                'queue_id': "zte.physical_int_status_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PhysicalInterfaceStatus", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "14": {
                'id': '14',
                'name': '1031_03189_Receivebandwidthusagerate',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_03189_Receivebandwidthusagerate_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_receive_bandwidthusagerate_stats",
                'queue_id': "zte.receive_bandwidthusagerate_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': 'file',
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_ZTE_FILE_SUCCESS('zte.receive_bandwidthusagerate_stats', '{str_filedate}');
                END;""",
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "Receivebandwidthusagerate", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "Maxvalueofreceivebandwidthusagerate", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "Minvalueofreceivebandwidthusagerate", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "15": {
                'id': '15',
                'name': '1031_03192_Sendbandwidthusagerate',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_03192_Sendbandwidthusagerate_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 10000,
                'tablename': "zte_send_bandwidthusagerate_stats",
                'queue_id': "zte.send_bandwidthusagerate_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': 'file',
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_ZTE_FILE_SUCCESS('zte.send_bandwidthusagerate_stats', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "Sendbandwidthusagerate", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "Maxvalueofsendbandwidthusagerate", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "Minvalueofsendbandwidthusagerate", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "16": {
                'id': '16',
                'name': '1031_04203_EthernetPhysical(ETPI)',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_04203_EthernetPhysical\(ETPI\)_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_ethernet_physical_stats",
                'queue_id': "zte.ethernet_physical_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "EthernetPIReceivebytes", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPISendbytes", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceivebandwidthusagerate", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPISendbandwidthusagerate", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceiveerrorframes", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceiveerrorframesratio", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPISenderrorframes", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPISenderrorframesratio", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPISendframes", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceiveframes", 'src_fieldname': "14", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceiveoversizeframes", 'src_fieldname': "15", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceiveundersizeframes", 'src_fieldname': "16", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceivefragmenterrorframes", 'src_fieldname': "17", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceiveCRCerrorframes", 'src_fieldname': "18", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPISendCRCerrorframes", 'src_fieldname': "19", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIReceivealignmenterrorframes", 'src_fieldname': "20", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIOperationState", 'src_fieldname': "21", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetPIAdminState", 'src_fieldname': "22", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetReceivecommittedbandwidthusagerate", 'src_fieldname': "23", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthernetSendcommittedbandwidthusagerate", 'src_fieldname': "24", 'type': "number", 'to_reload': None},
                ]
            },
            "17": {
                'id': '17',
                'name': '1031_04386_LIGHTTWAMP',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_04386_LIGHTTWAMP_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_lighttwamp_stats",
                'queue_id': "zte.lighttwamp_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "LIGHTTWAMPLossratio", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "LIGHTTWAMPCountofpacketloss", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "LIGHTTWAMPReceivePackets", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "LIGHTTWAMPSendPackets", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                ]
            },
            "18": {
                'id': '18',
                'name': '1031_04639_EthSub-Interface',
                'type': 'stats',
                'server_id': 'zte02',
                'work_dir': '/northbound/pm/{date}/BN.PMP',
                'wk_date_format': '%Y%m%d',
                'file_pattern': '1031_04639_EthSub-Interface_([0-9]{14})_.+.csv.zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "zte_ethsub_interface_stats",
                'queue_id': "zte.ethsub_interface_stats",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "BeginTime", 'src_fieldname': "0", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "EndTime", 'src_fieldname': "1", 'type': "date", 'map_with': "{dt.datetime.strptime(value, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "DSTSAVING", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "MeLocation", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MeasuringObjectPosition", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "EthsubinfReceivebytes", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendbytes", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfReceiveframes", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendframes", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinterfaceReceivebandwidthusagerate", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinterfaceSendbandwidthusagerate", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfReceiveV4bytes", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendV4bytes", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfReceiveV4pkts", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendV4pkts", 'src_fieldname': "14", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfReceiveV6bytes", 'src_fieldname': "15", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendV6bytes", 'src_fieldname': "16", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfReceiveV6pkts", 'src_fieldname': "17", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendV6pkts", 'src_fieldname': "18", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfReceiveCommittedBandwidthUsageRate", 'src_fieldname': "19", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfSendCommittedBandwidthUsageRate", 'src_fieldname': "20", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfOperationState", 'src_fieldname': "21", 'type': "number", 'to_reload': None},
                    {'fieldname': "EthsubinfAdminState", 'src_fieldname': "22", 'type': "number", 'to_reload': None},
                ]
            },
            "19": {
                'id': '19',
                'name': 'fm-history-timingreport-Daily_Rep',
                'type': 'stats',
                'server_id': 'zte',
                'work_dir': '/fm-history/timing/history/E755288/Daily_Rep.Desemp.Red-Historical/{date}',
                'wk_date_format': '%Y-%m-%d',
                'file_pattern': 'fm-history-timingreport-Daily_Rep.Desemp.Red-Historical-E755288-([0-9]{14}).zip',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "alarmas_historico_zte",
                'queue_id': "zte.history_timingreport_daily_rep_alarm",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    INSERT INTO ZTE_ALARM_COLA_ARCH_PROCESADOS(archivo,estado,fecha_insercion,tipo_carga) VALUES ('{filename}', 0, SYSDATE,'C');
                    COMMIT;
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'alarms',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "archivo", 'src_fieldname': "0", 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': None},
                    {'fieldname': "me", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_code_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "relevancy", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "resource_type", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_code", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "specific_problem", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_severity", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "occurrence_time", 'src_fieldname': "7", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_state", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_id", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "ack_unack_user", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "server_time", 'src_fieldname': "11", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_unack_time", 'src_fieldname': "12", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "changed_time", 'src_fieldname': "13", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "ack_unack_system", 'src_fieldname': "14", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ack_unack_information", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_type", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "aid", 'src_fieldname': "17", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "repeat_count", 'src_fieldname': "18", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "moc", 'src_fieldname': "19", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_user", 'src_fieldname': "20", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_time", 'src_fieldname': "21", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "comment_user", 'src_fieldname': "22", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "link", 'src_fieldname': "23", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_system", 'src_fieldname': "24", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_system", 'src_fieldname': "25", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_type", 'src_fieldname': "26", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_time", 'src_fieldname': "27", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "position", 'src_fieldname': "28", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "slice_and_sub_slice", 'src_fieldname': "29", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "comment_information", 'src_fieldname': "30", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "additional_information", 'src_fieldname': "31", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_uuid", 'src_fieldname': "32", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "business", 'src_fieldname': "33", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_id", 'src_fieldname': "34", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "affected_client_service_number", 'src_fieldname': "35", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_ip", 'src_fieldname': "36", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "intermittence_count", 'src_fieldname': "37", 'type': "number", 'to_reload': None},
                    {'fieldname': "related_me", 'src_fieldname': "38", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_level", 'src_fieldname': "39", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "related_me_name", 'src_fieldname': "40", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration_time", 'src_fieldname': "41", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "admc", 'src_fieldname': "42", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clear_message_arrival_time", 'src_fieldname': "43", 'type': "date", 'map_with': "{dt.datetime.fromisoformat(value).strftime('%Y-%m-%d %H:%M:%S') if value != '' else value}", 'to_reload': None},
                    {'fieldname': "associating_a_physical_interface", 'src_fieldname': "44", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "communicate_failed_cause", 'src_fieldname': "45", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_type", 'src_fieldname': "46", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "threshold", 'src_fieldname': "47", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "granularity", 'src_fieldname': "48", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "l3vpn_peer_ne", 'src_fieldname': "49", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "memo", 'src_fieldname': "50", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pm_threshold_type", 'src_fieldname': "51", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protect_group_id", 'src_fieldname': "52", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protect_group_state", 'src_fieldname': "53", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "protection_group_type", 'src_fieldname': "54", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "reversion_mode", 'src_fieldname': "55", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switch_reason", 'src_fieldname': "56", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pm_value", 'src_fieldname': "57", 'type': "number", 'to_reload': None},
                    {'fieldname': "affected_customer_number", 'src_fieldname': "58", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "l3peer_affected", 'src_fieldname': "59", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_title", 'src_fieldname': "60", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "area_information", 'src_fieldname': "61", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "maintain_status", 'src_fieldname': "62", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "port_role", 'src_fieldname': "63", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "service_consistency", 'src_fieldname': "64", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switch_from", 'src_fieldname': "65", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "switch_to", 'src_fieldname': "66", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "20": {
                'id': '20',
                'name': 'ReportInventarioZTEME',
                'type': 'stats',
                'server_id': 'limqredv02',
                'work_dir': '/home/USRZENIC1/index2/estadisticas/reportes_zenic_zte/MeInfo',
                # 'wk_date_format': '%Y-%m-%d',
                'file_pattern': 'ReportInventarioZTEME Report_(.{19}).zip',
                'file_date_format': '%Y-%m-%d-%H-%M-%S',
                'limit_to_commit': 5000,
                'tablename': "tx_zte_inventario",
                'queue_id': "zte.reporte_me_inv",
                'status': 0,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'mxm',
                'm_group': 'inventario',
                'fields': [
                    {'fieldname': "fecha_carga", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "me_name", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_id", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nbi_id", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_id", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "gateway_me", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "product_type", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_type", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "me_classification", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rate_level", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_level", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "address_type", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ip_address", 'src_fieldname': "11", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "subnet_mask", 'src_fieldname': "12", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ipv6_address", 'src_fieldname': "13", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac_address", 'src_fieldname': "14", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "longitude", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitude", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "first_level_area", 'src_fieldname': "17", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "second_level_area", 'src_fieldname': "18", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "third_level_area", 'src_fieldname': "19", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location", 'src_fieldname': "20", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "service_loopback", 'src_fieldname': "21", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "hostname", 'src_fieldname': "22", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "subnet_name", 'src_fieldname': "23", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "subnet_path", 'src_fieldname': "24", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fibercount", 'src_fieldname': "25", 'type': "number", 'to_reload': None},
                    {'fieldname': "is_gateway_me", 'src_fieldname': "26", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "configuration_status", 'src_fieldname': "27", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "management_status", 'src_fieldname': "28", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "maintenance_state", 'src_fieldname': "29", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_state", 'src_fieldname': "30", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "hardware_version", 'src_fieldname': "31", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "software_version", 'src_fieldname': "32", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_soft_version", 'src_fieldname': "33", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "binding_ip", 'src_fieldname': "34", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "system_oid", 'src_fieldname': "35", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "system_name", 'src_fieldname': "36", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "creator", 'src_fieldname': "37", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "creation_time", 'src_fieldname': "38", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "vendor_name", 'src_fieldname': "39", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "remark", 'src_fieldname': "40", 'type': "number", 'to_reload': None},
                ]
            }
        }
