from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryPMConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'pm_stats_component',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/components?$top=2000&$skip=0&top=200&$expand=device,virtualservermfs&$select=device/Name,Name,virtualservermfs/Timestamp,virtualservermfs/im_Bytes,virtualservermfs/im_BytesIn,virtualservermfs/im_BytesOut,virtualservermfs/im_TotalRequestsRecvd,virtualservermfs/im_TotalResponsesRecvd,virtualservermfs/im_CurrentClientConnections,virtualservermfs/im_CurrentServerConnections,virtualservermfs/im_CurrentServerUP&$filter=((startswith(Name, 'VIP') eq true) and (groups/Name eq 'DASHBOARD BALANCEADORES') and (virtualservermfs/Timestamp ne 0))&$format=text/csv",
                'file_pattern': 'pm_stats_component_([0-9]{12}).csv',
                'file_date_format': '%Y%m%d%H%M',
                'limit_to_commit': 5000,
                'tablename': "pm_ctrx_stats_component",
                'queue_id': "pm.stats_component",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                # 'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 5}',
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "2", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "name", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "vservermfs_timestamp", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "vservermfs_im_bytes", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_bytesin", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_bytesout", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_totalrequestsrecvd", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_totalresponsesrecvd", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_currentclientconnections", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_currentserverconnections", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "vservermfs_im_currentserverup", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                ]
            },
            "2": {
                'id': '2',
                'name': 'pm_interfaces_stats_min_2',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/devices?$top=500&$skip=0&$format=json&$filter=((Name eq 'ceAGREGADORServiciosVES') or (Name eq 'ceAGREGADORServiciosVES3'))",
                'sub_api_query': "odata/api/interfaces?&resolution=RATE&timeout=120&$top=5000&$skip=0&top=300&$format=text/csv&$expand=device,portmfs&$select=DisplayName,ID,device/Name,device/ID,portmfs/Timestamp,portmfs/Resolution,portmfs/DcmID,portmfs/im_BitsPerSecond,portmfs/im_BitsPerSecondOut,portmfs/im_BitsPerSecondIn,portmfs/im_Bits,portmfs/im_BitsOut,portmfs/im_BitsIn,portmfs/im_Availability,portmfs/im_Utilization,portmfs/im_UtilizationOut,portmfs/im_UtilizationIn,Alias",
                'file_pattern': 'pm_interfaces_stats_min_2_([0-9]{10}).csv',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 5000,
                'skip_lines': 0,
                'tablename': "pm_interfaces_stats_min_2",
                'queue_id': "pm.stats_min2",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                # 'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "id_interface", 'src_fieldname': "0", 'type': "number", 'to_reload': None},
                    {'fieldname': "interface_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alias", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_device", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "resolution", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "dcmid", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecond", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecondout", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecondin", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "bits", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitsout", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitsin", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                    {'fieldname': "availability", 'src_fieldname': "14", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilization", 'src_fieldname': "15", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilizationout", 'src_fieldname': "16", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilizationin", 'src_fieldname': "17", 'type': "number", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "5", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                ]
            },
            "3": {
                'id': '3',
                'name': 'pm_interfaces_stats_min',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/devices?$top=5000&$skip=0&$format=json&$filter=((groups/Name eq 'FTTH') or (groups/Name eq 'CMTS')) or (groups/Name eq 'RHUB') or (groups/Name eq 'RMPLS')",
                'sub_api_query': "odata/api/interfaces?&resolution=RATE&timeout=120&$top=10000&$skip=0&top=300&$format=text/csv&$expand=device,portmfs&$select=DisplayName,ID,device/Name,device/ID,portmfs/Timestamp,portmfs/Resolution,portmfs/DcmID,portmfs/im_BitsPerSecond,portmfs/im_BitsPerSecondOut,portmfs/im_BitsPerSecondIn,portmfs/im_Bits,portmfs/im_BitsOut,portmfs/im_BitsIn,portmfs/im_Availability,portmfs/im_Utilization,portmfs/im_UtilizationOut,portmfs/im_UtilizationIn,Alias",
                'file_pattern': 'pm_interfaces_stats_min_([0-9]{10}).csv',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 5000,
                'skip_lines': 0,
                'tablename': "pm_interfaces_stats_min",
                'queue_id': "pm.stats_min",
                'status': 0,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """DECLARE
                    v_fecha_ini DATE := TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS');
                    v_fecha_fin DATE;
                BEGIN
                    v_fecha_fin := v_fecha_ini + interval '1' hour;
                    pk_pm_carga_hxh.sp_pm_giga_hxh(to_char(v_fecha_ini,'dd/mm/yyyy hh24'),to_char(v_fecha_fin,'dd/mm/yyyy hh24'));
                    pk_pm_carga_hxh.sp_pm_cm_hxh(to_char(v_fecha_ini,'dd/mm/yyyy hh24'),to_char(v_fecha_fin,'dd/mm/yyyy hh24'));
                    pk_pm_carga_hxh.sp_pm_gpon_hxh(to_char(v_fecha_ini,'dd/mm/yyyy hh24'),to_char(v_fecha_fin,'dd/mm/yyyy hh24'));
                    pk_pm_carga_hxh.SP_PM_US_HXH(to_char(v_fecha_ini,'dd/mm/yyyy hh24'),to_char(v_fecha_fin,'dd/mm/yyyy hh24'));
                    pk_pm_carga_hxh.sp_pm_cm_hxh_ofdm(to_char(v_fecha_ini,'dd/mm/yyyy hh24'),to_char(v_fecha_fin,'dd/mm/yyyy hh24'));
                END;""",
                # 'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'pm.stats_min',
                'fields': [
                    {'fieldname': "id_interface", 'src_fieldname': "0", 'type': "number", 'to_reload': None},
                    {'fieldname': "interface_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alias", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_device", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "resolution", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "dcmid", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecond", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecondout", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecondin", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "bits", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitsout", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitsin", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                    {'fieldname': "availability", 'src_fieldname': "14", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilization", 'src_fieldname': "15", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilizationout", 'src_fieldname': "16", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilizationin", 'src_fieldname': "17", 'type': "number", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "5", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                ]
            }
        }


class InMemoryPmBatchConfigRepository(InMemoryConfigRepository):
    def __init__(self):
        self.config_by_id = {
            "3": {
                'id': '3',
                'name': 'pm_interfaces_stats_min',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/devices?$top=5000&$skip=0&$format=json&$filter=((groups/Name eq 'FTTH') or (groups/Name eq 'CMTS')) or (groups/Name eq 'RHUB') or (groups/Name eq 'RMPLS')",
                'sub_api_query': "odata/api/interfaces?&resolution=RATE&timeout=120&$top=10000&$skip=0&top=300&$format=text/csv&$expand=device,portmfs&$select=DisplayName,ID,device/Name,device/ID,portmfs/Timestamp,portmfs/Resolution,portmfs/DcmID,portmfs/im_BitsPerSecond,portmfs/im_BitsPerSecondOut,portmfs/im_BitsPerSecondIn,portmfs/im_Bits,portmfs/im_BitsOut,portmfs/im_BitsIn,portmfs/im_Availability,portmfs/im_Utilization,portmfs/im_UtilizationOut,portmfs/im_UtilizationIn,Alias",
                'file_pattern': 'pm_interfaces_stats_min_([0-9]{12}).csv',
                'file_date_format': '%Y%m%d%H%M',
                # 'limit_to_commit': 5000,
                'chunk_limit': 10000,
                'skip_lines': 0,
                'tablename': "pm_interfaces_stats_min",
                'queue_id': "pm.stats_min",
                'status': 1,
                # 'reload_by': "file",
                # 'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_PM_FILE_SUCCESS('pm.stats_min', '{file_date}');
                END;""",
                # 'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'search_time_delay': '{"minutes": 5}',
                'loop_time': '{"minutes": 5}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                'm_group': 'pm.stats_min',
                'fields': [
                    {'fieldname': "id_interface", 'src_fieldname': "ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "interface_name", 'src_fieldname': "DisplayName", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alias", 'src_fieldname': "Alias", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "device/Name", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_device", 'src_fieldname': "device/ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': "portmfs/Timestamp", 'type': "number", 'to_reload': None},
                    {'fieldname': "resolution", 'src_fieldname': "portmfs/Resolution", 'type': "number", 'to_reload': None},
                    {'fieldname': "dcmid", 'src_fieldname': "portmfs/DcmID", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecond", 'src_fieldname': "portmfs/im_BitsPerSecond", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecondout", 'src_fieldname': "portmfs/im_BitsPerSecondOut", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitspersecondin", 'src_fieldname': "portmfs/im_BitsPerSecondIn", 'type': "number", 'to_reload': None},
                    {'fieldname': "bits", 'src_fieldname': "portmfs/im_Bits", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitsout", 'src_fieldname': "portmfs/im_BitsOut", 'type': "number", 'to_reload': None},
                    {'fieldname': "bitsin", 'src_fieldname': "portmfs/im_BitsIn", 'type': "number", 'to_reload': None},
                    {'fieldname': "availability", 'src_fieldname': "portmfs/im_Availability", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilization", 'src_fieldname': "portmfs/im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilizationout", 'src_fieldname': "portmfs/im_UtilizationOut", 'type': "number", 'to_reload': None},
                    {'fieldname': "utilizationin", 'src_fieldname': "portmfs/im_UtilizationIn", 'type': "number", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "result_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                ]
            },
            "4": {
                'id': '4',
                'name': 'pm_devices_cpu_stats',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/devices?&resolution=RATE&$expand=cpumfs&$select=Name,PrimaryIPAddress,cpumfs/ID,cpumfs/Timestamp,cpumfs/Resolution,cpumfs/DeviceItemID,cpumfs/DcmID,cpumfs/im_MemoryUtilization,cpumfs/im_Utilization,cpumfs/min_im_Utilization,cpumfs/max_im_Utilization,cpumfs/std_im_Utilization,cpumfs/pct_im_Utilization,cpumfs/im_StatusCode,cpumfs/im_cpuSystemUtilization,cpumfs/im_Status,cpumfs/im_CPUUtilizationAverage5Seconds,cpumfs/im_NumberOfCPUCores,cpumfs/im_TtlNumProcessesCPU,cpumfs/im_CPUUtilizationLastMin,cpumfs/im_cpuWaitUtilization,cpumfs/im_NumberOfCPUs&$filter=((groups/Name eq 'VPN SSL ASA') or (groups/Name eq 'VPN SSL') or (groups/Name eq 'VPN IVANTI') or (groups/Name eq 'VPN SSL IVANTI'))&$format=text/csv",
                'sub_api_query': None,
                'file_pattern': 'pm_devices_cpu_stats_([0-9]{12}).csv',
                'file_date_format': '%Y%m%d%H%M',
                'chunk_limit': 10000,
                'skip_lines': 0,
                'tablename': "pm_devices_cpu_stats",
                'queue_id': "pm.cpu_stats_vpn",
                'status': 0,
                'exec_after_st': None,
                'search_time_ago': '{"hours": 12}',
                'search_time_delay': '{"minutes": 5}',
                'loop_time': '{"minutes": 5}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                'm_group': 'cpu',
                'fields': [
                    {'fieldname': "name", 'src_fieldname': "Name", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "primaryipaddress", 'src_fieldname': "PrimaryIPAddress", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cpumfs_id", 'src_fieldname': "cpumfs/ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': "cpumfs/Timestamp", 'type': "number", 'to_reload': None},
                    {'fieldname': "resolution", 'src_fieldname': "cpumfs/Resolution", 'type': "number", 'to_reload': None},
                    {'fieldname': "deviceitemid", 'src_fieldname': "cpumfs/DeviceItemID", 'type': "number", 'to_reload': None},
                    {'fieldname': "dcmid", 'src_fieldname': "cpumfs/DcmID", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_memoryutilization", 'src_fieldname': "cpumfs/im_MemoryUtilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_utilization", 'src_fieldname': "cpumfs/im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "min_im_utilization", 'src_fieldname': "cpumfs/min_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "max_im_utilization", 'src_fieldname': "cpumfs/max_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "std_im_utilization", 'src_fieldname': "cpumfs/std_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "pct_im_utilization", 'src_fieldname': "cpumfs/pct_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_statuscode", 'src_fieldname': "cpumfs/im_StatusCode", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_cpusystemutilization", 'src_fieldname': "cpumfs/im_cpuSystemUtilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_status", 'src_fieldname': "cpumfs/im_Status", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_cpuutilizationavg5sec", 'src_fieldname': "cpumfs/im_CPUUtilizationAverage5Seconds", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_numberofcpucores", 'src_fieldname': "cpumfs/im_NumberOfCPUCores", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_ttlnumprocessescpu", 'src_fieldname': "cpumfs/im_TtlNumProcessesCPU", 'type': "number"},
                    {'fieldname': "im_cpuutilizationlastmin", 'src_fieldname': "cpumfs/im_CPUUtilizationLastMin", 'type': "number"},
                    {'fieldname': "im_cpuwaitutilization", 'src_fieldname': "cpumfs/im_cpuWaitUtilization", 'type': "number"},
                    {'fieldname': "im_numberofcpus", 'src_fieldname': "cpumfs/im_NumberOfCPUs", 'type': "number"},
                    {'fieldname': "result_time", 'src_fieldname': "result_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                ]
            },
            "5": {
                'id': '5',
                'name': 'pm_devices_latency_stats',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/devices?$top=10000&resolution=RATE&$expand=reachabilitymfs&$select=PrimaryIPAddress,Name,reachabilitymfs/Timestamp,reachabilitymfs/Resolution,reachabilitymfs/DeviceItemID,reachabilitymfs/DcmID,reachabilitymfs/im_Reachability,reachabilitymfs/min_im_Reachability,reachabilitymfs/max_im_Reachability,reachabilitymfs/std_im_Reachability,reachabilitymfs/im_AvgResponse,reachabilitymfs/min_im_AvgResponse,reachabilitymfs/max_im_AvgResponse,reachabilitymfs/std_im_AvgResponse&$filter=(groups/Name eq 'CMTS' or groups/Name eq 'FTTH' or groups/Name eq 'RHUB' or groups/Name eq 'RMPLS' or groups/Name eq 'VPN SSL ASA' or groups/Name eq 'VPN SSL')&$format=text/csv",
                'sub_api_query': None,
                'file_pattern': 'pm_devices_latency_stats_([0-9]{12}).csv',
                'file_date_format': '%Y%m%d%H%M',
                'chunk_limit': 10000,
                'skip_lines': 0,
                'tablename': "pm_devices_latency_stats",
                'queue_id': "pm.devices_latency",
                'status': 0,
                'exec_after_st': None,
                'search_time_ago': '{"hours": 12}',
                'search_time_delay': '{"minutes": 5}',
                'loop_time': '{"minutes": 5}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                'm_group': 'latency',
                'fields': [
                    {'fieldname': "name", 'src_fieldname': "Name", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "primaryipaddress", 'src_fieldname': "PrimaryIPAddress", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "result_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "resolution", 'src_fieldname': "reachabilitymfs/Resolution", 'type': "number", 'to_reload': None},
                    {'fieldname': "deviceitemid", 'src_fieldname': "reachabilitymfs/DeviceItemID", 'type': "number", 'to_reload': None},
                    {'fieldname': "dcmid", 'src_fieldname': "reachabilitymfs/DcmID", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_reachability", 'src_fieldname': "reachabilitymfs/im_Reachability", 'type': "number", 'to_reload': None},
                    {'fieldname': "min_im_reachability", 'src_fieldname': "reachabilitymfs/min_im_Reachability", 'type': "number", 'to_reload': None},
                    {'fieldname': "max_im_reachability", 'src_fieldname': "reachabilitymfs/max_im_Reachability", 'type': "number", 'to_reload': None},
                    {'fieldname': "std_im_reachability", 'src_fieldname': "reachabilitymfs/std_im_Reachability", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_avgresponse", 'src_fieldname': "reachabilitymfs/im_AvgResponse", 'type': "number", 'to_reload': None},
                    {'fieldname': "min_im_avgresponse", 'src_fieldname': "reachabilitymfs/min_im_AvgResponse", 'type': "number", 'to_reload': None},
                    {'fieldname': "max_im_avgresponse", 'src_fieldname': "reachabilitymfs/max_im_AvgResponse", 'type': "number", 'to_reload': None},
                    {'fieldname': "std_im_avgresponse", 'src_fieldname': "reachabilitymfs/std_im_AvgResponse", 'type': "number", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': 'pm_devices_memory_stats',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "odata/api/devices?&resolution=RATE&$expand=memorymfs&$select=Name,PrimaryIPAddress,memorymfs/ID,memorymfs/Timestamp,memorymfs/Resolution,memorymfs/DeviceItemID,memorymfs/DcmID,memorymfs/im_StatusCode,memorymfs/im_TotalEntityRAM,memorymfs/im_MemoryRealActive,memorymfs/im_Total,memorymfs/im_Free,memorymfs/std_im_Free,memorymfs/im_Utilization,memorymfs/min_im_Utilization,memorymfs/max_im_Utilization,memorymfs/std_im_Utilization,memorymfs/pct_im_Utilization,memorymfs/im_Used,memorymfs/im_HeapUtilization,memorymfs/im_Status&$filter=((groups/Name eq 'VPN SSL ASA') or (groups/Name eq 'VPN SSL') or (groups/Name eq 'VPN IVANTI') or (groups/Name eq 'VPN SSL IVANTI'))&$format=text/csv",
                'sub_api_query': None,
                'file_pattern': 'pm_devices_memory_stats_([0-9]{12}).csv',
                'file_date_format': '%Y%m%d%H%M',
                'chunk_limit': 10000,
                'skip_lines': 0,
                'tablename': "pm_devices_memory_stats",
                'queue_id': "pm.mem_stats_vpn",
                'status': 0,
                'exec_after_st': None,
                'search_time_ago': '{"hours": 12}',
                'search_time_delay': '{"minutes": 5}',
                'loop_time': '{"minutes": 5}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                'm_group': 'memory',
                'fields': [
                    {'fieldname': "name", 'src_fieldname': "Name", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "primaryipaddress", 'src_fieldname': "PrimaryIPAddress", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "memorymfs_id", 'src_fieldname': "memorymfs/ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': "memorymfs/Timestamp", 'type': "number", 'to_reload': None},
                    {'fieldname': "resolution", 'src_fieldname': "memorymfs/Resolution", 'type': "number", 'to_reload': None},
                    {'fieldname': "deviceitemid", 'src_fieldname': "memorymfs/DeviceItemID", 'type': "number", 'to_reload': None},
                    {'fieldname': "dcmid", 'src_fieldname': "memorymfs/DcmID", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_statuscode", 'src_fieldname': "memorymfs/im_StatusCode", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_totalentityram", 'src_fieldname': "memorymfs/im_TotalEntityRAM", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_memoryrealactive", 'src_fieldname': "memorymfs/im_MemoryRealActive", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_total", 'src_fieldname': "memorymfs/im_Total", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_free", 'src_fieldname': "memorymfs/im_Free", 'type': "number", 'to_reload': None},
                    {'fieldname': "std_im_free", 'src_fieldname': "memorymfs/std_im_Free", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_utilization", 'src_fieldname': "memorymfs/im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "min_im_utilization", 'src_fieldname': "memorymfs/min_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "max_im_utilization", 'src_fieldname': "memorymfs/max_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "std_im_utilization", 'src_fieldname': "memorymfs/std_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "pct_im_utilization", 'src_fieldname': "memorymfs/pct_im_Utilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_used", 'src_fieldname': "memorymfs/im_Used", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_heaputilization", 'src_fieldname': "memorymfs/im_HeapUtilization", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_status", 'src_fieldname': "memorymfs/im_Status", 'type': "number", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "result_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                ]
            }
        }
