from src.shared.carga.repository import InMemoryConfigRepository

class InMemorySpeedTestConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'dsar_report',
                'type': 'stats',
                'work_dir': 'extracts/dsar_reports/',
                'file_pattern': 'dsar_report_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_dsar_report",
                'queue_id': "speedtest.dsar_report",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 360}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'data_source', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'test_id', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'device_id', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'test_date', 'src_fieldname': '3', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'country_code', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'country', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'request_received_date', 'src_fieldname': '6', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "2": {
                'id': '2',
                'name': 'FixedNetworkPerformance',
                'type': 'stats',
                # 'server_id': 'pronatel03',
                'work_dir': 'extracts/Performance/FixedNetworkPerformance/',
                'file_pattern': 'FixedNetworkPerformance_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_fixed_network_performance",
                'queue_id': "speedtest.fixed_network_performance",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                # 'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'ts_result', 'src_fieldname': '0', 'type': 'date', 'map_with': "{dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S') if value != '' else ''}", 'to_reload': None},
                    {'fieldname': 'ts_result_received', 'src_fieldname': '1', 'type': 'date', 'map_with': "{dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S') if value != '' else ''}", 'to_reload': None},
                    {'fieldname': 'attr_location_timezone', 'src_fieldname': '2', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_result', 'src_fieldname': '3', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'guid_result', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_device', 'src_fieldname': '5', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_provider_name', 'src_fieldname': '6', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_provider_name_common', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '8', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'id_connection_type', 'src_fieldname': '9', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_latitude', 'src_fieldname': '10', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_longitude', 'src_fieldname': '11', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_altitude', 'src_fieldname': '12', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_accuracy_m', 'src_fieldname': '13', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_age_ms', 'src_fieldname': '14', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'id_location_type', 'src_fieldname': '15', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_place_name', 'src_fieldname': '16', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_country', 'src_fieldname': '17', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_country_code', 'src_fieldname': '18', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_region', 'src_fieldname': '19', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_subregion', 'src_fieldname': '20', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_subsubregion', 'src_fieldname': '21', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_postal_code', 'src_fieldname': '22', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_browser_agent', 'src_fieldname': '23', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_test_method', 'src_fieldname': '24', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_test_ip_version', 'src_fieldname': '25', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_result_test_source', 'src_fieldname': '26', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_connection_net_speed', 'src_fieldname': '27', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv4_address', 'src_fieldname': '28', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv6_address', 'src_fieldname': '29', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_asn', 'src_fieldname': '30', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_mac_manufacturer', 'src_fieldname': '31', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_wifi_frequency_mhz', 'src_fieldname': '32', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_channel_width_mhz', 'src_fieldname': '33', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_wifi_5ghz', 'src_fieldname': '34', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_24ghz_band_supported', 'src_fieldname': '35', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_5ghz_supported', 'src_fieldname': '36', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_6ghz_band_supported', 'src_fieldname': '37', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_60ghz_band_supported', 'src_fieldname': '38', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_wifi_base_station_id', 'src_fieldname': '39', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_wifi_rssi_dbm', 'src_fieldname': '40', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_rx_link_speed_mbps', 'src_fieldname': '41', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_tx_link_speed_mbps', 'src_fieldname': '42', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_max_supported_rx_link_speed_mbps', 'src_fieldname': '43', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_max_supported_tx_link_speed_mbps', 'src_fieldname': '44', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_standard', 'src_fieldname': '45', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_wifi_standard', 'src_fieldname': '46', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_mbps', 'src_fieldname': '47', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_mbps', 'src_fieldname': '48', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_min_ms', 'src_fieldname': '49', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_iqm_ms', 'src_fieldname': '50', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_max_ms', 'src_fieldname': '51', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_multiserver_latency_ms', 'src_fieldname': '52', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_min_ms', 'src_fieldname': '53', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_iqm_ms', 'src_fieldname': '54', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_max_ms', 'src_fieldname': '55', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_min_ms', 'src_fieldname': '56', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_iqm_ms', 'src_fieldname': '57', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_max_ms', 'src_fieldname': '58', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_packet_loss_sent', 'src_fieldname': '59', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_packet_loss_received', 'src_fieldname': '60', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'metric_packet_loss_percent', 'src_fieldname': '61', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_traceroute_hops', 'src_fieldname': '62', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute0_ip_address', 'src_fieldname': '63', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_traceroute0_latency_ms', 'src_fieldname': '64', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute1_ip_address', 'src_fieldname': '65', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_jitter_ms', 'src_fieldname': '66', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_multiserver_jitter_ms', 'src_fieldname': '67', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_model', 'src_fieldname': '68', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_manufacturer', 'src_fieldname': '69', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_chipset', 'src_fieldname': '70', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_chipset_manufacturer', 'src_fieldname': '71', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_radio', 'src_fieldname': '72', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_ram_mb', 'src_fieldname': '73', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_storage_mb', 'src_fieldname': '74', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_system_memory_mb', 'src_fieldname': '75', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_processor_count', 'src_fieldname': '76', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_processor_type', 'src_fieldname': '77', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_processor_frequency', 'src_fieldname': '78', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_app_version', 'src_fieldname': '79', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_os_version', 'src_fieldname': '80', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_name', 'src_fieldname': '81', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_country_code', 'src_fieldname': '82', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_sponsor_name', 'src_fieldname': '83', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_latitude', 'src_fieldname': '84', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_longitude', 'src_fieldname': '85', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_distance_km', 'src_fieldname': '86', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_server_auto_selected', 'src_fieldname': '87', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_server_on_network', 'src_fieldname': '88', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'num_server_download', 'src_fieldname': '89', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_network_vpn', 'src_fieldname': '90', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_portal_included', 'src_fieldname': '91', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_portal_categories', 'src_fieldname': '92', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_common_name', 'src_fieldname': '93', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_name_raw', 'src_fieldname': '94', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_connection_type_string', 'src_fieldname': '95', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "3": {
                'id': '3',
                'name': 'SensitiveData',
                'type': 'stats',
                'work_dir': 'extracts/Supplemental/',
                'file_pattern': 'SensitiveData_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_sensitive_data",
                'queue_id': "speedtest.sensitive_data",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'guid_result', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_remote_port', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_latitude', 'src_fieldname': '3', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_longitude', 'src_fieldname': '4', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute0_ip_address', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_traceroute1_ip_address', 'src_fieldname': '6', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv4_address', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "4": {
                'id': '4',
                'name': 'ServerLatency',
                'type': 'stats',
                'work_dir': 'extracts/Supplemental/',
                'file_pattern': 'ServerLatency_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_server_latency",
                'queue_id': "speedtest.server_latency",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'guid_result', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'id_server', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_name', 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_sponsor_name', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_latitude', 'src_fieldname': '5', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_longitude', 'src_fieldname': '6', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_country', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_country_code', 'src_fieldname': '8', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_server_latency_ms', 'src_fieldname': '9', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_server_jitter_ms', 'src_fieldname': '10', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_server_latency_pings_ms', 'src_fieldname': '11', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_server_on_net', 'src_fieldname': '12', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_result_multiserver_latency_included', 'src_fieldname': '13', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "5": {
                'id': '5',
                'name': 'android_modern_chipsets',
                'type': 'stats',
                'work_dir': 'extracts/modern_chipsets/',
                'file_pattern': 'android_modern_chipsets_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'file_date_added_from_mtime': True,
                'limit_to_commit': 10000,
                'tablename': "speedtest_android_modern_chipsets",
                'queue_id': "speedtest.android_modern_chipsets",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'brand', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'device', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'manufacturer', 'src_fieldname': '2', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'model', 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'hardware', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'chipset_name', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'start_date', 'src_fieldname': '6', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'retirement_date', 'src_fieldname': '7', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "6": {
                'id': '6',
                'name': 'iOS_modern_chipsets',
                'type': 'stats',
                'work_dir': 'extracts/modern_chipsets/',
                'file_pattern': 'iOS_modern_chipsets_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'file_date_added_from_mtime': True,
                'limit_to_commit': 10000,
                'tablename': "speedtest_ios_modern_chipsets",
                'queue_id': "speedtest.ios_modern_chipsets",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'model', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'chipset_name', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'start_date', 'src_fieldname': '2', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'retirement_date', 'src_fieldname': '3', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "7": {
                'id': '7',
                'name': 'AndroidSignalScan',
                'type': 'stats',
                'work_dir': 'extracts/Coverage/AndroidSignalScan',
                'file_pattern': 'AndroidSignalScan_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'file_date_added_from_mtime': False,
                'limit_to_commit': 5000,
                'db_product_name': "clickhouse",
                'tablename': "ookla.ookla_android_signal_scan",
                'queue_id': "speedtest.android_signal_scan",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "report_id", 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "trigger_name", 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_date", 'src_fieldname': '2', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "received_date", 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "received_date_local", 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "time_zone_name", 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_id", 'src_fieldname': '6', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_model", 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_manufacturer", 'src_fieldname': '8', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_model_raw", 'src_fieldname': '9', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_manufacturer_raw", 'src_fieldname': '10', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_brand_raw", 'src_fieldname': '11', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "os_version", 'src_fieldname': '12', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "app_version", 'src_fieldname': '13', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': '14', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_airplane_mode", 'src_fieldname': '15', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_network_roaming", 'src_fieldname': '16', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_international_roaming", 'src_fieldname': '17', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "number_registered_networks", 'src_fieldname': '18', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "number_unregistered_networks", 'src_fieldname': '19', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "sim_operator_name", 'src_fieldname': '20', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "raw_sim_operator_name", 'src_fieldname': '21', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "sim_operator_mcc_code", 'src_fieldname': '22', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "sim_operator_mnc_code", 'src_fieldname': '23', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "network_operator_name", 'src_fieldname': '24', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "network_operator_mcc_code", 'src_fieldname': '25', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "network_operator_mnc_code", 'src_fieldname': '26', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "client_latitude", 'src_fieldname': '27', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "client_longitude", 'src_fieldname': '28', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "altitude", 'src_fieldname': '29', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "location_accuracy", 'src_fieldname': '30', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "location_age", 'src_fieldname': '31', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "location_type", 'src_fieldname': '32', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "country", 'src_fieldname': '33', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "region", 'src_fieldname': '34', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "subregion", 'src_fieldname': '35', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "locality", 'src_fieldname': '36', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "place_type", 'src_fieldname': '37', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "postal_code", 'src_fieldname': '38', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "computed_cellular_generation", 'src_fieldname': '39', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "tac", 'src_fieldname': '40', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "pci", 'src_fieldname': '41', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "cell_identifier", 'src_fieldname': '42', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "lte_enodeb", 'src_fieldname': '43', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "rnc_id", 'src_fieldname': '44', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "cell_id", 'src_fieldname': '45', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "arfcn", 'src_fieldname': '46', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "uarfcn", 'src_fieldname': '47', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "earfcn", 'src_fieldname': '48', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_primary_cell", 'src_fieldname': '49', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': '50', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': '51', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': '52', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': '53', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': '54', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': '55', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_enabled", 'src_fieldname': '56', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_state", 'src_fieldname': '57', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_rssi", 'src_fieldname': '58', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_frequency", 'src_fieldname': '59', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_channel", 'src_fieldname': '60', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "app_foreground", 'src_fieldname': '61', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "azimuth", 'src_fieldname': '62', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_level", 'src_fieldname': '63', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_level_max", 'src_fieldname': '64', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_plugged", 'src_fieldname': '65', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_present", 'src_fieldname': '66', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_status", 'src_fieldname': '67', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_technology", 'src_fieldname': '68', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_temperature", 'src_fieldname': '69', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "battery_voltage", 'src_fieldname': '70', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_idle_mode", 'src_fieldname': '71', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "humidity", 'src_fieldname': '72', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "humidity_accuracy", 'src_fieldname': '73', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "light_lx", 'src_fieldname': '74', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "light_accuracy", 'src_fieldname': '75', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "pitch", 'src_fieldname': '76', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "power_interactive", 'src_fieldname': '77', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "power_save_mode", 'src_fieldname': '78', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "pressure_accuracy", 'src_fieldname': '79', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "pressure_mbar", 'src_fieldname': '80', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "temp_celsius", 'src_fieldname': '81', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "temp_accuracy", 'src_fieldname': '82', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_billing", 'src_fieldname': '83', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_internet", 'src_fieldname': '84', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_network_state", 'src_fieldname': '85', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_phone_state", 'src_fieldname': '86', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_fine_location", 'src_fieldname': '87', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_coarse_location", 'src_fieldname': '88', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_background_location", 'src_fieldname': '89', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_wifi_state", 'src_fieldname': '90', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "grant_boot_completed", 'src_fieldname': '91', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "valid_device_check", 'src_fieldname': '92', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "location_check", 'src_fieldname': '93', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "radio", 'src_fieldname': '94', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "service_state", 'src_fieldname': '95', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "sim_state", 'src_fieldname': '96', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "sim_count", 'src_fieldname': '97', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "guid", 'src_fieldname': '98', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "cell_bandwidth", 'src_fieldname': '99', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "vertical_accuracy", 'src_fieldname': '100', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_ss_rsrp", 'src_fieldname': '101', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_ss_rsrq", 'src_fieldname': '102', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_ss_sinr", 'src_fieldname': '103', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_csi_rsrp", 'src_fieldname': '104', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_csi_rsrq", 'src_fieldname': '105', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_csi_sinr", 'src_fieldname': '106', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_level", 'src_fieldname': '107', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_asu", 'src_fieldname': '108', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_arfcn", 'src_fieldname': '109', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_nci", 'src_fieldname': '110', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_pci", 'src_fieldname': '111', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_tac", 'src_fieldname': '112', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_mcc", 'src_fieldname': '113', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_mnc", 'src_fieldname': '114', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_state", 'src_fieldname': '115', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_frequency_range", 'src_fieldname': '116', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_nr_available", 'src_fieldname': '117', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_nr_telephony_sourced", 'src_fieldname': '118', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_using_carrier_aggregation", 'src_fieldname': '119', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "chipset_name", 'src_fieldname': '120', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "chipset_manufacturer", 'src_fieldname': '121', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "cell_bandwidths", 'src_fieldname': '122', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_access_network_technology_nr", 'src_fieldname': '123', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "device_tac", 'src_fieldname': '124', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "downstream_bandwidth_kbps", 'src_fieldname': '125', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_channel_width", 'src_fieldname': '126', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "has_bg_location_permission", 'src_fieldname': '127', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "has_cellular_service", 'src_fieldname': '128', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "upstream_bandwidth_kbps", 'src_fieldname': '129', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "gsm_additional_plmns", 'src_fieldname': '130', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "tdscdma_additional_plmns", 'src_fieldname': '131', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wcdma_additional_plmns", 'src_fieldname': '132', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "lte_additional_plmns", 'src_fieldname': '133', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "lte_bands", 'src_fieldname': '134', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_additional_plmns", 'src_fieldname': '135', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "nr_bands", 'src_fieldname': '136', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "gsm_rssi", 'src_fieldname': '137', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wcdma_ecno", 'src_fieldname': '138', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_rx_link_speed", 'src_fieldname': '139', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_max_supported_rx_link_speed", 'src_fieldname': '140', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_max_supported_tx_link_speed", 'src_fieldname': '141', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_passpoint_fqdn", 'src_fieldname': '142', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_passpoint_provider_name", 'src_fieldname': '143', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_carrier_name", 'src_fieldname': '144', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_standard", 'src_fieldname': '145', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_is_2_4GHz_band_supported", 'src_fieldname': '146', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_is_6GHz_band_supported", 'src_fieldname': '147', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "wifi_is_60GHz_band_supported", 'src_fieldname': '148', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "current_thermal_status", 'src_fieldname': '149', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "thermal_headroom", 'src_fieldname': '150', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "alt_sim_operator_name", 'src_fieldname': '151', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "alt_raw_sim_operator_name", 'src_fieldname': '152', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "alt_sim_operator_mcc_code", 'src_fieldname': '153', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "alt_sim_operator_mnc_code", 'src_fieldname': '154', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "data_activity", 'src_fieldname': '155', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "data_state", 'src_fieldname': '156', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "display_state", 'src_fieldname': '157', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_concurrent_voice_data_supported", 'src_fieldname': '158', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_data_capable", 'src_fieldname': '159', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_data_enabled", 'src_fieldname': '160', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_data_connection_allowed", 'src_fieldname': '161', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_data_roaming_enabled", 'src_fieldname': '162', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "has_icc_card", 'src_fieldname': '163', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_world_phone", 'src_fieldname': '164', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_multi_sim_supported", 'src_fieldname': '165', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "active_modem_count", 'src_fieldname': '166', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "supported_modem_count", 'src_fieldname': '167', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "override_network_type", 'src_fieldname': '168', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "lac", 'src_fieldname': '169', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "psc", 'src_fieldname': '170', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "location_speed_mps", 'src_fieldname': '171', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "is_device_5g_capable", 'src_fieldname': '172', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "fecha_archivo", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "8": {
                'id': '8',
                'name': 'SiteFinder',
                'type': 'stats',
                'work_dir': 'extracts/Coverage/CellAnalytics',
                'file_pattern': 'SiteFinder_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'file_date_added_from_mtime': False,
                'limit_to_commit': 10000,
                'tablename': "ookla_site_finder",
                'queue_id': "speedtest.site_finder",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 90}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'site_country', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'site_latitude', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'site_longitude', 'src_fieldname': '2', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'network_operator_name', 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'enodeb_id', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'site_admin_level_1', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'site_admin_level_2', 'src_fieldname': '6', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "fecha_archivo", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "9": {
                'id': '9',
                'name': 'dsar_video_report',
                'type': 'stats',
                'work_dir': 'extracts/dsar_reports/',
                'file_pattern': 'dsar_video_report_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_dsar_video_report",
                'queue_id': "speedtest.dsar_video_report",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 360}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'data_source', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'test_id', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'device_id', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'test_date', 'src_fieldname': '3', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'request_received_date', 'src_fieldname': '4', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "10": {
                'id': '10',
                'name': 'MobileNetworkPerformance',
                'type': 'stats',
                'work_dir': 'extracts/Performance/MobileNetworkPerformance',
                'file_pattern': 'MobileNetworkPerformance_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'db_product_name': "clickhouse",
                'tablename': "ook_speed_test.mobile_speed_test",
                'queue_id': "speedtest.mobile_network_performance",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '11',
                'fields': [
                    {'fieldname': 'id_result', 'src_fieldname': '0', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'guid_result', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '2', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'ts_result', 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'ts_result_received', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_location_timezone', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_device', 'src_fieldname': '6', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_device_android_fingerprint', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},  
                    {'fieldname': 'attr_device_model', 'src_fieldname': '8', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_manufacturer', 'src_fieldname': '9', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_model_raw', 'src_fieldname': '10', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_manufacturer_raw', 'src_fieldname': '11', 'type': 'varchar2', 'to_reload': None},    
                    {'fieldname': 'attr_device_brand_raw', 'src_fieldname': '12', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_chipset', 'src_fieldname': '13', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_chipset_manufacturer', 'src_fieldname': '14', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_hardware_name', 'src_fieldname': '15', 'type': 'varchar2', 'to_reload': None},       
                    {'fieldname': 'attr_device_os_version', 'src_fieldname': '16', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_build', 'src_fieldname': '17', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_device_rooted', 'src_fieldname': '18', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_radio', 'src_fieldname': '19', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_ram_mb', 'src_fieldname': '20', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_device_storage_mb', 'src_fieldname': '21', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'is_device_world_phone', 'src_fieldname': '22', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_multi_sim_support', 'src_fieldname': '23', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_device_active_modems', 'src_fieldname': '24', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_device_supported_modems', 'src_fieldname': '25', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'is_device_concurrent_voice_data_supported', 'src_fieldname': '26', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_device_data_connection_allowed', 'src_fieldname': '27', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_device_data_capable', 'src_fieldname': '28', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_device_data_roaming_enabled', 'src_fieldname': '29', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_device_icc_card_present', 'src_fieldname': '30', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_service_state', 'src_fieldname': '31', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_device_thermal_status', 'src_fieldname': '32', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_device_thermal_headroom', 'src_fieldname': '33', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_app_permission_phone_state', 'src_fieldname': '34', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_app_permission_fine_location', 'src_fieldname': '35', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_app_permission_coarse_location', 'src_fieldname': '36', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_app_permission_background_location', 'src_fieldname': '37', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_app_permission_wifi_state', 'src_fieldname': '38', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_common_name', 'src_fieldname': '39', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_name_raw', 'src_fieldname': '40', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_mcc', 'src_fieldname': '41', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_mnc', 'src_fieldname': '42', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_altsim_operator_name', 'src_fieldname': '43', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_altsim_operator_mcc', 'src_fieldname': '44', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_altsim_operator_mnc', 'src_fieldname': '45', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_network_operator_mcc', 'src_fieldname': '46', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_network_operator_mnc', 'src_fieldname': '47', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_network_operator_common_name', 'src_fieldname': '48', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_isp_common_name', 'src_fieldname': '49', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_isp_name_raw', 'src_fieldname': '50', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_type_allocation_code', 'src_fieldname': '51', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_sim_state', 'src_fieldname': '52', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_test_method', 'src_fieldname': '53', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_test_ip_version', 'src_fieldname': '54', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'id_connection_type_start', 'src_fieldname': '55', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'id_connection_type_end', 'src_fieldname': '56', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_connections_failed', 'src_fieldname': '57', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'is_connection_carrier_aggregation', 'src_fieldname': '58', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_connection_nr_state', 'src_fieldname': '59', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_connection_apn', 'src_fieldname': '60', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_connection_net_speed', 'src_fieldname': '61', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'is_connection_access_technology_nr', 'src_fieldname': '62', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_connection_network_override_type', 'src_fieldname': '63', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_connection_downstream_bandwidth_kbps', 'src_fieldname': '64', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_connection_upstream_bandwidth_kbps', 'src_fieldname': '65', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_connection_nat64_prefix', 'src_fieldname': '66', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_location_latitude', 'src_fieldname': '67', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_location_longitude', 'src_fieldname': '68', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_location_start_latitude', 'src_fieldname': '69', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_location_start_longitude', 'src_fieldname': '70', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_location_start_type', 'src_fieldname': '71', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'id_location_end_type', 'src_fieldname': '72', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_location_accuracy_m', 'src_fieldname': '73', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_location_age_ms', 'src_fieldname': '74', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_location_altitude_m', 'src_fieldname': '75', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_location_vertical_accuracy_m', 'src_fieldname': '76', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_location_speed_mps', 'src_fieldname': '77', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_place_formatted_address', 'src_fieldname': '78', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_name', 'src_fieldname': '79', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_locality_type', 'src_fieldname': '80', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_country', 'src_fieldname': '81', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_country_code', 'src_fieldname': '82', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_region', 'src_fieldname': '83', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_subregion', 'src_fieldname': '84', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_subsubregion', 'src_fieldname': '85', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_postal_code', 'src_fieldname': '86', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_packet_loss_sent', 'src_fieldname': '87', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_packet_loss_received', 'src_fieldname': '88', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'metric_packet_loss_percent', 'src_fieldname': '89', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_download_stopped', 'src_fieldname': '90', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_latency_min_ms', 'src_fieldname': '91', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_iqm_ms', 'src_fieldname': '92', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_max_ms', 'src_fieldname': '93', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_multiserver_latency_ms', 'src_fieldname': '94', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_min_ms', 'src_fieldname': '95', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_iqm_ms', 'src_fieldname': '96', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_max_ms', 'src_fieldname': '97', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_min_ms', 'src_fieldname': '98', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_iqm_ms', 'src_fieldname': '99', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_max_ms', 'src_fieldname': '100', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_traceroute_hops', 'src_fieldname': '101', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_traceroute0_ip_address', 'src_fieldname': '102', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_traceroute0_latency_ms', 'src_fieldname': '103', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute1_ip_address', 'src_fieldname': '104', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_traceroute1_latency_ms', 'src_fieldname': '105', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_jitter_ms', 'src_fieldname': '106', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_multiserver_jitter_ms', 'src_fieldname': '107', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_kbps', 'src_fieldname': '108', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_test_download_kb', 'src_fieldname': '109', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_test_download_threads', 'src_fieldname': '110', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_test_download_duration_ms', 'src_fieldname': '111', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_upload_kbps', 'src_fieldname': '112', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_test_upload_kb', 'src_fieldname': '113', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_test_upload_threads', 'src_fieldname': '114', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_test_upload_duration_ms', 'src_fieldname': '115', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv4_address', 'src_fieldname': '116', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv6_address', 'src_fieldname': '117', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_asn', 'src_fieldname': '118', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_app_version', 'src_fieldname': '119', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_app_store', 'src_fieldname': '120', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_name', 'src_fieldname': '121', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_sponsor_name', 'src_fieldname': '122', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_latitude', 'src_fieldname': '123', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_longitude', 'src_fieldname': '124', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_server_distance_km', 'src_fieldname': '125', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_server_country', 'src_fieldname': '126', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_country_code', 'src_fieldname': '127', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_server_auto_selected', 'src_fieldname': '128', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_server_on_network', 'src_fieldname': '129', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_asn', 'src_fieldname': '130', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'num_server_download', 'src_fieldname': '131', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_rsrp_dbm', 'src_fieldname': '132', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_csi_rsrp_dbm', 'src_fieldname': '133', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_ss_rsrp_dbm', 'src_fieldname': '134', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_rsrq_db', 'src_fieldname': '135', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_csi_rsrq_db', 'src_fieldname': '136', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_ss_rsrq_db', 'src_fieldname': '137', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_rssnr_db', 'src_fieldname': '138', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_csi_snr_db', 'src_fieldname': '139', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_ss_snr_db', 'src_fieldname': '140', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_wcdma_ecno_db', 'src_fieldname': '141', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_rssi_dbm', 'src_fieldname': '142', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_gsm_rssi_dbm', 'src_fieldname': '143', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_timing_advance_ts', 'src_fieldname': '144', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'val_signal_cqi', 'src_fieldname': '145', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_nr_frequency_range', 'src_fieldname': '146', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_cell_bandwidth_khz', 'src_fieldname': '147', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_bandwidths_khz', 'src_fieldname': '148', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_cell_primary', 'src_fieldname': '149', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'id_cell_lte_enodeb', 'src_fieldname': '150', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_pci', 'src_fieldname': '151', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_nr_pci', 'src_fieldname': '152', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_tac', 'src_fieldname': '153', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_lac', 'src_fieldname': '154', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_psc', 'src_fieldname': '155', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_frequency_channel', 'src_fieldname': '156', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_frequency_channel_type', 'src_fieldname': '157', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_cell_nr_arfcn', 'src_fieldname': '158', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_cell_lte_bands', 'src_fieldname': '159', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_cell_nr_bands', 'src_fieldname': '160', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_network_roaming', 'src_fieldname': '161', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_network_international_roaming', 'src_fieldname': '162', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_network_vpn', 'src_fieldname': '163', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_device_5g_capable', 'src_fieldname': '164', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_portal_included', 'src_fieldname': '165', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_portal_categories', 'src_fieldname': '166', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_connection_type_start_string', 'src_fieldname': '167', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_connection_type_end_string', 'src_fieldname': '168', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_esim_embedded', 'src_fieldname': '169', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_cell_nr', 'src_fieldname': '170', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'id_cell_start', 'src_fieldname': '171', 'type': 'int', 'to_reload': None},
                    {'fieldname': 'attr_network_operator_mcc_nr', 'src_fieldname': '172', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_operator_mnc_nr', 'src_fieldname': '173', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_location_building', 'src_fieldname': '174', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_indoor_confidence_level', 'src_fieldname': '175', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "11": {
                'id': '11',
                'name': 'DataUsage',
                'type': 'stats',
                'work_dir': 'extracts/Coverage/CellAnalytics',
                'file_pattern': 'DataUsage_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                # 'db_product_name': "clickhouse",
                'tablename': "speedtest_data_usage",
                'queue_id': "speedtest.data_usage",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 147}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '11',
                'fields': [
                    {'fieldname': 'start_date', 'src_fieldname': '0', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'mcc', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'mnc', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'latitude', 'src_fieldname': '3', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'longitude', 'src_fieldname': '4', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'mobile_data_usage_mb', 'src_fieldname': '5', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'wifi_data_usage_mb', 'src_fieldname': '6', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'user_count', 'src_fieldname': '7', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'provider_name', 'src_fieldname': '8', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                ]
            }
        }