from src.shared.carga.repository import InMemoryConfigRepository

class InMemorySpeedTestConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'dsar_report',
                'type': 'stats',
                'work_dir': 'extracts/dsar_reports/',
                'file_pattern': 'dsar_report_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_dsar_report",
                'queue_id': "speedtest.dsar_report",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 360}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'data_source', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'test_id', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'device_id', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'test_date', 'src_fieldname': '3', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'country_code', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'country', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'request_received_date', 'src_fieldname': '6', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "2": {
                'id': '2',
                'name': 'FixedNetworkPerformance',
                'type': 'stats',
                # 'server_id': 'pronatel03',
                'work_dir': 'extracts/Performance/FixedNetworkPerformance/',
                'file_pattern': 'FixedNetworkPerformance_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_fixed_network_performance",
                'queue_id': "speedtest.fixed_network_performance",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                # 'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'ts_result', 'src_fieldname': '0', 'type': 'date', 'map_with': "{dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S') if value != '' else ''}", 'to_reload': None},
                    {'fieldname': 'ts_result_received', 'src_fieldname': '1', 'type': 'date', 'map_with': "{dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S') if value != '' else ''}", 'to_reload': None},
                    {'fieldname': 'attr_location_timezone', 'src_fieldname': '2', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_result', 'src_fieldname': '3', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'guid_result', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_device', 'src_fieldname': '5', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_provider_name', 'src_fieldname': '6', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_provider_name_common', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '8', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'id_connection_type', 'src_fieldname': '9', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_latitude', 'src_fieldname': '10', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_longitude', 'src_fieldname': '11', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_altitude', 'src_fieldname': '12', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_accuracy_m', 'src_fieldname': '13', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_age_ms', 'src_fieldname': '14', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'id_location_type', 'src_fieldname': '15', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_place_name', 'src_fieldname': '16', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_country', 'src_fieldname': '17', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_country_code', 'src_fieldname': '18', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_region', 'src_fieldname': '19', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_subregion', 'src_fieldname': '20', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_subsubregion', 'src_fieldname': '21', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_place_postal_code', 'src_fieldname': '22', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_browser_agent', 'src_fieldname': '23', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_test_method', 'src_fieldname': '24', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_test_ip_version', 'src_fieldname': '25', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_result_test_source', 'src_fieldname': '26', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_connection_net_speed', 'src_fieldname': '27', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv4_address', 'src_fieldname': '28', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv6_address', 'src_fieldname': '29', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_asn', 'src_fieldname': '30', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_mac_manufacturer', 'src_fieldname': '31', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_wifi_frequency_mhz', 'src_fieldname': '32', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_channel_width_mhz', 'src_fieldname': '33', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_wifi_5ghz', 'src_fieldname': '34', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_24ghz_band_supported', 'src_fieldname': '35', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_5ghz_supported', 'src_fieldname': '36', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_6ghz_band_supported', 'src_fieldname': '37', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_wifi_60ghz_band_supported', 'src_fieldname': '38', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_wifi_base_station_id', 'src_fieldname': '39', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_wifi_rssi_dbm', 'src_fieldname': '40', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_rx_link_speed_mbps', 'src_fieldname': '41', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_tx_link_speed_mbps', 'src_fieldname': '42', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_max_supported_rx_link_speed_mbps', 'src_fieldname': '43', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_max_supported_tx_link_speed_mbps', 'src_fieldname': '44', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_wifi_standard', 'src_fieldname': '45', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_wifi_standard', 'src_fieldname': '46', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_mbps', 'src_fieldname': '47', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_mbps', 'src_fieldname': '48', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_min_ms', 'src_fieldname': '49', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_iqm_ms', 'src_fieldname': '50', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_latency_max_ms', 'src_fieldname': '51', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_multiserver_latency_ms', 'src_fieldname': '52', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_min_ms', 'src_fieldname': '53', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_iqm_ms', 'src_fieldname': '54', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_download_latency_max_ms', 'src_fieldname': '55', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_min_ms', 'src_fieldname': '56', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_iqm_ms', 'src_fieldname': '57', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_upload_latency_max_ms', 'src_fieldname': '58', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_packet_loss_sent', 'src_fieldname': '59', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_packet_loss_received', 'src_fieldname': '60', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'metric_packet_loss_percent', 'src_fieldname': '61', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'num_traceroute_hops', 'src_fieldname': '62', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute0_ip_address', 'src_fieldname': '63', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_traceroute0_latency_ms', 'src_fieldname': '64', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute1_ip_address', 'src_fieldname': '65', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_jitter_ms', 'src_fieldname': '66', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_multiserver_jitter_ms', 'src_fieldname': '67', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_model', 'src_fieldname': '68', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_manufacturer', 'src_fieldname': '69', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_chipset', 'src_fieldname': '70', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_chipset_manufacturer', 'src_fieldname': '71', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_radio', 'src_fieldname': '72', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_ram_mb', 'src_fieldname': '73', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_storage_mb', 'src_fieldname': '74', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_system_memory_mb', 'src_fieldname': '75', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_processor_count', 'src_fieldname': '76', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_processor_type', 'src_fieldname': '77', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_processor_frequency', 'src_fieldname': '78', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_app_version', 'src_fieldname': '79', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_device_os_version', 'src_fieldname': '80', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_name', 'src_fieldname': '81', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_country_code', 'src_fieldname': '82', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_sponsor_name', 'src_fieldname': '83', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_latitude', 'src_fieldname': '84', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_longitude', 'src_fieldname': '85', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_distance_km', 'src_fieldname': '86', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_server_auto_selected', 'src_fieldname': '87', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_server_on_network', 'src_fieldname': '88', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'num_server_download', 'src_fieldname': '89', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'is_network_vpn', 'src_fieldname': '90', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_portal_included', 'src_fieldname': '91', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_portal_categories', 'src_fieldname': '92', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_common_name', 'src_fieldname': '93', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_sim_operator_name_raw', 'src_fieldname': '94', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_connection_type_string', 'src_fieldname': '95', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "3": {
                'id': '3',
                'name': 'SensitiveData',
                'type': 'stats',
                'work_dir': 'extracts/Supplemental/',
                'file_pattern': 'SensitiveData_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_sensitive_data",
                'queue_id': "speedtest.sensitive_data",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'guid_result', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_device_remote_port', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_latitude', 'src_fieldname': '3', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_location_longitude', 'src_fieldname': '4', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_traceroute0_ip_address', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_traceroute1_ip_address', 'src_fieldname': '6', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_network_ipv4_address', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "4": {
                'id': '4',
                'name': 'ServerLatency',
                'type': 'stats',
                'work_dir': 'extracts/Supplemental/',
                'file_pattern': 'ServerLatency_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "speedtest_server_latency",
                'queue_id': "speedtest.server_latency",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'guid_result', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'id_platform', 'src_fieldname': '1', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'id_server', 'src_fieldname': '2', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_name', 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_sponsor_name', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_latitude', 'src_fieldname': '5', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_longitude', 'src_fieldname': '6', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'attr_server_country', 'src_fieldname': '7', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'attr_server_country_code', 'src_fieldname': '8', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'val_server_latency_ms', 'src_fieldname': '9', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_server_jitter_ms', 'src_fieldname': '10', 'type': 'number', 'to_reload': None},
                    {'fieldname': 'val_server_latency_pings_ms', 'src_fieldname': '11', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_server_on_net', 'src_fieldname': '12', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'is_result_multiserver_latency_included', 'src_fieldname': '13', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "5": {
                'id': '5',
                'name': 'android_modern_chipsets',
                'type': 'stats',
                'work_dir': 'extracts/modern_chipsets/',
                'file_pattern': 'android_modern_chipsets_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'file_date_added_from_mtime': True,
                'limit_to_commit': 10000,
                'tablename': "speedtest_android_modern_chipsets",
                'queue_id': "speedtest.android_modern_chipsets",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'brand', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'device', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'manufacturer', 'src_fieldname': '2', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'model', 'src_fieldname': '3', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'hardware', 'src_fieldname': '4', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'chipset_name', 'src_fieldname': '5', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'start_date', 'src_fieldname': '6', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'retirement_date', 'src_fieldname': '7', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "6": {
                'id': '6',
                'name': 'iOS_modern_chipsets',
                'type': 'stats',
                'work_dir': 'extracts/modern_chipsets/',
                'file_pattern': 'iOS_modern_chipsets_(.{10}).zip',
                'file_date_format': '%Y-%m-%d',
                'file_date_added_from_mtime': True,
                'limit_to_commit': 10000,
                'tablename': "speedtest_ios_modern_chipsets",
                'queue_id': "speedtest.ios_modern_chipsets",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "unzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': 'model', 'src_fieldname': '0', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'chipset_name', 'src_fieldname': '1', 'type': 'varchar2', 'to_reload': None},
                    {'fieldname': 'start_date', 'src_fieldname': '2', 'type': 'date', 'to_reload': None},
                    {'fieldname': 'retirement_date', 'src_fieldname': '3', 'type': 'date', 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            }
        }