from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryPronatelConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'reclamos_siac_planning',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reclamos_siac_planning_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_siac_planning",
                'queue_id': "pronatel.reclamos_siac_planning",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro_escalado", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "respuesta", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "2": {
                'id': '2',
                'name': 'reclamos_ifi_planning',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reclamos_ifi_planning_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_ifi_planning",
                'queue_id': "pronatel.reclamos_ifi_planning",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '2',
                'fields': [
                    {'fieldname': "fecha_registro_escalado", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "respuesta", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "3": {
                'id': '3',
                'name': 'reclamos_retencion_planning',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reclamos_retencion_planning_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_retencion_planning",
                'queue_id': "pronatel.reclamos_retencion_planning",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '2',
                'fields': [
                    {'fieldname': "fecha_registro_escalado", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "respuesta", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "4": {
                'id': '4',
                'name': 'tsf_score_area_sn_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_area_sn_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "fija_tsf_score_area_sn_30d",
                'queue_id': "pronatel.tsf_score_area_sn_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "upselling", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_clientes", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "oym_sf", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "ingcalidad_sf", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                ]
            },
            "5": {
                'id': '5',
                'name': 'tsf_score_flag_sn_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_flag_sn_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "fija_tsf_score_flag_sn_30d",
                'queue_id': "pronatel.tsf_score_flag_sn_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "rt_auto_upselling", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_equipo_upselling", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_vel_ingcalidad_sf", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_reinicio_ingcalidad_sf", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_alerta_plano_ingcalidad_sf", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_wifi_upselling", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_in_house_im_clientes", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_pext_ingcalidad_sf", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_sots", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': 'reporte_reinicios_ftth_hfc_detallado',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_reinicios_ftth_hfc_detallado_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_reporte_reinicios_ftth_hfc_det",
                'queue_id': "pronatel.reporte_reinicios_ftth_hfc_det",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nro_cliente", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "displayname", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cantidad_reinicios", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "7": {
                'id': '7',
                'name': 'reporte_equipo_no_recomendado_hfc_detallado',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_equipo_no_recomendado_hfc_detallado_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_rep_equipo_no_recomendado_hfc_det",
                'queue_id': "soportecli.rep_equipo_no_recomendado_hfc_det",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "customer_id", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "n_portadoras_cm", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "velocidad_contratada", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "porcentaje_ofrecida_cm", 'src_fieldname': "6", 'type': "number", 'to_reload': None}
                ]
            },
            "8": {
                'id': '8',
                'name': 'reporte_relacion_device_plano',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_relacion_device_plano_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_reporte_relacion_device_plano",
                'queue_id': "soportecli.reporte_relacion_device_plano",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "device", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None}
                ]
            },
            "9": {
                'id': '9',
                'name': 'reporte_alerta_plano_detallado',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_alerta_plano_detallado_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_reporte_alerta_plano_det",
                'queue_id': "soportecli.reporte_alerta_plano_det",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "mac_serial", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "customerid", 'src_fieldname': "0", 'type': "number", 'map_with': "{row[1] if len(row)>1 else ''}", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "0", 'type': "varchar2", 'map_with': "{row[2] if len(row)>2 else ''}", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "0", 'type': "varchar2", 'map_with': "{row[3] if len(row)>3 else ''}", 'to_reload': None},
                    {'fieldname': "hora_inicio_evento", 'src_fieldname': "0", 'type': "date", 'map_with': "{row[4] if len(row)>4 else ''}", 'to_reload': None},
                    {'fieldname': "hora_fin_evento", 'src_fieldname': "0", 'type': "date", 'map_with': "{(row[5] if len(row[5])>=10 else '') if len(row)>5 else ''}", 'to_reload': None},
                    {'fieldname': "duracion_evento_min", 'src_fieldname': "0", 'type': "number", 'map_with': "{row[6] if len(row) > 6 else ''}", 'to_reload': None},
                    {'fieldname': "recurencia", 'src_fieldname': "0", 'type': "number", 'map_with': "{row[7] if len(row) > 7 else ''}", 'to_reload': None},
                ]
            },
            "10": {
                'id': '10',
                'name': 'reporte_ifi',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_ifi_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_movil_ifi",
                'queue_id': "reclamos_movil_ifi",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_export", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                ]
            },
            "11": {
                'id': '11',
                'name': 'reporte_masivos',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_masivos_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_movil_masivos",
                'queue_id': "reclamos_movil_masivos",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_export", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                ]
            },
            "12": {
                'id': '12',
                'name': 'reporte_retenciones',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_retenciones_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_movil_retenciones",
                'queue_id': "reclamos_movil_retenciones",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_export", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                ]
            },
            "13": {
                'id': '13',
                'name': 'reporte_reclamos_fija',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_reclamos_fija_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'skip_lines': 0,
                'limit_to_commit': 5000,
                'tablename': "reclamos_fija_masivos",
                'queue_id': "reclamos_fija_masivos",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "problema", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "equipo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "14": {
                'id': '14',
                'name': 'estad_viavy',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'estad_viavy_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "fija_calidad_viavy",
                'queue_id': "fija_calidad_viavy",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "timestamp", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cmts_olt", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "qoescore", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "qoepassstatus", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ingresspassstatus", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                ]
            }
        }