from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryPronatelConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'reclamos_siac_planning',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reclamos_siac_planning_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_siac_planning",
                'queue_id': "soportecli.reclamos_siac_planning",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reclamos_planning.load', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro_escalado", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "respuesta", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "2": {
                'id': '2',
                'name': 'reclamos_ifi_planning',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reclamos_ifi_planning_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_ifi_planning",
                'queue_id': "soportecli.reclamos_ifi_planning",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reclamos_planning.load', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro_escalado", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "respuesta", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "3": {
                'id': '3',
                'name': 'reclamos_retencion_planning',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reclamos_retencion_planning_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_retencion_planning",
                'queue_id': "soportecli.reclamos_retencion_planning",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reclamos_planning.load', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro_escalado", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "respuesta", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "4": {
                'id': '4',
                'name': 'tsf_score_area_sn_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_area_sn_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "fija_tsf_score_area_sn_30d",
                'queue_id': "soportecli.tsf_score_area_sn_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "upselling", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_clientes", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "oym_sf", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "ingcalidad_sf", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                ]
            },
            "5": {
                'id': '5',
                'name': 'tsf_score_flag_sn_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_flag_sn_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "fija_tsf_score_flag_sn_30d",
                'queue_id': "soportecli.tsf_score_flag_sn_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "rt_auto_upselling", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_equipo_upselling", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_vel_ingcalidad_sf", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_reinicio_ingcalidad_sf", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_alerta_plano_ingcalidad_sf", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_wifi_upselling", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_in_house_im_clientes", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_pext_ingcalidad_sf", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_sots", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': 'reporte_reinicios_ftth_hfc_detallado',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_reinicios_ftth_hfc_detallado_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_reporte_reinicios_ftth_hfc_det",
                'queue_id': "soportecli.reporte_reinicios_ftth_hfc_det",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reporte_reinicios_ftth_hfc_det.sendfile', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nro_cliente", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "displayname", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cantidad_reinicios", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ]
            },
            "7": {
                'id': '7',
                'name': 'reporte_equipo_no_recomendado_hfc_detallado',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_equipo_no_recomendado_hfc_detallado_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_rep_equipo_no_recomendado_hfc_det",
                'queue_id': "soportecli.rep_equipo_no_recomendado_hfc_det",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.rep_equipo_no_recomen_hfc_det.sendfile', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "customer_id", 'src_fieldname': "1", 'type': "number", 'map_with': "{'' if 'N' in value else value}", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "n_portadoras_cm", 'src_fieldname': "4", 'type': "number", 'map_with': "{'' if 'N' in value else value}", 'to_reload': None},
                    {'fieldname': "velocidad_contratada", 'src_fieldname': "5", 'type': "number", 'map_with': "{'' if 'N' in value else value}", 'to_reload': None},
                    {'fieldname': "porcentaje_ofrecida_cm", 'src_fieldname': "6", 'type': "number", 'map_with': "{'' if 'N' in value else value}", 'to_reload': None}
                ]
            },
            "8": {
                'id': '8',
                'name': 'reporte_relacion_device_plano',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_relacion_device_plano_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_reporte_relacion_device_plano",
                'queue_id': "soportecli.reporte_relacion_device_plano",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """DECLARE
                    V_FECHA_ARCHIVO DATE := TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS');
                    CURSOR CUR_VALIDATION IS
                    SELECT
                    to_char(a.result_time, 'yyyy-mm-dd') a_result_time,
                    a.counter a_counter,
                    to_char(b.result_time, 'yyyy-mm-dd') b_result_time,
                    b.counter b_counter,
                    (A.COUNTER/B.COUNTER)*100 PORCENTAJE_DIFF FROM
                    (
                        SELECT result_time, COUNT(*) counter FROM fija_reporte_relacion_device_plano
                        WHERE result_time = V_FECHA_ARCHIVO
                        GROUP BY result_time
                    ) A
                    INNER JOIN (
                        SELECT result_time, COUNT(*) counter FROM fija_reporte_relacion_device_plano
                        WHERE result_time < V_FECHA_ARCHIVO
                        GROUP BY result_time
                        ORDER BY result_time desc
                        FETCH FIRST '1' ROWS ONLY
                    ) B ON 1=1
                    WHERE A.COUNTER/B.COUNTER < 0.80;
                BEGIN
                    FOR V_ROW IN  CUR_VALIDATION LOOP
                        sp_send_mail_notification('Notificacion Procesos - Registros reporte_relacion_device_plano por debajo del 80%',
                        'La cantidad de registros para el dia '||v_row.a_result_time
                        ||' es de '|| v_row.a_counter ||' y estan por debajo del 80% del dia '||v_row.b_result_time||' con '
                        ||v_row.b_counter||' registros',
                        'ALARMA_CARGAS');
                        DELETE FROM fija_reporte_relacion_device_plano
                        WHERE result_time = V_FECHA_ARCHIVO;
                        COMMIT; 
                    END LOOP;
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "device", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None}
                ]
            },
            "9": {
                'id': '9',
                'name': 'reporte_alerta_plano_detallado',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_alerta_plano_detallado_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "fija_reporte_alerta_plano_det",
                'queue_id': "soportecli.reporte_alerta_plano_det",
                'status': 0,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "mac_serial", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "customerid", 'src_fieldname': "0", 'type': "number", 'map_with': "{row[1] if len(row)>1 else ''}", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "0", 'type': "varchar2", 'map_with': "{row[2] if len(row)>2 else ''}", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "0", 'type': "varchar2", 'map_with': "{row[3] if len(row)>3 else ''}", 'to_reload': None},
                    {'fieldname': "hora_inicio_evento", 'src_fieldname': "0", 'type': "date", 'map_with': "{row[4] if len(row)>4 else ''}", 'to_reload': None},
                    {'fieldname': "hora_fin_evento", 'src_fieldname': "0", 'type': "date", 'map_with': "{(row[5] if len(row[5])>=10 else '') if len(row)>5 else ''}", 'to_reload': None},
                    {'fieldname': "duracion_evento_min", 'src_fieldname': "0", 'type': "number", 'map_with': "{row[6] if len(row) > 6 else ''}", 'to_reload': None},
                    {'fieldname': "recurencia", 'src_fieldname': "0", 'type': "number", 'map_with': "{row[7] if len(row) > 7 else ''}", 'to_reload': None},
                ]
            },
            "10": {
                'id': '10',
                'name': 'reporte_ifi',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_ifi_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_movil_ifi",
                'queue_id': "soportecli.reclamos_movil_ifi",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_export", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                ]
            },
            "11": {
                'id': '11',
                'name': 'reporte_masivos',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_masivos_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_movil_masivos",
                'queue_id': "soportecli.reclamos_movil_masivos",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_export", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                ]
            },
            "12": {
                'id': '12',
                'name': 'reporte_retenciones',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_retenciones_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "reclamos_movil_retenciones",
                'queue_id': "soportecli.reclamos_movil_retenciones",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "tipo", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sector", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_site", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "inconveniente", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_export", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                ]
            },
            "13": {
                'id': '13',
                'name': 'reporte_reclamos_fija',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_reclamos_fija_(.{19}).csv',
                'file_date_format': '%Y-%m-%d_%H-%M-%S',
                'file_encoding': 'utf-8',
                'skip_lines': 0,
                'limit_to_commit': 5000,
                'tablename': "reclamos_fija_masivos",
                'queue_id': "soportecli.reclamos_fija_masivos",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"minutes": 15}',
                'msg_send_granularity': True,
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'real-time',
                'fields': [
                    {'fieldname': "fecha_registro", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "problema", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "equipo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "criticidad", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "diagnostico", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "14": {
                'id': '14',
                'name': 'estad_viavy',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'estad_viavy_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "fija_calidad_viavy",
                'queue_id': "soportecli.fija_calidad_viavy",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "timestamp", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cmts_olt", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "qoescore", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "qoepassstatus", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ingresspassstatus", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "15": {
                'id': '15',
                'name': 'planos_caidos',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'planos_caidos_(.{10}).csv',
                'file_date_format': '%Y_%m_%d',
                'skip_lines': 0,
                'file_delimiter': '|',
                'file_encoding': 'utf-8',
                'limit_to_commit': 10000,
                'tablename': "fija_planos_caidos",
                'queue_id': "soportecli.fija_planos_caidos",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "HUB", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ANILLO", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "HILOS", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CMTS", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PLANO", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SUMINISTRO", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "FECHA_CREACION", 'src_fieldname': "6", 'type': "date", 'to_reload': None},
                    {'fieldname': "INICIO", 'src_fieldname': "7", 'type': "date", 'to_reload': None},
                    {'fieldname': "FIN", 'src_fieldname': "8", 'type': "date", 'to_reload': None},
                    {'fieldname': "CLIENTES_ANTES_CAIDA", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "CLIENTES_AFECTADOS", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "CLIENTES_CORPORATIVO_AFECTADOS", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "CLIENTES_VIP", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "AFECTACION", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                    {'fieldname': "CORPORATIVO_AFECTACION", 'src_fieldname': "14", 'type': "number", 'to_reload': None},
                    {'fieldname': "TIEMPO_AFECTACION", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "INCIDENCIA", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "16": {
                'id': '16',
                'name': 'HFC_MAX',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'HFC_MAX_(.{8}).csv',
                'file_date_format': '%Y%m%d',
                'skip_lines': 1,
                'file_delimiter': ',',
                'file_encoding': 'utf-8',
                'limit_to_commit': 10000,
                'tablename': "fija_hfc_max",
                'queue_id': "soportecli.fija_hfc_max",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'max_retries': 3,
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "plano", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha", 'src_fieldname': "1", 'type': "date", 'to_reload': 1},
                    {'fieldname': "clientes", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                ]
            },
            "17": {
                'id': '17',
                'name': 'FTTH_MAX',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'FTTH_MAX_(.{8}).csv',
                'file_date_format': '%Y%m%d',
                'skip_lines': 1,
                'file_delimiter': ',',
                'file_encoding': 'utf-8',
                'limit_to_commit': 10000,
                'tablename': "fija_ftth_max",
                'queue_id': "soportecli.fija_ftth_max",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "plano", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha", 'src_fieldname': "1", 'type': "date", 'to_reload': 1},
                    {'fieldname': "clientes", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                ]
            },
            "18": {
                'id': '18',
                'name': 'flag_ftth',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'flag_ftth_([0-9]{8}).csv.gz',
                'file_date_format': '%Y%m%d',
                'file_encoding': 'utf-8',
                'limit_to_commit': 10000,
                'tablename': "fija_flag_ftth",
                'queue_id': "soportecli.fija_flag_ftth",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.fija_flag_ftth.send_file', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "ungzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "serialnumber", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "puerto", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "equipos_apropiados", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "reinicios", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "alerta_plano", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "pext", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "in_house", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "consumo", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "alto_uso_servicio", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "autosaturado", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "vel_maxima", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "cobertura_wifi", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                ]
            },
            "19": {
                'id': '19',
                'name': 'flag_hfc',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'flag_hfc_([0-9]{8}).csv.gz',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "fija_flag_hfc",
                'queue_id': "soportecli.fija_flag_hfc",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.fija_flag_hfc.send_file', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "ungzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alto_servicio", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "autosaturados", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "equipos_apropiados", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "velocidad_maxima", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "reinicios", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "alerta_plano", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "in_house", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "pext", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "consumo_minimo", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "cobertura_wifi", 'src_fieldname': "11", 'type': "number", 'map_with': "{'' if 'N' in value else value}", 'to_reload': None},

                ]
            },
            "20": {
                'id': '20',
                'name': 'tsf_score_area_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_area_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "fija_tsf_score_area_30d",
                'queue_id': "soportecli.fija_tsf_score_area_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "upselling", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "im_clientes", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "oym_sf", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "ingcalidad_sf", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                ]
            },
            "21": {
                'id': '21',
                'name': 'tsf_score_flag_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_flag_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "fija_tsf_score_flag_30d",
                'queue_id': "soportecli.fija_tsf_score_flag_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "rt_auto_upselling", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_equipo_upselling", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_vel_ingcalidad_sf", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_reinicio_ingcalidad_sf", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_alerta_plano_ingcalidad_sf", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_wifi_upselling", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_in_house_im_clientes", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_pext_ingcalidad_sf", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "rt_sots", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                ]
            },
            "22": {
                'id': '22',
                'name': 'tsf_score_mac_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_mac_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 10000,
                'tablename': "fija_tsf_score_mac_30d",
                'queue_id': "soportecli.fija_tsf_score_mac_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.fija_score_hfc.send_file', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "puntaje", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "score", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "auto", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "equipo", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "vel", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "reinicio", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "alerta_plano", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "in_house", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "pext", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "cant_sot", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                ]
            },
            "23": {
                'id': '23',
                'name': 'reporte_velocidad_maxima',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_velocidad_maxima_([0-9]{8}).csv.gz',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "fija_reporte_velocidad_maxima",
                'queue_id': "soportecli.reporte_velocidad_max",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reporte_velocidad_max.send_file', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': "ungzip",
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "mac_address", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "customer_id", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "pc_velocidad_alcanzada", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                ]
            },
            "24": {
                'id': '24',
                'name': 'reporte_ocurrencias',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_ocurrencias_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "fija_reporte_ocurrencias",
                'queue_id': "soportecli.reporte_ocurrencias",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reporte_ocurrencias.send_file', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "mac", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "customer_id", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alerta_plano", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "hora_inicio_evento", 'src_fieldname': "5", 'type': "date", 'to_reload': None},
                    {'fieldname': "hora_fin_evento", 'src_fieldname': "6", 'type': "date", 'to_reload': None},
                    {'fieldname': "duracion_del_evento", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                ]
            },
            "25": {
                'id': '25',
                'name': 'tsf_score_sn_30d',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'tsf_score_sn_30d_(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'file_encoding': 'utf-8',
                'limit_to_commit': 10000,
                'tablename': "FIJA_TSF_SCORE_SN_30D",
                'queue_id': "soportecli.tsf_score_sn_30d",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """DECLARE
                    V_FECHA_ARCHIVO VARCHAR2(20) := '{str_filedate}';
                BEGIN
                    UPDATE FIJA_TSF_SCORE_SN_30D SET device = replace(device, '\\N', '') where fecha_archivo = TO_DATE(V_FECHA_ARCHIVO, 'YYYY-MM-DD HH24:MI:SS');
                    COMMIT;
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.fija_score_ftth.send_file', V_FECHA_ARCHIVO);
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_archivo", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "puntaje", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "score", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "auto", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "equipo", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "vel", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "reinicio", 'src_fieldname': "8", 'type': "number", 'to_reload': None},
                    {'fieldname': "alerta_plano", 'src_fieldname': "9", 'type': "number", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': "10", 'type': "number", 'to_reload': None},
                    {'fieldname': "in_house", 'src_fieldname': "11", 'type': "number", 'to_reload': None},
                    {'fieldname': "pext", 'src_fieldname': "12", 'type': "number", 'to_reload': None},
                    {'fieldname': "cant_sot", 'src_fieldname': "13", 'type': "number", 'to_reload': None},
                ]
            },
            "26": {
                'id': '26',
                'name': 'reporte_casos_interferencia',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_casos_interferencia_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "reclamos_casos_interferencia",
                'queue_id': "soportecli.rep_casos_interferencia",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'to_reload': 1},
                    {'fieldname': "numcaso", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "numero", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "celda", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "lac", 'src_fieldname': "6", 'type': "number", 'to_reload': None},
                    {'fieldname': "site", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "27": {
                'id': '27',
                'name': 'reporte_wifi_hfc',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_wifi_hfc_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "FIJA_REPORTE_WIFI_HFC",
                'queue_id': "soportecli.reporte_wifi_hfc",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.reporte_wifi_hfc.sendfile', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "nro_cliente", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dispo_menor_60", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_disp", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "porcentaje", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "rango_porcentaje", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rango_cant_disp", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "28": {
                'id': '28',
                'name': 'reporte_wifi_ftth',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_encoding': 'latin-1',
                'file_pattern': 'reporte_wifi_ftth_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'skip_lines': 0,
                'limit_to_commit': 10000,
                'tablename': "fija_reporte_wifi_ftth",
                'queue_id': "soportecli.reporte_wifi_ftth",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "nr_cuenta", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nodo", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "n_dispositivo_mc", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_disp", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "porcentaje", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                    {'fieldname': "rango_porc", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rango_cant_disp", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "29": {
                'id': '29',
                'name': 'fija_consumo_hfc',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'fija_consumo_hfc_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "FIJA_CM_CONSUMO_HFC_DI",
                'queue_id': "soportecli.fija_consumo_hfc",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "macaddress", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "consumo_byte", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "30": {
                'id': '30',
                'name': 'fija_consumo_ftth',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'fija_consumo_ftth_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "FIJA_CM_CONSUMO_FTTH_DI",
                'queue_id': "soportecli.fija_consumo_ftth",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "serialnumber", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "consumo_byte", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "31": {
                'id': '31',
                'name': '20-GPON_Data_Report',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': '20-GPON_Data_Report(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'file_delimiter': '|',
                'limit_to_commit': 10000,
                'tablename': "FIJA_DI_GPON",
                'queue_id': "soportecli.gpon_data_report",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_archivo", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "nro_cuenta", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "estado_cuenta", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nro_serie_ont", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "estado_ont", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "modelo_ont", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "servicio_internet_gpon", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "estado_servicio_internet_gpon", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_creacion_serv_gpon", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_externo_psa_ont", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "servidor_ems", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_olt", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_de_marco_olt", 'src_fieldname': "11", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_de_ranura_olt", 'src_fieldname': "12", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_de_puerto_olt", 'src_fieldname': "13", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "32": {
                'id': '32',
                'name': 'cableModemActivos',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'cableModemActivos(.{10}).csv',
                'file_date_format': '%Y-%m-%d',
                'skip_lines': 3,
                'limit_to_commit': 10000,
                'tablename': "FIJA_CM_CABLEMODEM_ACTIVOS_DI",
                'queue_id': "soportecli.cable_modem_activos",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha_archivo", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "nro_cliente", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nombre_cliente", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "origen_inst_cm", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac_cm", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "estado_cm", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ip_cm", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mac_mta", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "estado_mta", 'src_fieldname': "7", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ident_servicio_hsd", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "id_producto", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "servicio", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "estado_de_servicio_hsd", 'src_fieldname': "11", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cantidad_pc", 'src_fieldname': "12", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ip_de_cpe", 'src_fieldname': "13", 'type': "clob", 'to_reload': None},
                    {'fieldname': "fecha_alta", 'src_fieldname': "14", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_activacion", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "hub_sga", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "nodo_sga", 'src_fieldname': "17", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ubicacion_red", 'src_fieldname': "18", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "up_down_incognito", 'src_fieldname': "19", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "version_docsis", 'src_fieldname': "20", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "grupo_scopes_cpe", 'src_fieldname': "21", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "mensajes", 'src_fieldname': "22", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fabricante", 'src_fieldname': "23", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "modelo", 'src_fieldname': "24", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "version_del_fw", 'src_fieldname': "25", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "oui", 'src_fieldname': "26", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "version_hw", 'src_fieldname': "27", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "version_de_rom", 'src_fieldname': "28", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sn", 'src_fieldname': "29", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "upstream_interface_alias", 'src_fieldname': "30", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "fecha_de_polleo", 'src_fieldname': "31", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "33": {
                'id': '33',
                'name': 'reporte_wifi_mala_cobertura',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_wifi_mala_cobertura_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "FIJA_WIFI_MALA_COBERTURA",
                'queue_id': "soportecli.rep_wifi_mala_cobertura",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "mac", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cantidad", 'src_fieldname': "1", 'type': "number", 'to_reload': None},
                ]
            },
            "34": {
                'id': '34',
                'name': 'reporte_pext_cliente',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'reporte_pext_cliente_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "fija_pext_cliente",
                'queue_id': "soportecli.rep_pext_cliente",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "codigo", 'src_fieldname': "0", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "plano", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "35": {
                'id': '35',
                'name': 'casos_celdas_at',
                'type': 'stats',
                'server_id': 'pronatel03',
                'work_dir': '/index2/estadisticas/soporte_clientes',
                'file_pattern': 'casos_celdas_at_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 1000,
                'tablename': "reclamos_moviles_celdas_at",
                'queue_id': "soportecli.casos_celdas_at",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': 'file',
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_SOPORTECLI_FILE_SUCCESS('soportecli.casos_celdas_at.send_file', '{str_filedate}');
                END;""",
                'files_permission': "group",
                'search_time_ago': '{"days": 30}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "fec_insert", 'src_fieldname': "0", 'type': "date", 'to_reload': None},
                    {'fieldname': "telefono", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latitud", 'src_fieldname': "2", 'type': "number", 'to_reload': None},
                    {'fieldname': "longitud", 'src_fieldname': "3", 'type': "number", 'to_reload': None},
                    {'fieldname': "tipificacion", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "escenario", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                ]
            },
        }