from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryIptConfigRepository(InMemoryConfigRepository):
    def __init__(self):
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'huawei_3g',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'src_query': """
                select
                    "bsc6900ucell",
                    "cell name",
                    "period (min)",
                    "start time",
                    "ne name",
                    "vs.cell.unavailtime.sys", "vs.amr.erlang.bestcell", "vs.hsdpa.meanrequiredpwr", "vs.rab.attestabcs.conv",
                    "vs.rab.abnormrel.cs", "vs.rab.normrel.cs", "vs.attcellupdt.detach.pch", "vs.attcellupdt.other.pch",
                    "vs.attcellupdt.reg.pch", "vs.attcellupdt.pagersp", "vs.attcellupdt.uldatatrans", "vs.rab.attestabps.bkg",
                    "vs.rab.attestabps.conv", "vs.rab.attestabps.int", "vs.rab.attestabps.str", "rrc.attconnestab.emgcall",
                    "rrc.attconnestab.orgbkgcall", "rrc.attconnestab.orgconvcall", "rrc.attconnestab.orgintercall", "rrc.attconnestab.orgsubcall",
                    "rrc.attconnestab.tmbkgcall", "rrc.attconnestab.tmconvcall", "rrc.attconnestab.tmintercall", "vs.rab.succestabcs.conv",
                    "vs.succcellupdt.pagersp", "vs.succcellupdt.uldatatrans", "vs.succcellupdt.detach.pch", "vs.succcellupdt.other.pch",
                    "vs.succcellupdt.reg.pch", "vs.rab.succestabps.bkg", "vs.rab.succestabps.conv", "vs.rab.succestabps.int",
                    "vs.rab.succestabps.str", "rrc.succconnestab.emgcall", "rrc.succconnestab.orgbkgcall", "rrc.succconnestab.orgconvcall",
                    "rrc.succconnestab.orgitrcall", "rrc.succconnestab.orgsubcall", "rrc.succconnestab.tmbkgcall", "rrc.succconnestab.tmconvcall",
                    "rrc.succconnestab.tmitrcall", "vs.hsdpa.all.schedulednum", "vs.hsdpa.dataoutput.traffic", "vs.hsdpa.datattinum.user",
                    "vs.rb.amr.dl.10.2", "vs.rb.amr.dl.12.2", "vs.rb.amr.dl.7.95", "vs.rb.amr.dl.7.4",
                    "vs.rb.amr.dl.5.9", "vs.rb.amr.dl.5.15", "vs.rb.amr.dl.4.75", "vs.rb.amr.dl.6.7",
                    "vs.rb.amrwb.dl.23.85", "vs.rb.amrwb.dl.23.05", "vs.rb.amrwb.dl.19.85", "vs.rb.amrwb.dl.18.25", "vs.rb.amrwb.dl.15.85",
                    "vs.rb.amrwb.dl.14.25", "vs.rb.amrwb.dl.12.65", "vs.rb.amrwb.dl.8.85", "vs.rb.amrwb.dl.6.60", "vs.hsdpa.meanchthr.totalbytes",
                    "vs.hsupa.meanchthr.totalbytes", "vs.ps.bkg.dl.128.traffic", "vs.ps.bkg.dl.144.traffic", "vs.ps.bkg.dl.16.traffic", "vs.ps.bkg.dl.256.traffic",
                    "vs.ps.bkg.dl.32.traffic", "vs.ps.bkg.dl.384.traffic", "vs.ps.bkg.dl.64.traffic", "vs.ps.bkg.dl.8.traffic", "vs.ps.bkg.ul.128.traffic",
                    "vs.ps.bkg.ul.144.traffic", "vs.ps.bkg.ul.16.traffic", "vs.ps.bkg.ul.256.traffic", "vs.ps.bkg.ul.32.traffic", "vs.ps.bkg.ul.384.traffic",
                    "vs.ps.bkg.ul.64.traffic", "vs.ps.bkg.ul.8.traffic", "vs.ps.conv.dl.traffic", "vs.ps.conv.ul.traffic", "vs.ps.int.dl.128.traffic",
                    "vs.ps.int.dl.144.traffic", "vs.ps.int.dl.16.traffic", "vs.ps.int.dl.256.traffic", "vs.ps.int.dl.32.traffic", "vs.ps.int.dl.384.traffic",
                    "vs.ps.int.dl.64.traffic",
                    "vs.ps.int.dl.8.traffic", "vs.ps.int.ul.128.traffic", "vs.ps.int.ul.144.traffic", "vs.ps.int.ul.16.traffic", "vs.ps.int.ul.256.traffic",
                    "vs.ps.int.ul.32.traffic", "vs.ps.int.ul.384.traffic", "vs.ps.int.ul.64.traffic", "vs.ps.int.ul.8.traffic", "vs.ps.str.dl.128.traffic",
                    "vs.ps.str.dl.144.traffic", "vs.ps.str.dl.16.traffic", "vs.ps.str.dl.256.traffic", "vs.ps.str.dl.32.traffic", "vs.ps.str.dl.384.traffic",
                    "vs.ps.str.dl.64.traffic", "vs.ps.str.dl.8.traffic", "vs.ps.str.ul.128.traffic", "vs.ps.str.ul.16.traffic", "vs.ps.str.ul.32.traffic",
                    "vs.ps.str.ul.64.traffic", "vs.ps.str.ul.8.traffic", "vs.psr99.p2d.succ", "vs.hsdpa.p2h.succ", "vs.dccc.p2f.succ", "vs.dccc.urap2f.succ",
                    "rrc.attconnestab.rep.orgbkgcall", "rrc.attconnestab.rep.orgintercall", "rrc.attconnestab.rep.orgsubcall", "rrc.attconnestab.rep.tmbkgcall",
                    "rrc.attconnestab.rep.tmintercall", "vs.psr99.p2d.att", "vs.hsdpa.p2h.att", "vs.dccc.p2f.att", "vs.dccc.urap2f.att", "vs.cell.unavailtime",
                    "quantity", "vs.cellpchues", "vs.cellfachues", "vs.celldchues", "vs.meanrtwp", "vs.hsdpa.ue.mean.cell", "vs.dcchsrb.dl.traffic",
                    "vs.dcchsrbkbps.dl", "vs.rb.ps.bkg.dl.8", "vs.rb.ps.bkg.dl.16", "vs.rb.ps.bkg.dl.32", "vs.rb.ps.bkg.dl.64", "vs.rb.ps.bkg.dl.128",
                    "vs.rb.ps.bkg.dl.144", "vs.rb.ps.bkg.dl.256", "vs.rb.ps.bkg.dl.384", "vs.rb.ps.int.dl.8", "vs.rb.ps.int.dl.16", "vs.rb.ps.int.dl.32",
                    "vs.rb.ps.int.dl.64", "vs.rb.ps.int.dl.128", "vs.rb.ps.int.dl.144", "vs.rb.ps.int.dl.256", "vs.rb.ps.int.dl.384", "vs.rb.ps.conv.dl.42.8",
                    "vs.rb.ps.conv.dl.40", "vs.rb.ps.conv.dl.39.2", "vs.rb.ps.conv.dl.38.8", "vs.rb.ps.str.dl.8", "vs.rb.ps.str.dl.16", "vs.rb.ps.str.dl.32",
                    "vs.rb.ps.str.dl.64", "vs.rb.ps.str.dl.128", "vs.rb.ps.str.dl.144", "vs.rb.ps.str.dl.256.384", "vs.rb.ps.conv.dl.64",
                    "vs.srnciubbytespsr99conv.tx", "vs.srnciubbytespsr99str.tx", "vs.srnciubbytespsr99int.tx", "vs.srnciubbytespsr99bkg.tx",
                    "vs.srnciubbyteshsdpa.tx", "vs.crnciubbytesfach.tx", "vs.crnciubbytesefach.tx", "vs.ippool.adjnode.ping.maxdelay",
                    "vs.ippool.adjnode.ping.maxjitter", "vs.ippool.adjnode.ping.maxlost", "vs.ippool.adjnode.ping.meandelay",
                    "vs.ippool.adjnode.ping.meanjitter", "vs.ippool.adjnode.ping.meanlost", "vs.rab.normrel.amrwb", "vs.rab.abnormrel.amrwb",
                    "vs.rab.succestabcs.str", "vs.rab.attestabcs.str", "vs.rab.abnormrel.amr", "vs.rab.normrel.amr"
                from CLARO.counter_huawei_3g
                where %(fecha_ini)s <= "start time" and "start time" < %(fecha_fin)s
                """,
                "src_query_finder": """select "start time" as fecha from CLARO.counter_huawei_3g WHERE "start time" > now() - interval '2' day group by "start time" """,
                # "src_bucket": "claro-pe-pro-storage",
                # 'work_dir': 'exports/daily_district_aggregate/Peru/{date}',
                # 'wk_date_format': '%Y%m%d',
                'file_pattern': 'huawei_3g_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'chunk_limit': 1000,
                'tablename': "ipt_counter_huawei_3g",
                'queue_id': "ipt.huawei_3g",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_IPT_FILE_SUCCESS('ipt.huawei_3g', '{file_date}');
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "bsc6900ucell", 'src_fieldname': "bsc6900ucell", 'type': "varchar2"},
                    {'fieldname': "cell_name", 'src_fieldname': "cell name", 'type': "varchar2"},
                    {'fieldname': "period_min", 'src_fieldname': "period (min)", 'type': "varchar2"},
                    {'fieldname': "start_time", 'src_fieldname': "start time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "ne_name", 'src_fieldname': "ne name", 'type': "varchar2"},
                    {'fieldname': "vsd_celld_unavailtimed_sys", 'src_fieldname': "vs.cell.unavailtime.sys", 'type': "number"},
                    {'fieldname': "vsd_amrd_erlangd_bestcell", 'src_fieldname': "vs.amr.erlang.bestcell", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_meanrequiredpwr", 'src_fieldname': "vs.hsdpa.meanrequiredpwr", 'type': "number"},
                    {'fieldname': "vsd_rabd_attestabcsd_conv", 'src_fieldname': "vs.rab.attestabcs.conv", 'type': "number"},
                    {'fieldname': "vsd_rabd_abnormreld_cs", 'src_fieldname': "vs.rab.abnormrel.cs", 'type': "number"},
                    {'fieldname': "vsd_rabd_normreld_cs", 'src_fieldname': "vs.rab.normrel.cs", 'type': "number"},
                    {'fieldname': "vsd_attcellupdtd_detachd_pch", 'src_fieldname': "vs.attcellupdt.detach.pch", 'type': "number"},
                    {'fieldname': "vsd_attcellupdtd_otherd_pch", 'src_fieldname': "vs.attcellupdt.other.pch", 'type': "number"},
                    {'fieldname': "vsd_attcellupdtd_regd_pch", 'src_fieldname': "vs.attcellupdt.reg.pch", 'type': "number"},
                    {'fieldname': "vsd_attcellupdtd_pagersp", 'src_fieldname': "vs.attcellupdt.pagersp", 'type': "number"},
                    {'fieldname': "vsd_attcellupdtd_uldatatrans", 'src_fieldname': "vs.attcellupdt.uldatatrans", 'type': "number"},
                    {'fieldname': "vsd_rabd_attestabpsd_bkg", 'src_fieldname': "vs.rab.attestabps.bkg", 'type': "number"},
                    {'fieldname': "vsd_rabd_attestabpsd_conv", 'src_fieldname': "vs.rab.attestabps.conv", 'type': "number"},
                    {'fieldname': "vsd_rabd_attestabpsd_int", 'src_fieldname': "vs.rab.attestabps.int", 'type': "number"},
                    {'fieldname': "vsd_rabd_attestabpsd_str", 'src_fieldname': "vs.rab.attestabps.str", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_emgcall", 'src_fieldname': "rrc.attconnestab.emgcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_orgbkgcall", 'src_fieldname': "rrc.attconnestab.orgbkgcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_orgconvcall", 'src_fieldname': "rrc.attconnestab.orgconvcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_orgintercall", 'src_fieldname': "rrc.attconnestab.orgintercall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_orgsubcall", 'src_fieldname': "rrc.attconnestab.orgsubcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_tmbkgcall", 'src_fieldname': "rrc.attconnestab.tmbkgcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_tmconvcall", 'src_fieldname': "rrc.attconnestab.tmconvcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_tmintercall", 'src_fieldname': "rrc.attconnestab.tmintercall", 'type': "number"},
                    {'fieldname': "vsd_rabd_succestabcsd_conv", 'src_fieldname': "vs.rab.succestabcs.conv", 'type': "number"},
                    {'fieldname': "vsd_succcellupdtd_pagersp", 'src_fieldname': "vs.succcellupdt.pagersp", 'type': "number"},
                    {'fieldname': "vsd_succcellupdtd_uldatatrans", 'src_fieldname': "vs.succcellupdt.uldatatrans", 'type': "number"},
                    {'fieldname': "vsd_succcellupdtd_detachd_pch", 'src_fieldname': "vs.succcellupdt.detach.pch", 'type': "number"},
                    {'fieldname': "vsd_succcellupdtd_otherd_pch", 'src_fieldname': "vs.succcellupdt.other.pch", 'type': "number"},
                    {'fieldname': "vsd_succcellupdtd_regd_pch", 'src_fieldname': "vs.succcellupdt.reg.pch", 'type': "number"},
                    {'fieldname': "vsd_rabd_succestabpsd_bkg", 'src_fieldname': "vs.rab.succestabps.bkg", 'type': "number"},
                    {'fieldname': "vsd_rabd_succestabpsd_conv", 'src_fieldname': "vs.rab.succestabps.conv", 'type': "number"},
                    {'fieldname': "vsd_rabd_succestabpsd_int", 'src_fieldname': "vs.rab.succestabps.int", 'type': "number"},
                    {'fieldname': "vsd_rabd_succestabpsd_str", 'src_fieldname': "vs.rab.succestabps.str", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_emgcall", 'src_fieldname': "rrc.succconnestab.emgcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_orgbkgcall", 'src_fieldname': "rrc.succconnestab.orgbkgcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_orgconvcall", 'src_fieldname': "rrc.succconnestab.orgconvcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_orgitrcall", 'src_fieldname': "rrc.succconnestab.orgitrcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_orgsubcall", 'src_fieldname': "rrc.succconnestab.orgsubcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_tmbkgcall", 'src_fieldname': "rrc.succconnestab.tmbkgcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_tmconvcall", 'src_fieldname': "rrc.succconnestab.tmconvcall", 'type': "number"},
                    {'fieldname': "rrcd_succconnestabd_tmitrcall", 'src_fieldname': "rrc.succconnestab.tmitrcall", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_alld_schedulednum", 'src_fieldname': "vs.hsdpa.all.schedulednum", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_dataoutputd_traffic", 'src_fieldname': "vs.hsdpa.dataoutput.traffic", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_datattinumd_user", 'src_fieldname': "vs.hsdpa.datattinum.user", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_10d_2", 'src_fieldname': "vs.rb.amr.dl.10.2", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_12d_2", 'src_fieldname': "vs.rb.amr.dl.12.2", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_7d_95", 'src_fieldname': "vs.rb.amr.dl.7.95", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_7d_4", 'src_fieldname': "vs.rb.amr.dl.7.4", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_5d_9", 'src_fieldname': "vs.rb.amr.dl.5.9", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_5d_15", 'src_fieldname': "vs.rb.amr.dl.5.15", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_4d_75", 'src_fieldname': "vs.rb.amr.dl.4.75", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrd_dld_6d_7", 'src_fieldname': "vs.rb.amr.dl.6.7", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_23d_85", 'src_fieldname': "vs.rb.amrwb.dl.23.85", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_23d_05", 'src_fieldname': "vs.rb.amrwb.dl.23.05", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_19d_85", 'src_fieldname': "vs.rb.amrwb.dl.19.85", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_18d_25", 'src_fieldname': "vs.rb.amrwb.dl.18.25", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_15d_85", 'src_fieldname': "vs.rb.amrwb.dl.15.85", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_14d_25", 'src_fieldname': "vs.rb.amrwb.dl.14.25", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_12d_65", 'src_fieldname': "vs.rb.amrwb.dl.12.65", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_8d_85", 'src_fieldname': "vs.rb.amrwb.dl.8.85", 'type': "number"},
                    {'fieldname': "vsd_rbd_amrwbd_dld_6d_60", 'src_fieldname': "vs.rb.amrwb.dl.6.60", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_meanchthrd_totalbytes", 'src_fieldname': "vs.hsdpa.meanchthr.totalbytes", 'type': "number"},
                    {'fieldname': "vsd_hsupad_meanchthrd_totalbytes", 'src_fieldname': "vs.hsupa.meanchthr.totalbytes", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_128d_traffic", 'src_fieldname': "vs.ps.bkg.dl.128.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_144d_traffic", 'src_fieldname': "vs.ps.bkg.dl.144.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_16d_traffic", 'src_fieldname': "vs.ps.bkg.dl.16.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_256d_traffic", 'src_fieldname': "vs.ps.bkg.dl.256.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_32d_traffic", 'src_fieldname': "vs.ps.bkg.dl.32.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_384d_traffic", 'src_fieldname': "vs.ps.bkg.dl.384.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_64d_traffic", 'src_fieldname': "vs.ps.bkg.dl.64.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_dld_8d_traffic", 'src_fieldname': "vs.ps.bkg.dl.8.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_128d_traffic", 'src_fieldname': "vs.ps.bkg.ul.128.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_144d_traffic", 'src_fieldname': "vs.ps.bkg.ul.144.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_16d_traffic", 'src_fieldname': "vs.ps.bkg.ul.16.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_256d_traffic", 'src_fieldname': "vs.ps.bkg.ul.256.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_32d_traffic", 'src_fieldname': "vs.ps.bkg.ul.32.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_384d_traffic", 'src_fieldname': "vs.ps.bkg.ul.384.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_64d_traffic", 'src_fieldname': "vs.ps.bkg.ul.64.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_bkgd_uld_8d_traffic", 'src_fieldname': "vs.ps.bkg.ul.8.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_convd_dld_traffic", 'src_fieldname': "vs.ps.conv.dl.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_convd_uld_traffic", 'src_fieldname': "vs.ps.conv.ul.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_128d_traffic", 'src_fieldname': "vs.ps.int.dl.128.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_144d_traffic", 'src_fieldname': "vs.ps.int.dl.144.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_16d_traffic", 'src_fieldname': "vs.ps.int.dl.16.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_256d_traffic", 'src_fieldname': "vs.ps.int.dl.256.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_32d_traffic", 'src_fieldname': "vs.ps.int.dl.32.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_384d_traffic", 'src_fieldname': "vs.ps.int.dl.384.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_64d_traffic", 'src_fieldname': "vs.ps.int.dl.64.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_dld_8d_traffic", 'src_fieldname': "vs.ps.int.dl.8.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_128d_traffic", 'src_fieldname': "vs.ps.int.ul.128.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_144d_traffic", 'src_fieldname': "vs.ps.int.ul.144.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_16d_traffic", 'src_fieldname': "vs.ps.int.ul.16.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_256d_traffic", 'src_fieldname': "vs.ps.int.ul.256.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_32d_traffic", 'src_fieldname': "vs.ps.int.ul.32.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_384d_traffic", 'src_fieldname': "vs.ps.int.ul.384.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_64d_traffic", 'src_fieldname': "vs.ps.int.ul.64.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_intd_uld_8d_traffic", 'src_fieldname': "vs.ps.int.ul.8.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_128d_traffic", 'src_fieldname': "vs.ps.str.dl.128.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_144d_traffic", 'src_fieldname': "vs.ps.str.dl.144.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_16d_traffic", 'src_fieldname': "vs.ps.str.dl.16.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_256d_traffic", 'src_fieldname': "vs.ps.str.dl.256.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_32d_traffic", 'src_fieldname': "vs.ps.str.dl.32.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_384d_traffic", 'src_fieldname': "vs.ps.str.dl.384.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_64d_traffic", 'src_fieldname': "vs.ps.str.dl.64.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_dld_8d_traffic", 'src_fieldname': "vs.ps.str.dl.8.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_uld_128d_traffic", 'src_fieldname': "vs.ps.str.ul.128.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_uld_16d_traffic", 'src_fieldname': "vs.ps.str.ul.16.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_uld_32d_traffic", 'src_fieldname': "vs.ps.str.ul.32.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_uld_64d_traffic", 'src_fieldname': "vs.ps.str.ul.64.traffic", 'type': "number"},
                    {'fieldname': "vsd_psd_strd_uld_8d_traffic", 'src_fieldname': "vs.ps.str.ul.8.traffic", 'type': "number"},
                    {'fieldname': "vsd_psr99d_p2dd_succ", 'src_fieldname': "vs.psr99.p2d.succ", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_p2hd_succ", 'src_fieldname': "vs.hsdpa.p2h.succ", 'type': "number"},
                    {'fieldname': "vsd_dcccd_p2fd_succ", 'src_fieldname': "vs.dccc.p2f.succ", 'type': "number"},
                    {'fieldname': "vsd_dcccd_urap2fd_succ", 'src_fieldname': "vs.dccc.urap2f.succ", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_repd_orgbkgcall", 'src_fieldname': "rrc.attconnestab.rep.orgbkgcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_repd_orgintercall", 'src_fieldname': "rrc.attconnestab.rep.orgintercall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_repd_orgsubcall", 'src_fieldname': "rrc.attconnestab.rep.orgsubcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_repd_tmbkgcall", 'src_fieldname': "rrc.attconnestab.rep.tmbkgcall", 'type': "number"},
                    {'fieldname': "rrcd_attconnestabd_repd_tmintercall", 'src_fieldname': "rrc.attconnestab.rep.tmintercall", 'type': "number"},
                    {'fieldname': "vsd_psr99d_p2dd_att", 'src_fieldname': "vs.psr99.p2d.att", 'type': "number"},
                    {'fieldname': "vsd_hsdpad_p2hd_att", 'src_fieldname': "vs.hsdpa.p2h.att", 'type': "number"},
                    {'fieldname': "vsd_dcccd_p2fd_att", 'src_fieldname': "vs.dccc.p2f.att", 'type': "number"},
                    {'fieldname': "vsd_dcccd_urap2fd_att", 'src_fieldname': "vs.dccc.urap2f.att", 'type': "number"},
                    {'fieldname': "vsd_celld_unavailtime", 'src_fieldname': "vs.cell.unavailtime", 'type': "number"},
                    {'fieldname': "quantity", 'src_fieldname': "quantity", 'type': "number"},
                    {'fieldname': "vs_cellpchues", 'src_fieldname': "vs.cellpchues", 'type': "number"},
                    {'fieldname': "vs_cellfachues", 'src_fieldname': "vs.cellfachues", 'type': "number"},
                    {'fieldname': "vs_celldchues", 'src_fieldname': "vs.celldchues", 'type': "number"},
                    {'fieldname': "vs_meanrtwp", 'src_fieldname': "vs.meanrtwp", 'type': "number"},
                    {'fieldname': "vs_hsdpa_ue_mean_cell", 'src_fieldname': "vs.hsdpa.ue.mean.cell", 'type': "number"},
                    {'fieldname': "vs_dcchsrb_dl_traffic", 'src_fieldname': "vs.dcchsrb.dl.traffic", 'type': "number"},
                    {'fieldname': "vs_dcchsrbkbps_dl", 'src_fieldname': "vs.dcchsrbkbps.dl", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_8", 'src_fieldname': "vs.rb.ps.bkg.dl.8", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_16", 'src_fieldname': "vs.rb.ps.bkg.dl.16", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_32", 'src_fieldname': "vs.rb.ps.bkg.dl.32", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_64", 'src_fieldname': "vs.rb.ps.bkg.dl.64", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_128", 'src_fieldname': "vs.rb.ps.bkg.dl.128", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_144", 'src_fieldname': "vs.rb.ps.bkg.dl.144", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_256", 'src_fieldname': "vs.rb.ps.bkg.dl.256", 'type': "number"},
                    {'fieldname': "vs_rb_ps_bkg_dl_384", 'src_fieldname': "vs.rb.ps.bkg.dl.384", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_8", 'src_fieldname': "vs.rb.ps.int.dl.8", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_16", 'src_fieldname': "vs.rb.ps.int.dl.16", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_32", 'src_fieldname': "vs.rb.ps.int.dl.32", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_64", 'src_fieldname': "vs.rb.ps.int.dl.64", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_128", 'src_fieldname': "vs.rb.ps.int.dl.128", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_144", 'src_fieldname': "vs.rb.ps.int.dl.144", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_256", 'src_fieldname': "vs.rb.ps.int.dl.256", 'type': "number"},
                    {'fieldname': "vs_rb_ps_int_dl_384", 'src_fieldname': "vs.rb.ps.int.dl.384", 'type': "number"},
                    {'fieldname': "vs_rb_ps_conv_dl_42_8", 'src_fieldname': "vs.rb.ps.conv.dl.42.8", 'type': "number"},
                    {'fieldname': "vs_rb_ps_conv_dl_40", 'src_fieldname': "vs.rb.ps.conv.dl.40", 'type': "number"},
                    {'fieldname': "vs_rb_ps_conv_dl_39_2", 'src_fieldname': "vs.rb.ps.conv.dl.39.2", 'type': "number"},
                    {'fieldname': "vs_rb_ps_conv_dl_38_8", 'src_fieldname': "vs.rb.ps.conv.dl.38.8", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_8", 'src_fieldname': "vs.rb.ps.str.dl.8", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_16", 'src_fieldname': "vs.rb.ps.str.dl.16", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_32", 'src_fieldname': "vs.rb.ps.str.dl.32", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_64", 'src_fieldname': "vs.rb.ps.str.dl.64", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_128", 'src_fieldname': "vs.rb.ps.str.dl.128", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_144", 'src_fieldname': "vs.rb.ps.str.dl.144", 'type': "number"},
                    {'fieldname': "vs_rb_ps_str_dl_256_384", 'src_fieldname': "vs.rb.ps.str.dl.256.384", 'type': "number"},
                    {'fieldname': "vs_rb_ps_conv_dl_64", 'src_fieldname': "vs.rb.ps.conv.dl.64", 'type': "number"},
                    {'fieldname': "vs_srnciubbytespsr99conv_tx", 'src_fieldname': "vs.srnciubbytespsr99conv.tx", 'type': "number"},
                    {'fieldname': "vs_srnciubbytespsr99str_tx", 'src_fieldname': "vs.srnciubbytespsr99str.tx", 'type': "number"},
                    {'fieldname': "vs_srnciubbytespsr99int_tx", 'src_fieldname': "vs.srnciubbytespsr99int.tx", 'type': "number"},
                    {'fieldname': "vs_srnciubbytespsr99bkg_tx", 'src_fieldname': "vs.srnciubbytespsr99bkg.tx", 'type': "number"},
                    {'fieldname': "vs_srnciubbyteshsdpa_tx", 'src_fieldname': "vs.srnciubbyteshsdpa.tx", 'type': "number"},
                    {'fieldname': "vs_crnciubbytesfach_tx", 'src_fieldname': "vs.crnciubbytesfach.tx", 'type': "number"},
                    {'fieldname': "vs_crnciubbytesefach_tx", 'src_fieldname': "vs.crnciubbytesefach.tx", 'type': "number"},
                    {'fieldname': "vs_ippool_adjnode_ping_maxdelay", 'src_fieldname': "vs.ippool.adjnode.ping.maxdelay", 'type': "number"},
                    {'fieldname': "vs_ippool_adjnode_ping_maxjitter", 'src_fieldname': "vs.ippool.adjnode.ping.maxjitter", 'type': "number"},
                    {'fieldname': "vs_ippool_adjnode_ping_maxlost", 'src_fieldname': "vs.ippool.adjnode.ping.maxlost", 'type': "number"},
                    {'fieldname': "vs_ippool_adjnode_ping_meandelay", 'src_fieldname': "vs.ippool.adjnode.ping.meandelay", 'type': "number"},
                    {'fieldname': "vs_ippool_adjnode_ping_meanjitter", 'src_fieldname': "vs.ippool.adjnode.ping.meanjitter", 'type': "number"},
                    {'fieldname': "vs_ippool_adjnode_ping_meanlost", 'src_fieldname': "vs.ippool.adjnode.ping.meanlost", 'type': "number"},
                    {'fieldname': "vs_rab_normrel_amrwb", 'src_fieldname': "vs.rab.normrel.amrwb", 'type': "number"},
                    {'fieldname': "vs_rab_abnormrel_amrwb", 'src_fieldname': "vs.rab.abnormrel.amrwb", 'type': "number"},
                    {'fieldname': "vs_rab_succestabcs_str", 'src_fieldname': "vs.rab.succestabcs.str", 'type': "number"},
                    {'fieldname': "vs_rab_attestabcs_str", 'src_fieldname': "vs.rab.attestabcs.str", 'type': "number"},
                    {'fieldname': "vs_rab_abnormrel_amr", 'src_fieldname': "vs.rab.abnormrel.amr", 'type': "number"},
                    {'fieldname': "vs_rab_normrel_amr", 'src_fieldname': "vs.rab.normrel.amr", 'type': "number"},
                ]
            },
            "2": {
                'id': '2',
                'name': 'huawei_4g',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'src_query': """
                select
                    "start time", "period (min)", "ne name", "cell name", "cell", "l.rrc.connreq.succ.emc", "l.rrc.connreq.succ.highpri",
                    "l.rrc.connreq.succ.mt", "l.rrc.connreq.succ.modata", "l.rrc.connreq.succ.delaytol", "l.rrc.connreq.att.emc",
                    "l.rrc.connreq.att.highpri", "l.rrc.connreq.att.mt", "l.rrc.connreq.att.modata", "l.rrc.connreq.att.delaytol",
                    "l.e-rab.succest", "l.e-rab.attest", "l.s1sig.connest.succ", "l.s1sig.connest.att", "l.thrp.bits.dl.qci.6",
                    "l.thrp.bits.dl.qci.7", "l.thrp.bits.dl.qci.8", "l.thrp.bits.dl.lasttti.qci.6", "l.thrp.bits.dl.lasttti.qci.7",
                    "l.thrp.bits.dl.lasttti.qci.8", "l.thrp.time.dl.rmvlasttti.qci.6", "l.thrp.time.dl.rmvlasttti.qci.7",
                    "l.thrp.time.dl.rmvlasttti.qci.8", "l.cell.unavail.dur.sys", "l.chmeas.prb.dl.used.avg", "l.chmeas.prb.dl.avail",
                    "l.thrp.bits.ul.qci.6", "l.thrp.bits.ul.qci.7", "l.thrp.bits.ul.qci.8", "l.cell.unavail.dur.manual",
                    "l.csfb.e2w", "l.csfb.prepatt", "l.e-rab.succest.qci.1", "l.e-rab.attest.qci.1", "l.e-rab.succest.qci.5",
                    "l.e-rab.attest.qci.5", "l.e-rab.abnormrel.qci.1", "l.e-rab.normrel.qci.1", "l.voice.e2evqi.amrwb.totalvalue",
                    "l.voice.e2evqi.amrwb.excellent.times", "l.voice.e2evqi.amrwb.good.times", "l.voice.e2evqi.amrwb.accept.times",
                    "l.voice.e2evqi.amrwb.poor.times", "l.voice.e2evqi.amrwb.bad.times", "l.chmeas.cqi.dl.1", "l.chmeas.cqi.dl.2",
                    "l.chmeas.cqi.dl.3", "l.chmeas.cqi.dl.4", "l.chmeas.cqi.dl.5", "l.chmeas.cqi.dl.6", "l.chmeas.cqi.dl.7",
                    "l.chmeas.cqi.dl.8", "l.chmeas.cqi.dl.9", "l.chmeas.cqi.dl.10", "l.chmeas.cqi.dl.11", "l.chmeas.cqi.dl.12",
                    "l.chmeas.cqi.dl.13", "l.chmeas.cqi.dl.14", "l.chmeas.cqi.dl.15", "l.chmeas.cqi.dl.0",
                    "l.iratho.srvcc.e2w.execsuccout", "l.iratho.srvcc.e2w.mmeabnormrsp", "l.iratho.srvcc.e2w.execattout",
                    "l.iratho.srvcc.e2w.prepattout", "l.cell.avail.dur", "l.thrp.bits.ul", "l.thrp.bits.dl", "l.thrp.bits.dl.qci.9",
                    "l.thrp.time.dl.rmvlasttti.qci.9", "l.thrp.bits.dl.lasttti.qci.9", "l.traffic.user.avg", "l.ul.interference.avg",
                    "l.chmeas.prb.ul.used.avg", "l.chmeas.prb.ul.avail", "l.e-rab.failest.tnl", "l.e-rab.abnormrel.tnl",
                    "l.thrp.time.dl.rmvlasttti", "l.rrc.connreq.succ", "l.rrc.connreq.att", "l.thrp.bits.dl.lasttti"
                    from CLARO.counter_huawei_4g
                where %(fecha_ini)s <= "start time" and "start time" < %(fecha_fin)s
                """,
                "src_query_finder": """select "start time" as fecha from CLARO.counter_huawei_4g
                WHERE "start time" > now() - interval '2' day group by "start time" """,
                'file_pattern': 'huawei_4g_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'chunk_limit': 1000,
                'tablename': "ipt_counter_huawei_4g",
                'queue_id': "ipt.huawei_4g",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_IPT_FILE_SUCCESS('ipt.huawei_4g', '{file_date}');
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "start_time", 'src_fieldname': "start time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "period_min", 'src_fieldname': "period (min)", 'type': "varchar2"},
                    {'fieldname': "ne_name", 'src_fieldname': "ne name", 'type': "varchar2"},
                    {'fieldname': "cell_name", 'src_fieldname': "cell name", 'type': "varchar2"},
                    {'fieldname': "cell", 'src_fieldname': "cell", 'type': "varchar2"},
                    {'fieldname': "l_rrc_connreq_succ_emc", 'src_fieldname': "l.rrc.connreq.succ.emc", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_succ_highpri", 'src_fieldname': "l.rrc.connreq.succ.highpri", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_succ_mt", 'src_fieldname': "l.rrc.connreq.succ.mt", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_succ_modata", 'src_fieldname': "l.rrc.connreq.succ.modata", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_succ_delaytol", 'src_fieldname': "l.rrc.connreq.succ.delaytol", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_att_emc", 'src_fieldname': "l.rrc.connreq.att.emc", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_att_highpri", 'src_fieldname': "l.rrc.connreq.att.highpri", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_att_mt", 'src_fieldname': "l.rrc.connreq.att.mt", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_att_modata", 'src_fieldname': "l.rrc.connreq.att.modata", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_att_delaytol", 'src_fieldname': "l.rrc.connreq.att.delaytol", 'type': "number"},
                    {'fieldname': "l_e_rab_succest", 'src_fieldname': "l.e-rab.succest", 'type': "number"},
                    {'fieldname': "l_e_rab_attest", 'src_fieldname': "l.e-rab.attest", 'type': "number"},
                    {'fieldname': "l_s1sig_connest_succ", 'src_fieldname': "l.s1sig.connest.succ", 'type': "number"},
                    {'fieldname': "l_s1sig_connest_att", 'src_fieldname': "l.s1sig.connest.att", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_qci_6", 'src_fieldname': "l.thrp.bits.dl.qci.6", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_qci_7", 'src_fieldname': "l.thrp.bits.dl.qci.7", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_qci_8", 'src_fieldname': "l.thrp.bits.dl.qci.8", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_lasttti_qci_6", 'src_fieldname': "l.thrp.bits.dl.lasttti.qci.6", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_lasttti_qci_7", 'src_fieldname': "l.thrp.bits.dl.lasttti.qci.7", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_lasttti_qci_8", 'src_fieldname': "l.thrp.bits.dl.lasttti.qci.8", 'type': "number"},
                    {'fieldname': "l_thrp_time_dl_rmvlasttti_qci_6", 'src_fieldname': "l.thrp.time.dl.rmvlasttti.qci.6", 'type': "number"},
                    {'fieldname': "l_thrp_time_dl_rmvlasttti_qci_7", 'src_fieldname': "l.thrp.time.dl.rmvlasttti.qci.7", 'type': "number"},
                    {'fieldname': "l_thrp_time_dl_rmvlasttti_qci_8", 'src_fieldname': "l.thrp.time.dl.rmvlasttti.qci.8", 'type': "number"},
                    {'fieldname': "l_cell_unavail_dur_sys", 'src_fieldname': "l.cell.unavail.dur.sys", 'type': "number"},
                    {'fieldname': "l_chmeas_prb_dl_used_avg", 'src_fieldname': "l.chmeas.prb.dl.used.avg", 'type': "number"},
                    {'fieldname': "l_chmeas_prb_dl_avail", 'src_fieldname': "l.chmeas.prb.dl.avail", 'type': "number"},
                    {'fieldname': "l_thrp_bits_ul_qci_6", 'src_fieldname': "l.thrp.bits.ul.qci.6", 'type': "number"},
                    {'fieldname': "l_thrp_bits_ul_qci_7", 'src_fieldname': "l.thrp.bits.ul.qci.7", 'type': "number"},
                    {'fieldname': "l_thrp_bits_ul_qci_8", 'src_fieldname': "l.thrp.bits.ul.qci.8", 'type': "number"},
                    {'fieldname': "l_cell_unavail_dur_manual", 'src_fieldname': "l.cell.unavail.dur.manual", 'type': "number"},
                    {'fieldname': "l_csfb_e2w", 'src_fieldname': "l.csfb.e2w", 'type': "number"},
                    {'fieldname': "l_csfb_prepatt", 'src_fieldname': "l.csfb.prepatt", 'type': "number"},
                    {'fieldname': "l_e_rab_succest_qci_1", 'src_fieldname': "l.e-rab.succest.qci.1", 'type': "number"},
                    {'fieldname': "l_e_rab_attest_qci_1", 'src_fieldname': "l.e-rab.attest.qci.1", 'type': "number"},
                    {'fieldname': "l_e_rab_succest_qci_5", 'src_fieldname': "l.e-rab.succest.qci.5", 'type': "number"},
                    {'fieldname': "l_e_rab_attest_qci_5", 'src_fieldname': "l.e-rab.attest.qci.5", 'type': "number"},
                    {'fieldname': "l_e_rab_abnormrel_qci_1", 'src_fieldname': "l.e-rab.abnormrel.qci.1", 'type': "number"},
                    {'fieldname': "l_e_rab_normrel_qci_1", 'src_fieldname': "l.e-rab.normrel.qci.1", 'type': "number"},
                    {'fieldname': "l_voice_e2evqi_amrwb_totalvalue", 'src_fieldname': "l.voice.e2evqi.amrwb.totalvalue", 'type': "number"},
                    {'fieldname': "l_voice_e2evqi_amrwb_excellent_times", 'src_fieldname': "l.voice.e2evqi.amrwb.excellent.times", 'type': "number"},
                    {'fieldname': "l_voice_e2evqi_amrwb_good_times", 'src_fieldname': "l.voice.e2evqi.amrwb.good.times", 'type': "number"},
                    {'fieldname': "l_voice_e2evqi_amrwb_accept_times", 'src_fieldname': "l.voice.e2evqi.amrwb.accept.times", 'type': "number"},
                    {'fieldname': "l_voice_e2evqi_amrwb_poor_times", 'src_fieldname': "l.voice.e2evqi.amrwb.poor.times", 'type': "number"},
                    {'fieldname': "l_voice_e2evqi_amrwb_bad_times", 'src_fieldname': "l.voice.e2evqi.amrwb.bad.times", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_1", 'src_fieldname': "l.chmeas.cqi.dl.1", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_2", 'src_fieldname': "l.chmeas.cqi.dl.2", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_3", 'src_fieldname': "l.chmeas.cqi.dl.3", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_4", 'src_fieldname': "l.chmeas.cqi.dl.4", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_5", 'src_fieldname': "l.chmeas.cqi.dl.5", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_6", 'src_fieldname': "l.chmeas.cqi.dl.6", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_7", 'src_fieldname': "l.chmeas.cqi.dl.7", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_8", 'src_fieldname': "l.chmeas.cqi.dl.8", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_9", 'src_fieldname': "l.chmeas.cqi.dl.9", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_10", 'src_fieldname': "l.chmeas.cqi.dl.10", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_11", 'src_fieldname': "l.chmeas.cqi.dl.11", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_12", 'src_fieldname': "l.chmeas.cqi.dl.12", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_13", 'src_fieldname': "l.chmeas.cqi.dl.13", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_14", 'src_fieldname': "l.chmeas.cqi.dl.14", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_15", 'src_fieldname': "l.chmeas.cqi.dl.15", 'type': "number"},
                    {'fieldname': "l_chmeas_cqi_dl_0", 'src_fieldname': "l.chmeas.cqi.dl.0", 'type': "number"},
                    {'fieldname': "l_iratho_srvcc_e2w_execsuccout", 'src_fieldname': "l.iratho.srvcc.e2w.execsuccout", 'type': "number"},
                    {'fieldname': "l_iratho_srvcc_e2w_mmeabnormrsp", 'src_fieldname': "l.iratho.srvcc.e2w.mmeabnormrsp", 'type': "number"},
                    {'fieldname': "l_iratho_srvcc_e2w_execattout", 'src_fieldname': "l.iratho.srvcc.e2w.execattout", 'type': "number"},
                    {'fieldname': "l_iratho_srvcc_e2w_prepattout", 'src_fieldname': "l.iratho.srvcc.e2w.prepattout", 'type': "number"},
                    {'fieldname': "l_cell_avail_dur", 'src_fieldname': "l.cell.avail.dur", 'type': "number"},
                    {'fieldname': "l_thrp_bits_ul", 'src_fieldname': "l.thrp.bits.ul", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl", 'src_fieldname': "l.thrp.bits.dl", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_qci_9", 'src_fieldname': "l.thrp.bits.dl.qci.9", 'type': "number"},
                    {'fieldname': "l_thrp_time_dl_rmvlasttti_qci_9", 'src_fieldname': "l.thrp.time.dl.rmvlasttti.qci.9", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_lasttti_qci_9", 'src_fieldname': "l.thrp.bits.dl.lasttti.qci.9", 'type': "number"},
                    {'fieldname': "l_traffic_user_avg", 'src_fieldname': "l.traffic.user.avg", 'type': "number"},
                    {'fieldname': "l_ul_interference_avg", 'src_fieldname': "l.ul.interference.avg", 'type': "number"},
                    {'fieldname': "l_chmeas_prb_ul_used_avg", 'src_fieldname': "l.chmeas.prb.ul.used.avg", 'type': "number"},
                    {'fieldname': "l_chmeas_prb_ul_avail", 'src_fieldname': "l.chmeas.prb.ul.avail", 'type': "number"},
                    {'fieldname': "l_e_rab_failest_tnl", 'src_fieldname': "l.e-rab.failest.tnl", 'type': "number"},
                    {'fieldname': "l_e_rab_abnormrel_tnl", 'src_fieldname': "l.e-rab.abnormrel.tnl", 'type': "number"},
                    {'fieldname': "l_thrp_time_dl_rmvlasttti", 'src_fieldname': "l.thrp.time.dl.rmvlasttti", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_succ", 'src_fieldname': "l.rrc.connreq.succ", 'type': "number"},
                    {'fieldname': "l_rrc_connreq_att", 'src_fieldname': "l.rrc.connreq.att", 'type': "number"},
                    {'fieldname': "l_thrp_bits_dl_lasttti", 'src_fieldname': "l.thrp.bits.dl.lasttti", 'type': "number"},
                ]
            },
            "3": {
                'id': '3',
                'name': 'ericsson_3g',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'src_query': """
                select
                rnc, start_time, rbs, cell, nombre_ebc, ci, lac, banda, sector, pmtotnorrcconnectreqcssucc,
                pmnocellupdatesuccmultics, pmtotnorrcconnectreqcs, pmnoloadsharingrrcconncs, pmnocellupdateattmultics,
                pmnorabestablishsuccessspeech, pmnorabestablishattemptspeech, pmnosystemrabreleasespeech,
                pmnonormalrabreleasespeech, pmtotnorrcconnectreqpssucc, pmchswitchsuccuradch, pmchswitchsuccurahs,
                pmchswitchsuccurafach, pmtotnorrcconnectreqps, pmnoloadsharingrrcconnps, pmchswitchattempturadch,
                pmchswitchattempturahs, pmchswitchattempturafach, pmnonormalnassignreleaseps, pmnosystemnassignreleaseps,
                pmnorabestablishsuccesspacketinteractivehs, pmnorabestablishattemptpacketinteractivehs,
                pmcelldowntimeauto, pmcelldowntimeman, erl_speech, pmsumackedbitspqspi01, pmsumnonemptyuserbufferspqspi01,
                pmsumackedbitspqspi03, pmsumnonemptyuserbufferspqspi03, pmtransmittedcarrierpowerhs, pmnoofhsuserspertti,
                pmsumbestcs12establish, pmsamplesbestcs12establish, pmsumbestamr4750rabestablish, pmsamplesbestamr4750rabestablish,
                pmsumbestamr5900rabestablish, pmsamplesbestamr5900rabestablish, pmsumbestamr7950rabestablish,
                pmsamplesbestamr7950rabestablish, pmsumbestamr12200rabestablish, pmsamplesbestamr12200rabestablish,
                pmsumbestamrwbrabestablish, pmsamplesbestamrwbrabestablish, pmsumbestamrnbmmrabestablish,
                pmsamplesbestamrnbmmrabestablish, pmdltrafficvolumepscommon, pmdltrafficvolumeps8, pmdltrafficvolumeps16,
                pmdltrafficvolumeps64, pmdltrafficvolumeps128, pmdltrafficvolumeps384, pmultrafficvolumepscommon,
                pmultrafficvolumeps8, pmultrafficvolumeps16, pmultrafficvolumeps64, pmultrafficvolumeps128, pmultrafficvolumeps384,
                pmdltrafficvolumepsinths, pmultrafficvolumepsinteul, pmnorabestablishsuccesscs57, pmnorabestablishsuccesscs64,
                pmnorabestablishattemptcs57, pmnorabestablishattemptcs64, pmnosystemrabreleaseamrnb, pmnosystemrabreleaseamrwb,
                pmnonormalrabreleaseamrnb, pmnonormalrabreleaseamrwb, pmnorabestablishsuccesspacketinteractive,
                pmnorabestablishattemptpacketinteractive
                from claro.counter_ericsson_3g
                where %(fecha_ini)s <= start_time and start_time < %(fecha_fin)s
                """,
                "src_query_finder": """select start_time as fecha from CLARO.counter_ericsson_3g
                WHERE start_time > now() - interval '2' day group by start_time """,
                'file_pattern': 'ericsson_3g_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'chunk_limit': 1000,
                'tablename': "ipt_counter_ericsson_3g",
                'queue_id': "ipt.ericsson_3g",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_IPT_FILE_SUCCESS('ipt.ericsson_3g', '{file_date}');
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "rnc", 'src_fieldname': "rnc", 'type': "varchar2"},
                    {'fieldname': "start_time", 'src_fieldname': "start_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "rbs", 'src_fieldname': "rbs", 'type': "varchar2"},
                    {'fieldname': "cell", 'src_fieldname': "cell", 'type': "varchar2"},
                    {'fieldname': "nombre_ebc", 'src_fieldname': "nombre_ebc", 'type': "varchar2"},
                    {'fieldname': "ci", 'src_fieldname': "ci", 'type': "varchar2"},
                    {'fieldname': "lac", 'src_fieldname': "lac", 'type': "varchar2"},
                    {'fieldname': "banda", 'src_fieldname': "banda", 'type': "varchar2"},
                    {'fieldname': "sector", 'src_fieldname': "sector", 'type': "varchar2"},
                    {'fieldname': "pmtotnorrcconnectreqcssucc", 'src_fieldname': "pmtotnorrcconnectreqcssucc", 'type': "number"},
                    {'fieldname': "pmnocellupdatesuccmultics", 'src_fieldname': "pmnocellupdatesuccmultics", 'type': "number"},
                    {'fieldname': "pmtotnorrcconnectreqcs", 'src_fieldname': "pmtotnorrcconnectreqcs", 'type': "number"},
                    {'fieldname': "pmnoloadsharingrrcconncs", 'src_fieldname': "pmnoloadsharingrrcconncs", 'type': "number"},
                    {'fieldname': "pmnocellupdateattmultics", 'src_fieldname': "pmnocellupdateattmultics", 'type': "number"},
                    {'fieldname': "pmnorabestablishsuccessspeech", 'src_fieldname': "pmnorabestablishsuccessspeech", 'type': "number"},
                    {'fieldname': "pmnorabestablishattemptspeech", 'src_fieldname': "pmnorabestablishattemptspeech", 'type': "number"},
                    {'fieldname': "pmnosystemrabreleasespeech", 'src_fieldname': "pmnosystemrabreleasespeech", 'type': "number"},
                    {'fieldname': "pmnonormalrabreleasespeech", 'src_fieldname': "pmnonormalrabreleasespeech", 'type': "number"},
                    {'fieldname': "pmtotnorrcconnectreqpssucc", 'src_fieldname': "pmtotnorrcconnectreqpssucc", 'type': "number"},
                    {'fieldname': "pmchswitchsuccuradch", 'src_fieldname': "pmchswitchsuccuradch", 'type': "number"},
                    {'fieldname': "pmchswitchsuccurahs", 'src_fieldname': "pmchswitchsuccurahs", 'type': "number"},
                    {'fieldname': "pmchswitchsuccurafach", 'src_fieldname': "pmchswitchsuccurafach", 'type': "number"},
                    {'fieldname': "pmtotnorrcconnectreqps", 'src_fieldname': "pmtotnorrcconnectreqps", 'type': "number"},
                    {'fieldname': "pmnoloadsharingrrcconnps", 'src_fieldname': "pmnoloadsharingrrcconnps", 'type': "number"},
                    {'fieldname': "pmchswitchattempturadch", 'src_fieldname': "pmchswitchattempturadch", 'type': "number"},
                    {'fieldname': "pmchswitchattempturahs", 'src_fieldname': "pmchswitchattempturahs", 'type': "number"},
                    {'fieldname': "pmchswitchattempturafach", 'src_fieldname': "pmchswitchattempturafach", 'type': "number"},
                    {'fieldname': "pmnonormalnassignreleaseps", 'src_fieldname': "pmnonormalnassignreleaseps", 'type': "number"},
                    {'fieldname': "pmnosystemnassignreleaseps", 'src_fieldname': "pmnosystemnassignreleaseps", 'type': "number"},
                    {'fieldname': "pmnorabestablishsuccesspacketinteractivehs", 'src_fieldname': "pmnorabestablishsuccesspacketinteractivehs", 'type': "number"},
                    {'fieldname': "pmnorabestablishattemptpacketinteractivehs", 'src_fieldname': "pmnorabestablishattemptpacketinteractivehs", 'type': "number"},
                    {'fieldname': "pmcelldowntimeauto", 'src_fieldname': "pmcelldowntimeauto", 'type': "number"},
                    {'fieldname': "pmcelldowntimeman", 'src_fieldname': "pmcelldowntimeman", 'type': "number"},
                    {'fieldname': "erl_speech", 'src_fieldname': "erl_speech", 'type': "number"},
                    {'fieldname': "pmsumackedbitspqspi01", 'src_fieldname': "pmsumackedbitspqspi01", 'type': "number"},
                    {'fieldname': "pmsumnonemptyuserbufferspqspi01", 'src_fieldname': "pmsumnonemptyuserbufferspqspi01", 'type': "number"},
                    {'fieldname': "pmsumackedbitspqspi03", 'src_fieldname': "pmsumackedbitspqspi03", 'type': "number"},
                    {'fieldname': "pmsumnonemptyuserbufferspqspi03", 'src_fieldname': "pmsumnonemptyuserbufferspqspi03", 'type': "number"},
                    {'fieldname': "pmtransmittedcarrierpowerhs", 'src_fieldname': "pmtransmittedcarrierpowerhs", 'type': "number"},
                    {'fieldname': "pmnoofhsuserspertti", 'src_fieldname': "pmnoofhsuserspertti", 'type': "number"},
                    {'fieldname': "pmsumbestcs12establish", 'src_fieldname': "pmsumbestcs12establish", 'type': "number"},
                    {'fieldname': "pmsamplesbestcs12establish", 'src_fieldname': "pmsamplesbestcs12establish", 'type': "number"},
                    {'fieldname': "pmsumbestamr4750rabestablish", 'src_fieldname': "pmsumbestamr4750rabestablish", 'type': "number"},
                    {'fieldname': "pmsamplesbestamr4750rabestablish", 'src_fieldname': "pmsamplesbestamr4750rabestablish", 'type': "number"},
                    {'fieldname': "pmsumbestamr5900rabestablish", 'src_fieldname': "pmsumbestamr5900rabestablish", 'type': "number"},
                    {'fieldname': "pmsamplesbestamr5900rabestablish", 'src_fieldname': "pmsamplesbestamr5900rabestablish", 'type': "number"},
                    {'fieldname': "pmsumbestamr7950rabestablish", 'src_fieldname': "pmsumbestamr7950rabestablish", 'type': "number"},
                    {'fieldname': "pmsamplesbestamr7950rabestablish", 'src_fieldname': "pmsamplesbestamr7950rabestablish", 'type': "number"},
                    {'fieldname': "pmsumbestamr12200rabestablish", 'src_fieldname': "pmsumbestamr12200rabestablish", 'type': "number"},
                    {'fieldname': "pmsamplesbestamr12200rabestablish", 'src_fieldname': "pmsamplesbestamr12200rabestablish", 'type': "number"},
                    {'fieldname': "pmsumbestamrwbrabestablish", 'src_fieldname': "pmsumbestamrwbrabestablish", 'type': "number"},
                    {'fieldname': "pmsamplesbestamrwbrabestablish", 'src_fieldname': "pmsamplesbestamrwbrabestablish", 'type': "number"},
                    {'fieldname': "pmsumbestamrnbmmrabestablish", 'src_fieldname': "pmsumbestamrnbmmrabestablish", 'type': "number"},
                    {'fieldname': "pmsamplesbestamrnbmmrabestablish", 'src_fieldname': "pmsamplesbestamrnbmmrabestablish", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumepscommon", 'src_fieldname': "pmdltrafficvolumepscommon", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumeps8", 'src_fieldname': "pmdltrafficvolumeps8", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumeps16", 'src_fieldname': "pmdltrafficvolumeps16", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumeps64", 'src_fieldname': "pmdltrafficvolumeps64", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumeps128", 'src_fieldname': "pmdltrafficvolumeps128", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumeps384", 'src_fieldname': "pmdltrafficvolumeps384", 'type': "number"},
                    {'fieldname': "pmultrafficvolumepscommon", 'src_fieldname': "pmultrafficvolumepscommon", 'type': "number"},
                    {'fieldname': "pmultrafficvolumeps8", 'src_fieldname': "pmultrafficvolumeps8", 'type': "number"},
                    {'fieldname': "pmultrafficvolumeps16", 'src_fieldname': "pmultrafficvolumeps16", 'type': "number"},
                    {'fieldname': "pmultrafficvolumeps64", 'src_fieldname': "pmultrafficvolumeps64", 'type': "number"},
                    {'fieldname': "pmultrafficvolumeps128", 'src_fieldname': "pmultrafficvolumeps128", 'type': "number"},
                    {'fieldname': "pmultrafficvolumeps384", 'src_fieldname': "pmultrafficvolumeps384", 'type': "number"},
                    {'fieldname': "pmdltrafficvolumepsinths", 'src_fieldname': "pmdltrafficvolumepsinths", 'type': "number"},
                    {'fieldname': "pmultrafficvolumepsinteul", 'src_fieldname': "pmultrafficvolumepsinteul", 'type': "number"},
                    {'fieldname': "pmnorabestablishsuccesscs57", 'src_fieldname': "pmnorabestablishsuccesscs57", 'type': "number"},
                    {'fieldname': "pmnorabestablishsuccesscs64", 'src_fieldname': "pmnorabestablishsuccesscs64", 'type': "number"},
                    {'fieldname': "pmnorabestablishattemptcs57", 'src_fieldname': "pmnorabestablishattemptcs57", 'type': "number"},
                    {'fieldname': "pmnorabestablishattemptcs64", 'src_fieldname': "pmnorabestablishattemptcs64", 'type': "number"},
                    {'fieldname': "pmnosystemrabreleaseamrnb", 'src_fieldname': "pmnosystemrabreleaseamrnb", 'type': "number"},
                    {'fieldname': "pmnosystemrabreleaseamrwb", 'src_fieldname': "pmnosystemrabreleaseamrwb", 'type': "number"},
                    {'fieldname': "pmnonormalrabreleaseamrnb", 'src_fieldname': "pmnonormalrabreleaseamrnb", 'type': "number"},
                    {'fieldname': "pmnonormalrabreleaseamrwb", 'src_fieldname': "pmnonormalrabreleaseamrwb", 'type': "number"},
                    {'fieldname': "pmnorabestablishsuccesspacketinteractive", 'src_fieldname': "pmnorabestablishsuccesspacketinteractive", 'type': "number"},
                    {'fieldname': "pmnorabestablishattemptpacketinteractive", 'src_fieldname': "pmnorabestablishattemptpacketinteractive", 'type': "number"},
                ]
            },
            "4": {
                'id': '4',
                'name': 'ericsson_4g',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'src_query': """
                select
                    "start_time", "erbs", "cell", "nombre_ebc", "enodeb", "tac", "banda", "sector", "eutrancell_id",
                    "pmrrcconnestabsucc", "pmrrcconnestabatt", "pmrrcconnestabattreatt", "pmrrcconnestabfailmmeovlmos",
                    "pmrrcconnestabfailmmeovlmod", "pms1sigconnestabsucc", "pms1sigconnestabatt", "pms1sigconnestabfailmmeovlmos",
                    "pmerabestabsuccinit", "pmerabestabattinit", "pmpdcpvoldldrb", "pmpdcpvoldldrblasttti", "pmuethptimedl",
                    "pmcelldowntimeauto", "pmcelldowntimeman", "pmpdcpvoluldrb", "pmprbutildl", "pmprbutilul", "pmprbavaildl",
                    "pmprbavailul", "pmuectxtrelcsfbwcdma", "pmuectxtrelnormalenb", "pmuectxtrelabnormalenb", "pmuectxtrelmme",
                    "pmrrcconnestabsuccmod", "pmrrcconnestabsuccmta", "pmrrcconnestabattmod", "pmrrcconnestabattmta",
                    "pmrrcconnestabattreattmod", "pmrrcconnestabattreattmta", "pms1sigconnestabsuccmod", "pms1sigconnestabsuccmta",
                    "pms1sigconnestabattmod", "pms1sigconnestabattmta", "cqi_distr", "cqi_distr_num", "cqi_distr_den",
                    "pmerabestabsuccinitqci1", "pmerabestabsuccinitqci5", "pmerabestabattinitqci1", "pmerabestabattinitqci5",
                    "pmerabestabsuccaddedqci1", "pmerabestabsuccaddedqci5", "pmerabestabattaddedqci1", "pmerabestabattaddedqci5",
                    "pmerabestabattaddedhoongoingqci1", "pmerabestabattaddedhoongoingqci5", "pmerabrelabnormalenbactqci1",
                    "pmerabrelabnormalenbactqci5", "pmerabrelabnormalmmeactqci1", "pmerabrelabnormalmmeactqci5",
                    "pmerabrelabnormalenbqci1", "pmerabrelabnormalenbqci5", "pmerabrelnormalenbqci1", "pmerabrelnormalenbqci5",
                    "pmerabrelmmeqci1", "pmerabrelmmeqci5", "pmhoprepsuccsrvcc", "pmhoprepattsrvcc", "pmpdcpvoldldrbqci1",
                    "pmpdcpvoldldrbqci5", "pmpdcpvoldldrblastttiqci1", "pmpdcpvoldldrblastttiqci5", "pmdrbthptimedlqci1",
                    "pmdrbthptimedlqci5", "pmrrcconnlevsum", "pmrrcconnlevsamp", "pmpdcpvoldldrbqci0", "pmpdcpvoldldrbqci2",
                    "pmpdcpvoldldrbqci3", "pmpdcpvoldldrbqci4", "pmpdcpvoldldrbqci6", "pmpdcpvoldldrbqci7", "pmpdcpvoldldrbqci8",
                    "pmpdcpvoldldrblastttiqci0", "pmpdcpvoldldrblastttiqci2", "pmpdcpvoldldrblastttiqci3",
                    "pmpdcpvoldldrblastttiqci4", "pmpdcpvoldldrblastttiqci6", "pmpdcpvoldldrblastttiqci7",
                    "pmpdcpvoldldrblastttiqci8", "pmdrbthptimedlqci0", "pmdrbthptimedlqci2", "pmdrbthptimedlqci3",
                    "pmdrbthptimedlqci4", "pmdrbthptimedlqci6", "pmdrbthptimedlqci7", "pmdrbthptimedlqci8"
                from CLARO.counter_ericsson_4g
                where %(fecha_ini)s <= "start_time" and "start_time" < %(fecha_fin)s
                """,
                "src_query_finder": """select start_time as fecha from CLARO.counter_ericsson_4g
                WHERE start_time > now() - interval '2' day group by start_time """,
                'file_pattern': 'ericsson_4g_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'chunk_limit': 1000,
                'tablename': "ipt_counter_ericsson_4g",
                'queue_id': "ipt.ericsson_4g",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_IPT_FILE_SUCCESS('ipt.ericsson_4g', '{file_date}');
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "start_time", 'src_fieldname': "start_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "erbs", 'src_fieldname': "erbs", 'type': "varchar2"},
                    {'fieldname': "cell", 'src_fieldname': "cell", 'type': "varchar2"},
                    {'fieldname': "nombre_ebc", 'src_fieldname': "nombre_ebc", 'type': "varchar2"},
                    {'fieldname': "enodeb", 'src_fieldname': "enodeb", 'type': "varchar2"},
                    {'fieldname': "tac", 'src_fieldname': "tac", 'type': "varchar2"},
                    {'fieldname': "banda", 'src_fieldname': "banda", 'type': "varchar2"},
                    {'fieldname': "sector", 'src_fieldname': "sector", 'type': "varchar2"},
                    {'fieldname': "eutrancell_id", 'src_fieldname': "eutrancell_id", 'type': "varchar2"},
                    {'fieldname': "pmrrcconnestabsucc", 'src_fieldname': "pmrrcconnestabsucc", 'type': "number"},
                    {'fieldname': "pmrrcconnestabatt", 'src_fieldname': "pmrrcconnestabatt", 'type': "number"},
                    {'fieldname': "pmrrcconnestabattreatt", 'src_fieldname': "pmrrcconnestabattreatt", 'type': "number"},
                    {'fieldname': "pmrrcconnestabfailmmeovlmos", 'src_fieldname': "pmrrcconnestabfailmmeovlmos", 'type': "number"},
                    {'fieldname': "pmrrcconnestabfailmmeovlmod", 'src_fieldname': "pmrrcconnestabfailmmeovlmod", 'type': "number"},
                    {'fieldname': "pms1sigconnestabsucc", 'src_fieldname': "pms1sigconnestabsucc", 'type': "number"},
                    {'fieldname': "pms1sigconnestabatt", 'src_fieldname': "pms1sigconnestabatt", 'type': "number"},
                    {'fieldname': "pms1sigconnestabfailmmeovlmos", 'src_fieldname': "pms1sigconnestabfailmmeovlmos", 'type': "number"},
                    {'fieldname': "pmerabestabsuccinit", 'src_fieldname': "pmerabestabsuccinit", 'type': "number"},
                    {'fieldname': "pmerabestabattinit", 'src_fieldname': "pmerabestabattinit", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrb", 'src_fieldname': "pmpdcpvoldldrb", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblasttti", 'src_fieldname': "pmpdcpvoldldrblasttti", 'type': "number"},
                    {'fieldname': "pmuethptimedl", 'src_fieldname': "pmuethptimedl", 'type': "number"},
                    {'fieldname': "pmcelldowntimeauto", 'src_fieldname': "pmcelldowntimeauto", 'type': "number"},
                    {'fieldname': "pmcelldowntimeman", 'src_fieldname': "pmcelldowntimeman", 'type': "number"},
                    {'fieldname': "pmpdcpvoluldrb", 'src_fieldname': "pmpdcpvoluldrb", 'type': "number"},
                    {'fieldname': "pmprbutildl", 'src_fieldname': "pmprbutildl", 'type': "number"},
                    {'fieldname': "pmprbutilul", 'src_fieldname': "pmprbutilul", 'type': "number"},
                    {'fieldname': "pmprbavaildl", 'src_fieldname': "pmprbavaildl", 'type': "number"},
                    {'fieldname': "pmprbavailul", 'src_fieldname': "pmprbavailul", 'type': "number"},
                    {'fieldname': "pmuectxtrelcsfbwcdma", 'src_fieldname': "pmuectxtrelcsfbwcdma", 'type': "number"},
                    {'fieldname': "pmuectxtrelnormalenb", 'src_fieldname': "pmuectxtrelnormalenb", 'type': "number"},
                    {'fieldname': "pmuectxtrelabnormalenb", 'src_fieldname': "pmuectxtrelabnormalenb", 'type': "number"},
                    {'fieldname': "pmuectxtrelmme", 'src_fieldname': "pmuectxtrelmme", 'type': "number"},
                    {'fieldname': "pmrrcconnestabsuccmod", 'src_fieldname': "pmrrcconnestabsuccmod", 'type': "number"},
                    {'fieldname': "pmrrcconnestabsuccmta", 'src_fieldname': "pmrrcconnestabsuccmta", 'type': "number"},
                    {'fieldname': "pmrrcconnestabattmod", 'src_fieldname': "pmrrcconnestabattmod", 'type': "number"},
                    {'fieldname': "pmrrcconnestabattmta", 'src_fieldname': "pmrrcconnestabattmta", 'type': "number"},
                    {'fieldname': "pmrrcconnestabattreattmod", 'src_fieldname': "pmrrcconnestabattreattmod", 'type': "number"},
                    {'fieldname': "pmrrcconnestabattreattmta", 'src_fieldname': "pmrrcconnestabattreattmta", 'type': "number"},
                    {'fieldname': "pms1sigconnestabsuccmod", 'src_fieldname': "pms1sigconnestabsuccmod", 'type': "number"},
                    {'fieldname': "pms1sigconnestabsuccmta", 'src_fieldname': "pms1sigconnestabsuccmta", 'type': "number"},
                    {'fieldname': "pms1sigconnestabattmod", 'src_fieldname': "pms1sigconnestabattmod", 'type': "number"},
                    {'fieldname': "pms1sigconnestabattmta", 'src_fieldname': "pms1sigconnestabattmta", 'type': "number"},
                    {'fieldname': "cqi_distr", 'src_fieldname': "cqi_distr", 'type': "number"},
                    {'fieldname': "cqi_distr_num", 'src_fieldname': "cqi_distr_num", 'type': "number"},
                    {'fieldname': "cqi_distr_den", 'src_fieldname': "cqi_distr_den", 'type': "number"},
                    {'fieldname': "pmerabestabsuccinitqci1", 'src_fieldname': "pmerabestabsuccinitqci1", 'type': "number"},
                    {'fieldname': "pmerabestabsuccinitqci5", 'src_fieldname': "pmerabestabsuccinitqci5", 'type': "number"},
                    {'fieldname': "pmerabestabattinitqci1", 'src_fieldname': "pmerabestabattinitqci1", 'type': "number"},
                    {'fieldname': "pmerabestabattinitqci5", 'src_fieldname': "pmerabestabattinitqci5", 'type': "number"},
                    {'fieldname': "pmerabestabsuccaddedqci1", 'src_fieldname': "pmerabestabsuccaddedqci1", 'type': "number"},
                    {'fieldname': "pmerabestabsuccaddedqci5", 'src_fieldname': "pmerabestabsuccaddedqci5", 'type': "number"},
                    {'fieldname': "pmerabestabattaddedqci1", 'src_fieldname': "pmerabestabattaddedqci1", 'type': "number"},
                    {'fieldname': "pmerabestabattaddedqci5", 'src_fieldname': "pmerabestabattaddedqci5", 'type': "number"},
                    {'fieldname': "pmerabestabattaddedhoongoingqci1", 'src_fieldname': "pmerabestabattaddedhoongoingqci1", 'type': "number"},
                    {'fieldname': "pmerabestabattaddedhoongoingqci5", 'src_fieldname': "pmerabestabattaddedhoongoingqci5", 'type': "number"},
                    {'fieldname': "pmerabrelabnormalenbactqci1", 'src_fieldname': "pmerabrelabnormalenbactqci1", 'type': "number"},
                    {'fieldname': "pmerabrelabnormalenbactqci5", 'src_fieldname': "pmerabrelabnormalenbactqci5", 'type': "number"},
                    {'fieldname': "pmerabrelabnormalmmeactqci1", 'src_fieldname': "pmerabrelabnormalmmeactqci1", 'type': "number"},
                    {'fieldname': "pmerabrelabnormalmmeactqci5", 'src_fieldname': "pmerabrelabnormalmmeactqci5", 'type': "number"},
                    {'fieldname': "pmerabrelabnormalenbqci1", 'src_fieldname': "pmerabrelabnormalenbqci1", 'type': "number"},
                    {'fieldname': "pmerabrelabnormalenbqci5", 'src_fieldname': "pmerabrelabnormalenbqci5", 'type': "number"},
                    {'fieldname': "pmerabrelnormalenbqci1", 'src_fieldname': "pmerabrelnormalenbqci1", 'type': "number"},
                    {'fieldname': "pmerabrelnormalenbqci5", 'src_fieldname': "pmerabrelnormalenbqci5", 'type': "number"},
                    {'fieldname': "pmerabrelmmeqci1", 'src_fieldname': "pmerabrelmmeqci1", 'type': "number"},
                    {'fieldname': "pmerabrelmmeqci5", 'src_fieldname': "pmerabrelmmeqci5", 'type': "number"},
                    {'fieldname': "pmhoprepsuccsrvcc", 'src_fieldname': "pmhoprepsuccsrvcc", 'type': "number"},
                    {'fieldname': "pmhoprepattsrvcc", 'src_fieldname': "pmhoprepattsrvcc", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci1", 'src_fieldname': "pmpdcpvoldldrbqci1", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci5", 'src_fieldname': "pmpdcpvoldldrbqci5", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci1", 'src_fieldname': "pmpdcpvoldldrblastttiqci1", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci5", 'src_fieldname': "pmpdcpvoldldrblastttiqci5", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci1", 'src_fieldname': "pmdrbthptimedlqci1", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci5", 'src_fieldname': "pmdrbthptimedlqci5", 'type': "number"},
                    {'fieldname': "pmrrcconnlevsum", 'src_fieldname': "pmrrcconnlevsum", 'type': "number"},
                    {'fieldname': "pmrrcconnlevsamp", 'src_fieldname': "pmrrcconnlevsamp", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci0", 'src_fieldname': "pmpdcpvoldldrbqci0", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci2", 'src_fieldname': "pmpdcpvoldldrbqci2", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci3", 'src_fieldname': "pmpdcpvoldldrbqci3", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci4", 'src_fieldname': "pmpdcpvoldldrbqci4", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci6", 'src_fieldname': "pmpdcpvoldldrbqci6", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci7", 'src_fieldname': "pmpdcpvoldldrbqci7", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrbqci8", 'src_fieldname': "pmpdcpvoldldrbqci8", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci0", 'src_fieldname': "pmpdcpvoldldrblastttiqci0", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci2", 'src_fieldname': "pmpdcpvoldldrblastttiqci2", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci3", 'src_fieldname': "pmpdcpvoldldrblastttiqci3", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci4", 'src_fieldname': "pmpdcpvoldldrblastttiqci4", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci6", 'src_fieldname': "pmpdcpvoldldrblastttiqci6", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci7", 'src_fieldname': "pmpdcpvoldldrblastttiqci7", 'type': "number"},
                    {'fieldname': "pmpdcpvoldldrblastttiqci8", 'src_fieldname': "pmpdcpvoldldrblastttiqci8", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci0", 'src_fieldname': "pmdrbthptimedlqci0", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci2", 'src_fieldname': "pmdrbthptimedlqci2", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci3", 'src_fieldname': "pmdrbthptimedlqci3", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci4", 'src_fieldname': "pmdrbthptimedlqci4", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci6", 'src_fieldname': "pmdrbthptimedlqci6", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci7", 'src_fieldname': "pmdrbthptimedlqci7", 'type': "number"},
                    {'fieldname': "pmdrbthptimedlqci8", 'src_fieldname': "pmdrbthptimedlqci8", 'type': "number"},
                ]
            },
            "5": {
                'id': '5',
                'name': 'alarms',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'src_query': """
                SELECT alarm_id,alarm_type_id,alarmed_object_id,alarmed_object_name,alarmed_object_type,alarm_raised_time,alarm_cleared_time,vendor_name,perceived_severity,event_type,specific_problem,regexp_replace(alarm_detail, '\r|\n', '', 'g') alarm_detail,source_system,latitude,longitude,site_name,local_cell_id,cell_name,id_ticket_remedy,alarm_load_time,probable_cause,leannoc_id,estado_celda,eutran,tecnologia,estacion,nodo,estado_sitio,ubigeo,centro_poblado,distrito,provincia,departamento,medio_tx,detalle_medio_tx,mno,portadora,id_controlador,logical_rnc_id,banda_operacion,tipo_de_transmision, 'alarms_'||to_char(%(fecha_ini)s, 'yyyy_mm_dd_hh24_mi')||'.csv' archivo FROM CLARO.alarms
                where %(fecha_fin)s is not null
                """,
                "src_query_finder": """select date_trunc('minute', now()) - (EXTRACT(MINUTE FROM now()) % 5) * interval '1 minute' AS fecha""",
                'file_pattern': 'alarms_([0-9]{12}).json',
                'file_date_format': '%Y%m%d%H%M',
                'chunk_limit': 1000,
                'tablename': "tmp_alarmas_ipt",
                'queue_id': "ipt.alarms",
                'status': 1,
                'reload_by': "file",
                # 'reload_validation': True,
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    delete from tmp_alarmas_ipt
                    where archivo != 'alarms_'||to_char(to_date('{file_date}', 'yyyy-mm-dd hh24:mi:ss'), 'yyyymmddhh24mi')||'.csv';
                    commit;
                    PK_ALARM_CARGA_IPT.SP_CARGA_ALARMAS_IPT;
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"minutes": 5}',
                'msg_send_granularity': True,
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    # {'fieldname': "start_time", 'src_fieldname': "start_time", 'type': "date", 'to_reload': 1, 'reload_argument': '{file_date}'},
                    {'fieldname': "alarm_id", 'src_fieldname': "alarm_id", 'type': "varchar2"},
                    {'fieldname': "alarm_type_id", 'src_fieldname': "alarm_type_id", 'type': "varchar2"},
                    {'fieldname': "alarmed_object_id", 'src_fieldname': "alarmed_object_id", 'type': "varchar2"},
                    {'fieldname': "alarmed_object_name", 'src_fieldname': "alarmed_object_name", 'type': "varchar2"},
                    {'fieldname': "alarmed_object_type", 'src_fieldname': "alarmed_object_type", 'type': "varchar2"},
                    {'fieldname': "alarm_raised_time", 'src_fieldname': "alarm_raised_time", 'type': "varchar2"},
                    {'fieldname': "alarm_cleared_time", 'src_fieldname': "alarm_cleared_time", 'type': "varchar2"},
                    {'fieldname': "vendor_name", 'src_fieldname': "vendor_name", 'type': "varchar2"},
                    {'fieldname': "perceived_severity", 'src_fieldname': "perceived_severity", 'type': "varchar2"},
                    {'fieldname': "event_type", 'src_fieldname': "event_type", 'type': "varchar2"},
                    {'fieldname': "specific_problem", 'src_fieldname': "specific_problem", 'type': "varchar2"},
                    {'fieldname': "alarm_detail", 'src_fieldname': "alarm_detail", 'type': "varchar2"},
                    {'fieldname': "source_system", 'src_fieldname': "source_system", 'type': "varchar2"},
                    {'fieldname': "latitude", 'src_fieldname': "latitude", 'type': "varchar2"},
                    {'fieldname': "longitude", 'src_fieldname': "longitude", 'type': "varchar2"},
                    {'fieldname': "site_name", 'src_fieldname': "site_name", 'type': "varchar2"},
                    {'fieldname': "local_cell_id", 'src_fieldname': "local_cell_id", 'type': "varchar2"},
                    {'fieldname': "cell_name", 'src_fieldname': "cell_name", 'type': "varchar2"},
                    {'fieldname': "id_ticket_remedy", 'src_fieldname': "id_ticket_remedy", 'type': "varchar2"},
                    {'fieldname': "alarm_load_time", 'src_fieldname': "alarm_load_time", 'type': "varchar2"},
                    {'fieldname': "probable_cause", 'src_fieldname': "probable_cause", 'type': "varchar2"},
                    {'fieldname': "leannoc_id", 'src_fieldname': "leannoc_id", 'type': "varchar2"},
                    {'fieldname': "estado_celda", 'src_fieldname': "estado_celda", 'type': "varchar2"},
                    {'fieldname': "eutran", 'src_fieldname': "eutran", 'type': "varchar2"},
                    {'fieldname': "tecnologia", 'src_fieldname': "tecnologia", 'type': "varchar2"},
                    {'fieldname': "estacion", 'src_fieldname': "estacion", 'type': "varchar2"},
                    {'fieldname': "nodo", 'src_fieldname': "nodo", 'type': "varchar2"},
                    {'fieldname': "estado_sitio", 'src_fieldname': "estado_sitio", 'type': "varchar2"},
                    {'fieldname': "ubigeo", 'src_fieldname': "ubigeo", 'type': "varchar2"},
                    {'fieldname': "centro_poblado", 'src_fieldname': "centro_poblado", 'type': "varchar2"},
                    {'fieldname': "distrito", 'src_fieldname': "distrito", 'type': "varchar2"},
                    {'fieldname': "provincia", 'src_fieldname': "provincia", 'type': "varchar2"},
                    {'fieldname': "departamento", 'src_fieldname': "departamento", 'type': "varchar2"},
                    {'fieldname': "medio_tx", 'src_fieldname': "medio_tx", 'type': "varchar2"},
                    {'fieldname': "detalle_medio_tx", 'src_fieldname': "detalle_medio_tx", 'type': "varchar2"},
                    {'fieldname': "mno", 'src_fieldname': "mno", 'type': "varchar2"},
                    {'fieldname': "portadora", 'src_fieldname': "portadora", 'type': "varchar2"},
                    {'fieldname': "id_controlador", 'src_fieldname': "id_controlador", 'type': "varchar2"},
                    {'fieldname': "logical_rnc_id", 'src_fieldname': "logical_rnc_id", 'type': "varchar2"},
                    {'fieldname': "banda_operacion", 'src_fieldname': "banda_operacion", 'type': "varchar2"},
                    {'fieldname': "tipo_de_transmision", 'src_fieldname': "tipo_de_transmision", 'type': "varchar2"},
                    {'fieldname': "archivo", 'src_fieldname': "archivo", 'type': "varchar2", 'reload_argument': '{filename}'},
                ]
            }
        }