import re

class NCEInventarioConfigRepository:
    def __init__(self, db):
        self.db = db
        # self.table = 'NCE_CONFIG'
        # self.fields = 'id, name, type, server_id, work_dir, file_pattern, file_date_format, limit_to_commit, tablename, queue_id, status, reload_by, exec_after_by, exec_after_st, files_permission, search_time_ago'
        # self.sub_table = 'NCE_CONFIG_FIELD'
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'Subcard_Report',
                'type': 'inventario',
                'server_id': 'nce',
                'work_dir': '/hfs_public/inventory_dm_report/inventoryReports',
                'file_pattern': 'Subcard_Report_(.{10}).*.csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "TX_INV_SUBCARD",
                'queue_id': "nce.subcard",
                'status': 1,
                'exec_after_by': "all",
                'exec_after_st': "UPDATE {tablename} SET TIME=TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS') WHERE ESTADO_SEG=1; COMMIT",
                'files_permission': "group",
                'search_time_ago': '{"days": 3}'
            },
            "2": {
                'id': '2',
                'name': 'Subrack_Report',
                'type': 'inventario',
                'server_id': 'nce',
                'work_dir': '/hfs_public/inventory_dm_report/inventoryReports',
                'file_pattern': 'Subrack_Report_(.{10}).*.csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "TX_INV_SUBRACK",
                'queue_id': "nce.subrack",
                'status': 1,
                'exec_after_by': "all",
                'exec_after_st': "UPDATE {tablename} SET TIME=TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS') WHERE ESTADO_SEG=1; COMMIT",
                'files_permission': "group",
                'search_time_ago': '{"days": 3}'
            },
            "3": {
                'id': '3',
                'name': 'Board_Report',
                'type': 'inventario',
                'server_id': 'nce',
                'work_dir': '/hfs_public/inventory_dm_report/inventoryReports',
                'file_pattern': 'Board_Report_(.{10}).*.csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "TX_INV_BOARD_REPORT",
                'queue_id': "nce.board_report",
                'status': 1,
                'exec_after_by': "all",
                'exec_after_st': "UPDATE {tablename} SET TIME=TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS') WHERE ESTADO_SEG=1; COMMIT",
                'files_permission': "group",
                'search_time_ago': '{"days": 3}'
            },
            "4": {
                'id': '4',
                'name': 'NE_Report',
                'type': 'inventario',
                'server_id': 'nce',
                'work_dir': '/hfs_public/inventory_dm_report/inventoryReports',
                'file_pattern': 'NE_Report_(.{10}).*.csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "TX_INV_NE_REPORT",
                'queue_id': "nce.ne_report",
                'status': 1,
                'exec_after_by': "all",
                'exec_after_st': "UPDATE {tablename} SET TIME=TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS') WHERE ESTADO_SEG=1; COMMIT",
                'files_permission': "group",
                'search_time_ago': '{"days": 3}'
            },
            "5": {
                'id': '5',
                'name': 'OpticalModule_Information',
                'type': 'inventario',
                'server_id': 'nce',
                'work_dir': '/hfs_public/inventory_dm_report/inventoryReports',
                'file_pattern': 'OpticalModule_Information_(.{10}).*.csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "TX_INV_OPTICAL_MODULE",
                'queue_id': "nce.optical_module",
                'status': 1,
                'exec_after_by': "all",
                'exec_after_st': "UPDATE {tablename} SET TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS') WHERE ESTADO_SEG=1; COMMIT",
                'files_permission': "group",
                'search_time_ago': '{"days": 3}'
            },
            "6": {
                'id': '6',
                'name': 'Port_Report',
                'type': 'inventario',
                'server_id': 'nce',
                'work_dir': '/hfs_public/inventory_dm_report/inventoryReports',
                'file_pattern': 'Port_Report_(.{10}).*.csv',
                'file_date_format': '%Y-%m-%d',
                'limit_to_commit': 5000,
                'tablename': "TX_INV_PORT_REPORT",
                'queue_id': "nce.port_report",
                'status': 1,
                'exec_after_by': "all",
                'exec_after_st': "UPDATE {tablename} SET TIME=TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS') WHERE ESTADO_SEG=1; COMMIT",
                'files_permission': "group",
                'search_time_ago': '{"days": 3}'
            }
        }
        self.config_fields_by_id = {
            "1": [
                {'fieldname': "NE",'src_fieldname': "1", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBBOARD_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBBOARD_TYPE", 'src_fieldname': "3", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBRACK_ID", 'src_fieldname': "4", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SLOT_NUMBER", 'src_fieldname': "5", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBSLOT_NUMBER", 'src_fieldname': "6", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBBOARD_STATUS", 'src_fieldname': "7", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "HARDWARE_VERSION", 'src_fieldname': "8", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SOFTWARE_VERSION", 'src_fieldname': "9", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SN_BAR_CODE", 'src_fieldname': "10", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "ALIAS", 'src_fieldname': "11", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBBOARD_DESCRIPTION", 'src_fieldname': "12", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REMARKS", 'src_fieldname': "13", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CUSTOMIZED_COLUMN", 'src_fieldname': "14", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PN_BOM_CODE_ITEM", 'src_fieldname': "15", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBBOARD_MANUFACTURE_DATE", 'src_fieldname': "16", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MODEL", 'src_fieldname': "17", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REV_ISSUE_NUMBER", 'src_fieldname': "18", 'type': "varchar2", 'is_unique': None},
            ],
            "2": [
                {'fieldname': "NE", 'src_fieldname': "1", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBRACK_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBRACK_TYPE", 'src_fieldname': "3", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBRACK_ID", 'src_fieldname': "4", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SOFTWARE_VERSION", 'src_fieldname': "5", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "NE_ID", 'src_fieldname': "6", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "ALIAS", 'src_fieldname': "7", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBRACK_STATUS", 'src_fieldname': "8", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SN_BAR_CODE", 'src_fieldname': "9", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "TELECOMMUNICATIONS_ROOM", 'src_fieldname': "10", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "RACK", 'src_fieldname': "11", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBRACK_NO", 'src_fieldname': "12", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PN_BOM_CODE_ITEM", 'src_fieldname': "13", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "DESCRIPTION", 'src_fieldname': "14", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MANUFACTURE_DATE", 'src_fieldname': "15", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBNET", 'src_fieldname': "16", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBNET_PATH", 'src_fieldname': "17", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "EQUIPMENT_NO", 'src_fieldname': "18", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REMARKS", 'src_fieldname': "19", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CUSTOMIZED_COLUMN", 'src_fieldname': "20", 'type': "varchar2", 'is_unique': None},
            ],
            "3": [
                {'fieldname': "NE", 'src_fieldname': "1", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "BOARD_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "BOARD_TYPE", 'src_fieldname': "3", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "NE_TYPE", 'src_fieldname': "4", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBRACK_ID", 'src_fieldname': "5", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SLOT_ID", 'src_fieldname': "6", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "HARDWARE_VERSION", 'src_fieldname': "7", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SOFTWARE_VERSION", 'src_fieldname': "8", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SN_BAR_CODE", 'src_fieldname': "9", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "ALIAS", 'src_fieldname': "10", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REMARKS", 'src_fieldname': "11", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CUSTOMIZED_COLUMN", 'src_fieldname': "12", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBRACK_TYPE", 'src_fieldname': "13", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "NE_ID", 'src_fieldname': "14", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "BIOS_VERSION", 'src_fieldname': "15", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "FPGA_VERSION", 'src_fieldname': "16", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "BOARD_STATUS", 'src_fieldname': "17", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PN_BOM_CODE_ITEM", 'src_fieldname': "18", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MODEL", 'src_fieldname': "19", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REV_ISSUE_NUMBER", 'src_fieldname': "20", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MANAGEMENT", 'src_fieldname': "21", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "DESCRIPTION", 'src_fieldname': "22", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MANUFACTURE_DATE", 'src_fieldname': "23", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CREATE_TIME", 'src_fieldname': "24", 'type': "varchar2", 'is_unique': None},
            ],
            "4": [
                {'fieldname': "NE_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "NE_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "NE_IP_ADDRESS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "NE_MAC_ADDRESS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "NE_ID", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SOFTWARE_VERSION", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PHYSICAL_LOCATION", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CREATE_TIME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "FIBER_CABLE_COUNT", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "RUNNING_STATUS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBNET", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBNET_PATH", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "ALIAS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REMARKS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PATCH_VERSION_LIST", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CUSTOMIZED_COLUMN", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "LSR_ID", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MAINTENANCE_STATUS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "GATEWAY_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "GATEWAY", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "OPTICAL_NE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SUBRACK_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CONFERENCE_CALL", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "ORDERWIRE_PHONE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "NE_SUBTYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
            ],
            "5": [
                {'fieldname': "SERIAL_NO", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "OPTICAL_ELECTRICAL_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "NE_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "PORT_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "PORT_DESCRIPTION", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PORT_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "RECEIVE_OPTICAL_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REFERENCE_RECEIVE_OPTICAL_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REFERENCE_RECEIVE_TIME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "RECEIVE_STATUS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "UPPER_THRESHOLD_RECEIVE_OPT_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "LOW_THRESHOLD_RECEIVE_OPT_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "TRANSMIT_OPTICAL_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REFERENCE_TRANSMIT_OPTICAL_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REFERENCE_TRANSMIT_TIME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "TRANSMIT_STATUS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "UPPER_THRESHOLD_TRANSMIT_OPT_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "LOW_THRESHOLD_TRANSMIT_OPT_POWER_DBM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SINGLEMODE_MULTIMODE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "SPEED_MB_S", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "WAVE_LENGTH_NM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "TRANSMISSION_DISTANCE_M", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "FIBER_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "P_MANUFACTURER", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "OPTICAL_MODE_AUTHENTICATION", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PORT_REMARK", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PORT_CUSTOM_COLUMN", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "OPTICAL_DIRECTION_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "VENDOR_PN", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "MODEL", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REV_ISSUE_NUMBER", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PN_BOM_CODE_ITEM", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None}
            ],
            "6": [
                {'fieldname': "NE_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "NE_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SHELF_NO", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SLOT_NO", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "SUBSLOT_NO", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "PORT_NO", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "PORT_NAME", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "PORT_TYPE", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PORT_RATE_KBIT_S", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "PORT_LEVEL", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': 1},
                {'fieldname': "MANAGEMENT", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "ALIAS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "REMARKS", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None},
                {'fieldname': "CUSTOMIZED_COLUMN", 'src_fieldname': "2", 'type': "varchar2", 'is_unique': None}
            ]
        }

    def get(self):
        result = []
        for id in list(self.config_by_id):
            result.append(self.config_by_id[id])
        return result

    def get_by_group_id(self, group_id):
        return self.get()

    def find(self, id):
        if id in self.config_by_id.keys():
            return self.config_by_id[id]
        return None
    
    def get_fields_by_id(self, config_id):
        if config_id in self.config_fields_by_id.keys():
            return self.config_fields_by_id[config_id]
        return []
