from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryGMyDConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'gmyd_kpi_mw',
                'type': 'stats',
                # 'server_id': 'pronatel03',
                'work_dir': '/kpis/lista/mw/todos/todo?region=&area=&categ=&tipo=&prior=&stock=&accion=',
                'file_pattern': 'gmyd_kpi_mw_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_kpi_mw",
                'queue_id': "gmyd.kpi_mw",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                # 'files_permission': "group",
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "ESTADO", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "ESTADO", 'src_fieldname': "ESTADO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ENLACE", 'src_fieldname': "ENLACE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CODIGO_ORIGEN", 'src_fieldname': "CODIGO_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "NOMBRE_ORIGEN", 'src_fieldname': "NOMBRE_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "REGION_ORIGEN", 'src_fieldname': "REGION_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CODIGO_DESTINO", 'src_fieldname': "CODIGO_DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "NOMBRE_DESTINO", 'src_fieldname': "NOMBRE_DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "TIPO", 'src_fieldname': "TIPO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ID", 'src_fieldname': "ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "IDSITEA", 'src_fieldname': "IDSITEA", 'type': "number", 'to_reload': None},
                    {'fieldname': "IDSITEB", 'src_fieldname': "IDSITEB", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ESTADO", 'src_fieldname': "ID_ESTADO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_TIPO", 'src_fieldname': "ID_TIPO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_CATEGORIA", 'src_fieldname': "ID_CATEGORIA", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_AREA_RESP", 'src_fieldname': "ID_AREA_RESP", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ACCIONES", 'src_fieldname': "ID_ACCIONES", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_DETALLE_ACCION", 'src_fieldname': "ID_DETALLE_ACCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_STOCK_EQUIPO", 'src_fieldname': "ID_STOCK_EQUIPO", 'type': "number", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_REGISTRO", 'src_fieldname': "CAPACIDAD_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_REGISTRO", 'src_fieldname': "PORC_OCUP_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_SOLUCION", 'src_fieldname': "CAPACIDAD_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "PRIORIDAD", 'src_fieldname': "PRIORIDAD", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MODO_PRIORIDAD", 'src_fieldname': "MODO_PRIORIDAD", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_SOLUCION", 'src_fieldname': "PORC_OCUP_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "FECHA_INGRESO", 'src_fieldname': "FECHA_INGRESO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_FORECAST", 'src_fieldname': "FECHA_FORECAST", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_SOLUCION", 'src_fieldname': "FECHA_SOLUCION", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_CAMBIO", 'src_fieldname': "FECHA_CAMBIO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "RESP_INGRESO", 'src_fieldname': "RESP_INGRESO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESP_CAMBIO", 'src_fieldname': "RESP_CAMBIO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PAP", 'src_fieldname': "PAP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESOURCENAME", 'src_fieldname': "RESOURCENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ACT_OCUP", 'src_fieldname': "ACT_OCUP", 'type': "number", 'to_reload': None},
                    {'fieldname': "CATEGORIA", 'src_fieldname': "CATEGORIA", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "AREA_RESP", 'src_fieldname': "AREA_RESP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SIGLAS", 'src_fieldname': "SIGLAS", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ACCION", 'src_fieldname': "ACCION", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DETALLE", 'src_fieldname': "DETALLE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "VALOR", 'src_fieldname': "VALOR", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SITE_PKLOSS", 'src_fieldname': "SITE_PKLOSS", 'type': "number", 'to_reload': None},
                    {'fieldname': "SITE_DELAY", 'src_fieldname': "SITE_DELAY", 'type': "number", 'to_reload': None},
                    {'fieldname': "SITES", 'src_fieldname': "SITE_DELAY", 'type': "number", 'to_reload': None},
                ]
            },
            "2": {
                'id': '2',
                'name': 'huawei_trafico_core_semana',
                'type': 'stats',
                'work_dir': '/huawei/stats/interfaces/photo?capaRed=core&estadoOcupacion=todo&tipoPuerto=todo&reporte=semana&search=',
                'file_pattern': 'huawei_trafico_core_semana_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_huawei_trafico_core_semana",
                'queue_id': "gmyd.huawei_trafico_core_semana",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "DEVICENAME", 'src_fieldname': "DEVICENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESOURCENAME", 'src_fieldname': "RESOURCENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MAX_BW_UTIL", 'src_fieldname': "MAX_BW_UTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "P95_BW_UTIL", 'src_fieldname': "P95_BW_UTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "INTERFACE_DESCRIPTION", 'src_fieldname': "INTERFACE_DESCRIPTION", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "INTERFACE_SPEED", 'src_fieldname': "INTERFACE_SPEED", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESDE", 'src_fieldname': "DESDE", 'type': "date", 'map_with': "{value+' 00:00:00'}", 'to_reload': 1},
                    {'fieldname': "HASTA", 'src_fieldname': "HASTA", 'type': "date", 'to_reload': None},
                ]
            },
            "3": {
                'id': '3',
                'name': 'huawei_trafico_core_dia',
                'type': 'stats',
                'work_dir': '/huawei/stats/interfaces/photo?capaRed=core&estadoOcupacion=todo&tipoPuerto=todo&reporte=dia&search=',
                'file_pattern': 'huawei_trafico_core_dia_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "gmyd_huawei_trafico_core_dia",
                'queue_id': "gmyd.huawei_trafico_core_dia",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "DEVICENAME", 'src_fieldname': "DEVICENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESOURCENAME", 'src_fieldname': "RESOURCENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MAX_BW_UTIL", 'src_fieldname': "MAX_BW_UTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "P95_BW_UTIL", 'src_fieldname': "P95_BW_UTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "INTERFACE_DESCRIPTION", 'src_fieldname': "INTERFACE_DESCRIPTION", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "INTERFACE_SPEED", 'src_fieldname': "INTERFACE_SPEED", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "FECHA", 'src_fieldname': "FECHA", 'type': "date", 'map_with': "{value+' 00:00:00'}", 'to_reload': 1},
                ]
            },
            "4": {
                'id': '4',
                'name': 'ipran_trafico_no_rcsr_semana',
                'type': 'stats',
                'work_dir': '/sam/stats/interfaces/semana/No_rCSR/todo/todo',
                'file_pattern': 'ipran_trafico_no_rcsr_semana_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_ipran_trafico_no_rcsr_semana",
                'queue_id': "gmyd.ipran_trafico_no_rcsr_semana",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "NAMECOMPLETE", 'src_fieldname': "NAMECOMPLETE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DEVICENAME", 'src_fieldname': "DEVICENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PORT", 'src_fieldname': "PORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESCRIPTIONPORT", 'src_fieldname': "DESCRIPTIONPORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CAPACITY", 'src_fieldname': "CAPACITY", 'type': "number", 'to_reload': None},
                    {'fieldname': "MAXIMO", 'src_fieldname': "MAXIMO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PERCENTIL", 'src_fieldname': "PERCENTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "DESDE", 'src_fieldname': "DESDE", 'type': "date", 'map_with': "{value+' 00:00:00'}", 'to_reload': 1},
                    {'fieldname': "HASTA", 'src_fieldname': "HASTA", 'type': "date", 'to_reload': None}
                ]
            },
            "5": {
                'id': '5',
                'name': 'ipran_trafico_no_rcsr_dia',
                'type': 'stats',
                'work_dir': '/sam/stats/interfaces/dia/No_rCSR/todo/todo',
                'file_pattern': 'ipran_trafico_no_rcsr_dia_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_ipran_trafico_no_rcsr_dia",
                'queue_id': "gmyd.ipran_trafico_no_rcsr_dia",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "NAMECOMPLETE", 'src_fieldname': "NAMECOMPLETE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DEVICENAME", 'src_fieldname': "DEVICENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PORT", 'src_fieldname': "PORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESCRIPTIONPORT", 'src_fieldname': "DESCRIPTIONPORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CAPACITY", 'src_fieldname': "CAPACITY", 'type': "number", 'to_reload': None},
                    {'fieldname': "MAXIMO", 'src_fieldname': "MAXIMO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PERCENTIL", 'src_fieldname': "PERCENTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "FECHA", 'src_fieldname': "FECHA", 'type': "date", 'map_with': "{value+' 00:00:00'}", 'to_reload': 1},
                ]
            },
            "6": {
                'id': '6',
                'name': 'ipran_trafico_rcsr_semana',
                'type': 'stats',
                'work_dir': '/sam/stats/interfaces/semana/rCSR/todo/todo',
                'file_pattern': 'ipran_trafico_rcsr_semana_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_ipran_trafico_rcsr_semana",
                'queue_id': "gmyd.ipran_trafico_rcsr_semana",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "NAMECOMPLETE", 'src_fieldname': "NAMECOMPLETE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DEVICENAME", 'src_fieldname': "DEVICENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PORT", 'src_fieldname': "PORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESCRIPTIONPORT", 'src_fieldname': "DESCRIPTIONPORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CAPACITY", 'src_fieldname': "CAPACITY", 'type': "number", 'to_reload': None},
                    {'fieldname': "MAXIMO", 'src_fieldname': "MAXIMO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PERCENTIL", 'src_fieldname': "PERCENTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "DESDE", 'src_fieldname': "DESDE", 'type': "date", 'map_with': "{value+' 00:00:00'}", 'to_reload': 1},
                    {'fieldname': "HASTA", 'src_fieldname': "HASTA", 'type': "date", 'to_reload': None}
                ]
            },
            "7": {
                'id': '7',
                'name': 'ipran_trafico_rcsr_dia',
                'type': 'stats',
                'work_dir': '/sam/stats/interfaces/dia/rCSR/todo/todo',
                'file_pattern': 'ipran_trafico_rcsr_dia_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_ipran_trafico_rcsr_dia",
                'queue_id': "gmyd.ipran_trafico_rcsr_dia",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "NAMECOMPLETE", 'src_fieldname': "NAMECOMPLETE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DEVICENAME", 'src_fieldname': "DEVICENAME", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PORT", 'src_fieldname': "PORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESCRIPTIONPORT", 'src_fieldname': "DESCRIPTIONPORT", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CAPACITY", 'src_fieldname': "CAPACITY", 'type': "number", 'to_reload': None},
                    {'fieldname': "MAXIMO", 'src_fieldname': "MAXIMO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PERCENTIL", 'src_fieldname': "PERCENTIL", 'type': "number", 'to_reload': None},
                    {'fieldname': "FECHA", 'src_fieldname': "FECHA", 'type': "date", 'map_with': "{value+' 00:00:00'}", 'to_reload': 1}
                ]
            },
            "8": {
                'id': '8',
                'name': 'gmyd_kpi_rcsr',
                'type': 'stats',
                'work_dir': '/kpis/lista/rcsr/todos/todo?region=&area=&categ=&provedor=&prior=&stock=&accion=',
                'file_pattern': 'gmyd_kpi_rcsr_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_kpi_rcsr",
                'queue_id': "gmyd.kpi_rcsr",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "ESTADO", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "ESTADO", 'src_fieldname': "ESTADO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CODIGO", 'src_fieldname': "CODIGO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "NOMBRE", 'src_fieldname': "NOMBRE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "REGION", 'src_fieldname': "REGION", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PROVEDOR", 'src_fieldname': "PROVEDOR", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ID", 'src_fieldname': "ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "ORIGEN", 'src_fieldname': "ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESTINO", 'src_fieldname': "DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ID_SITE_ORIGEN", 'src_fieldname': "ID_SITE_ORIGEN", 'type': "number", 'to_reload': None},
                    {'fieldname': "PUERTO", 'src_fieldname': "PUERTO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_REGISTRO", 'src_fieldname': "CAPACIDAD_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_REGISTRO", 'src_fieldname': "PORC_OCUP_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_SOLUCION", 'src_fieldname': "CAPACIDAD_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_SOLUCION", 'src_fieldname': "PORC_OCUP_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ESTADO", 'src_fieldname': "ID_ESTADO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_TIPO_EQUIPO", 'src_fieldname': "ID_TIPO_EQUIPO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_CATEGORIA", 'src_fieldname': "ID_CATEGORIA", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_PROVEEDOR", 'src_fieldname': "ID_PROVEEDOR", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ACCIONES", 'src_fieldname': "ID_ACCIONES", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_AREA_RESP", 'src_fieldname': "ID_AREA_RESP", 'type': "number", 'to_reload': None},
                    {'fieldname': "FECHA_CAMBIO", 'src_fieldname': "FECHA_CAMBIO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_SOLUCION", 'src_fieldname': "FECHA_SOLUCION", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_FORECAST", 'src_fieldname': "FECHA_FORECAST", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_INGRESO", 'src_fieldname': "FECHA_INGRESO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "RESP_INGRESO", 'src_fieldname': "RESP_INGRESO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESP_CAMBIO", 'src_fieldname': "RESP_CAMBIO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PRIORIDAD", 'src_fieldname': "PRIORIDAD", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "MODO_PRIORIDAD", 'src_fieldname': "MODO_PRIORIDAD", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ID_DETALLE_ACCION", 'src_fieldname': "ID_DETALLE_ACCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_STOCK_EQUIPO", 'src_fieldname': "ID_STOCK_EQUIPO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PAP", 'src_fieldname': "PAP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CATEGORIA", 'src_fieldname': "CATEGORIA", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "AREA_RESP", 'src_fieldname': "AREA_RESP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SIGLAS", 'src_fieldname': "SIGLAS", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ACCION", 'src_fieldname': "ACCION", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DETALLE", 'src_fieldname': "DETALLE", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "VALOR", 'src_fieldname': "VALOR", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SITE_PKLOSS", 'src_fieldname': "SITE_PKLOSS", 'type': "number", 'to_reload': None},
                    {'fieldname': "SITE_DELAY", 'src_fieldname': "SITE_DELAY", 'type': "number", 'to_reload': None},
                    {'fieldname': "SITES", 'src_fieldname': "SITES", 'type': "number", 'to_reload': None},
                ]
            },
            "9": {
                'id': '9',
                'name': 'gmyd_kpi_core',
                'type': 'stats',
                'work_dir': '/kpis/lista/core/todos/todo?region=&area=&categ=&tipo=',
                'file_pattern': 'gmyd_kpi_core_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_kpi_core",
                'queue_id': "gmyd.kpi_core",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "ID", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "ID", 'src_fieldname': "ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "ORIGEN", 'src_fieldname': "ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESTINO", 'src_fieldname': "DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ID_SITE_ORIGEN", 'src_fieldname': "ID_SITE_ORIGEN", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_SITE_DESTINO", 'src_fieldname': "ID_SITE_DESTINO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PUERTO", 'src_fieldname': "PUERTO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_REGISTRO", 'src_fieldname': "CAPACIDAD_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_REGISTRO", 'src_fieldname': "PORC_OCUP_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_SOLUCION", 'src_fieldname': "CAPACIDAD_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_SOLUCION", 'src_fieldname': "PORC_OCUP_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ESTADO", 'src_fieldname': "ID_ESTADO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_TIPO_EQUIPO", 'src_fieldname': "ID_TIPO_EQUIPO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_CATEGORIA", 'src_fieldname': "ID_CATEGORIA", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ACCION", 'src_fieldname': "ID_ACCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_DETALLE_ACCION", 'src_fieldname': "ID_DETALLE_ACCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_AREA_RESP", 'src_fieldname': "ID_AREA_RESP", 'type': "number", 'to_reload': None},
                    {'fieldname': "FECHA_CAMBIO", 'src_fieldname': "FECHA_CAMBIO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_SOLUCION", 'src_fieldname': "FECHA_SOLUCION", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_FORECAST", 'src_fieldname': "FECHA_FORECAST", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_INGRESO", 'src_fieldname': "FECHA_INGRESO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "RESP_INGRESO", 'src_fieldname': "RESP_INGRESO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESP_CAMBIO", 'src_fieldname': "RESP_CAMBIO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PAP", 'src_fieldname': "PAP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ESTADO", 'src_fieldname': "ESTADO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CODIGO_ORIGEN", 'src_fieldname': "CODIGO_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "NOMBRE_ORIGEN", 'src_fieldname': "NOMBRE_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "REGION_ORIGEN", 'src_fieldname': "REGION_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CODIGO_DESTINO", 'src_fieldname': "CODIGO_DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "NOMBRE_DESTINO", 'src_fieldname': "NOMBRE_DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "REGION_DESTINO", 'src_fieldname': "REGION_DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "TIPO", 'src_fieldname': "TIPO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DIAS", 'src_fieldname': "DIAS", 'type': "number", 'to_reload': None},
                    {'fieldname': "CATEGORIA", 'src_fieldname': "CATEGORIA", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "AREA_RESP", 'src_fieldname': "AREA_RESP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "SIGLAS", 'src_fieldname': "SIGLAS", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ACCION", 'src_fieldname': "ACCION", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "10": {
                'id': '10',
                'name': 'gmyd_kpi_acifabric',
                'type': 'stats',
                'work_dir': '/kpis/lista/acifabric/todos/todo?region=&area=&categ=',
                'file_pattern': 'gmyd_kpi_acifabric_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "gmyd_kpi_acifabric",
                'queue_id': "gmyd.kpi_acifabric",
                'status': 1,
                'reload_by': "all",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 15}',
                'loop_time': '{"days": 7}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "ID", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "ID", 'src_fieldname': "ID", 'type': "number", 'to_reload': None},
                    {'fieldname': "ORIGEN", 'src_fieldname': "ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "PUERTO", 'src_fieldname': "PUERTO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DESTINO", 'src_fieldname': "DESTINO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ID_SITE_ORIGEN", 'src_fieldname': "ID_SITE_ORIGEN", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ESTADO", 'src_fieldname': "ID_ESTADO", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_CATEGORIA", 'src_fieldname': "ID_CATEGORIA", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_AREA_RESP", 'src_fieldname': "ID_AREA_RESP", 'type': "number", 'to_reload': None},
                    {'fieldname': "ID_ACCION", 'src_fieldname': "ID_ACCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_REGISTRO", 'src_fieldname': "CAPACIDAD_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_REGISTRO", 'src_fieldname': "PORC_OCUP_REGISTRO", 'type': "number", 'to_reload': None},
                    {'fieldname': "CAPACIDAD_SOLUCION", 'src_fieldname': "CAPACIDAD_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "PORC_OCUP_SOLUCION", 'src_fieldname': "PORC_OCUP_SOLUCION", 'type': "number", 'to_reload': None},
                    {'fieldname': "FECHA_INGRESO", 'src_fieldname': "FECHA_INGRESO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_FORECAST", 'src_fieldname': "FECHA_FORECAST", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_SOLUCION", 'src_fieldname': "FECHA_SOLUCION", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "FECHA_CAMBIO", 'src_fieldname': "FECHA_CAMBIO", 'type': "date", 'map_with': "{'' if value is None else dt.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "RESP_INGRESO", 'src_fieldname': "RESP_INGRESO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "RESP_CAMBIO", 'src_fieldname': "RESP_CAMBIO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "INSTANCIA", 'src_fieldname': "INSTANCIA", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ESTADO", 'src_fieldname': "ESTADO", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CODIGO_ORIGEN", 'src_fieldname': "CODIGO_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "NOMBRE_ORIGEN", 'src_fieldname': "NOMBRE_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "REGION_ORIGEN", 'src_fieldname': "REGION_ORIGEN", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "CATEGORIA", 'src_fieldname': "CATEGORIA", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "AREA_RESP", 'src_fieldname': "AREA_RESP", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ACCION", 'src_fieldname': "ACCION", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "DIAS", 'src_fieldname': "DIAS", 'type': "number", 'to_reload': None},
                ]
            }
        }