from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryGdeConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'gde_alarm',
                'type': 'stats',
                'server_id': None,
                'work_dir': "",
                'api_query': "adc-intg/api/rest/v1/Alarm_WS/Alarm_WS/alarm_ws_integration/alarm/alarm_get",
                'file_pattern': 'gde_alarm_([0-9]{12}).json',
                'file_date_format': '%Y%m%d%H%M',
                'chunk_limit': 5000,
                'limit_to_commit': 5000,
                'skip_lines': 0,
                'tablename': "gde_alarm",
                'queue_id': "gde.alarm",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"minutes": 15}',
                'msg_send_granularity': True,
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'alarms',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "summary", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "summary", 'src_fieldname': "summary", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "standardalarmseverity", 'src_fieldname': "standardalarmseverity", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sitedownflag", 'src_fieldname': "sitedownflag", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sitedownfault", 'src_fieldname': "sitedownfault", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "severity", 'src_fieldname': "severity", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentnode", 'src_fieldname': "parentnode", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "node", 'src_fieldname': "node", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "netype", 'src_fieldname': "netype", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "moname", 'src_fieldname': "moname", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ticketid", 'src_fieldname': "ticketid", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location", 'src_fieldname': "location", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "remedy_id", 'src_fieldname': "remedy_id", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "lastoccurrence", 'src_fieldname': "lastoccurrence", 'type': "date", 'to_reload': None},
                    {'fieldname': "identifier", 'src_fieldname': "identifier", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "firstoccurrence", 'src_fieldname': "firstoccurrence", 'type': "date", 'to_reload': None},
                    {'fieldname': "emstype", 'src_fieldname': "emstype", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "emsname", 'src_fieldname': "emsname", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "domain", 'src_fieldname': "domain", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "devicetype", 'src_fieldname': "devicetype", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "devicename", 'src_fieldname': "devicename", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "deviceid", 'src_fieldname': "deviceid", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "continuance", 'src_fieldname': "continuance", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cleartime", 'src_fieldname': "cleartime", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clearalarmlastreceivetime", 'src_fieldname': "clearalarmlastreceivetime", 'type': "date", 'to_reload': None},
                    {'fieldname': "clearalarmfirstreceivetime", 'src_fieldname': "clearalarmfirstreceivetime", 'type': "date", 'to_reload': None},
                    {'fieldname': "alertkey", 'src_fieldname': "alertkey", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alertgroup", 'src_fieldname': "alertgroup", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmserialnumber", 'src_fieldname': "alarmserialnumber", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmname", 'src_fieldname': "alarmname", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmid", 'src_fieldname': "alarmid", 'type': "varchar2", 'to_reload': None},
                ]
            }
        }