from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryCdrConfigRepository(InMemoryConfigRepository):
    def __init__(self):
        self.config_by_group = {
            'oplist': {
                'id': '1',
                'name': 'oplist',
                # 'type': 'alarm',
                'server_id': 'cdr',
                'work_dir': "/share/0/bdi_sftp/fail/dbErr/oplist",
                'file_pattern': 'oplist(.{13})_[0-9]+.txt',
                'file_date_format': '%Y%m%d_%H%M',
                'file_delimiter': '|',
                'skip_lines': 0,
                'chunk_limit': 1000,
                'tablename': "aicc_cdrs_oplist",
                'queue_id': "cdr.oplist",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_CDR_FILE_SUCCESS('{filename}', '{server_ip}');
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                "msg_send_granularity": True,
                'm_group': 'cdr',
                'fields': [
                    {'fieldname': "cc_id", 'src_fieldname': "0", 'type': "varchar2"},
                    {'fieldname': "vdn_id", 'src_fieldname': "1", 'type': "varchar2"},
                    {'fieldname': "agent_id", 'src_fieldname': "2", 'type': "varchar2"},
                    {'fieldname': "service_no", 'src_fieldname': "3", 'type': "varchar2"},
                    {'fieldname': "skill_id", 'src_fieldname': "4", 'type': "varchar2"},
                    {'fieldname': "call_id", 'src_fieldname': "5", 'type': "varchar2"},
                    {'fieldname': "begin_time", 'src_fieldname': "6", 'type': "date"},
                    {'fieldname': "end_time", 'src_fieldname': "7", 'type': "date"},
                    {'fieldname': "op_type", 'src_fieldname': "8", 'type': "varchar2"},
                    {'fieldname': "op_object", 'src_fieldname': "9", 'type': "varchar2"},
                    {'fieldname': "op_cause", 'src_fieldname': "10", 'type': "varchar2"},
                    {'fieldname': "media_type", 'src_fieldname': "11", 'type': "varchar2"},
                    {'fieldname': "agent_type", 'src_fieldname': "12", 'type': "varchar2"},
                    {'fieldname': "phone_no", 'src_fieldname': "13", 'type': "varchar2"},
                    {'fieldname': "callIn_out", 'src_fieldname': "14", 'type': "varchar2"},
                    {'fieldname': "location_id", 'src_fieldname': "15", 'type': "varchar2"},
                    {'fieldname': "logon_sn", 'src_fieldname': "16", 'type': "varchar2"},
                    {'fieldname': "skillInfo_sn", 'src_fieldname': "17", 'type': "varchar2"},
                    {'fieldname': "filename", 'src_fieldname': "filename", 'type': "varchar2", 'to_reload': 1, 'reload_argument': '{filename}'},
                    {'fieldname': "server", 'src_fieldname': "server_ip", 'type': "varchar2", 'to_reload': 1, 'reload_argument': '{server_ip}'},
                ]
            },
            'prm': {
                'id': '2',
                'name': 'prm',
                'server_id': 'cdr',
                'work_dir': "/share/0/bdi_sftp/fail/dbErr/Prm",
                'file_pattern': 'Prm(.{13})_[0-9]+.txt',
                'file_date_format': '%Y%m%d_%H%M',
                'file_delimiter': '|',
                'skip_lines': 0,
                'chunk_limit': 1000,
                'tablename': "aicc_cdrs_prm",
                'queue_id': "cdr.prm",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': """BEGIN
                    PK_PADM_QUEUE.SP_CDR_FILE_SUCCESS('{filename}', '{server_ip}');
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                "msg_send_granularity": True,
                'm_group': 'cdr',
                'fields': [
                    {'fieldname': "call_id", 'src_fieldname': "0", 'type': "varchar2"},
                    {'fieldname': "call_id_num", 'src_fieldname': "1", 'type': "number"},
                    {'fieldname': "caller_no", 'src_fieldname': "2", 'type': "varchar2"},
                    {'fieldname': "called_no", 'src_fieldname': "3", 'type': "varchar2"},
                    {'fieldname': "wait_begin", 'src_fieldname': "4", 'type': "date"},
                    {'fieldname': "wait_end", 'src_fieldname': "5", 'type': "date"},
                    {'fieldname': "ack_begin", 'src_fieldname': "6", 'type': "date"},
                    {'fieldname': "ack_end", 'src_fieldname': "7", 'type': "date"},
                    {'fieldname': "call_begin", 'src_fieldname': "8", 'type': "date"},
                    {'fieldname': "call_end", 'src_fieldname': "9", 'type': "date"},
                    {'fieldname': "service_no", 'src_fieldname': "10", 'type': "number"},
                    {'fieldname': "trk_no", 'src_fieldname': "11", 'type': "number"},
                    {'fieldname': "mod_no", 'src_fieldname': "12", 'type': "number"},
                    {'fieldname': "device_type", 'src_fieldname': "13", 'type': "number"},
                    {'fieldname': "device_no", 'src_fieldname': "14", 'type': "number"},
                    {'fieldname': "device_in", 'src_fieldname': "15", 'type': "varchar2"},
                    {'fieldname': "call_type", 'src_fieldname': "16", 'type': "number"},
                    {'fieldname': "wait_cause", 'src_fieldname': "17", 'type': "number"},
                    {'fieldname': "release_cause", 'src_fieldname': "18", 'type': "number"},
                    {'fieldname': "sub_cc_no", 'src_fieldname': "19", 'type': "number"},
                    {'fieldname': "vdn", 'src_fieldname': "20", 'type': "number"},
                    {'fieldname': "media_type", 'src_fieldname': "21", 'type': "number"},
                    {'fieldname': "uvid", 'src_fieldname': "22", 'type': "number"},
                    {'fieldname': "us_trunk_group", 'src_fieldname': "23", 'type': "number"},
                    {'fieldname': "org_callee_no", 'src_fieldname': "24", 'type': "varchar2"},
                    {'fieldname': "ori_cc_no", 'src_fieldname': "25", 'type': "number"},
                    {'fieldname': "ori_call_id", 'src_fieldname': "26", 'type': "varchar2"},
                    {'fieldname': "ori_service_no", 'src_fieldname': "27", 'type': "number"},
                    {'fieldname': "service_cc_id", 'src_fieldname': "28", 'type': "number"},
                    {'fieldname': "dest_service_no", 'src_fieldname': "29", 'type': "number"},
                    {'fieldname': "us_cust_level", 'src_fieldname': "30", 'type': "varchar2"},
                    {'fieldname': "us_cust_class", 'src_fieldname': "31", 'type': "varchar2"},
                    {'fieldname': "us_call_in_cause", 'src_fieldname': "32", 'type': "number"},
                    {'fieldname': "uc_enter_reason", 'src_fieldname': "33", 'type': "varchar2"},
                    {'fieldname': "uc_leave_reason", 'src_fieldname': "34", 'type': "varchar2"},
                    {'fieldname': "ul_bill_info", 'src_fieldname': "35", 'type': "number"},
                    {'fieldname': "ul_pre_service_no", 'src_fieldname': "36", 'type': "number"},
                    {'fieldname': "ul_pre_device_type", 'src_fieldname': "37", 'type': "number"},
                    {'fieldname': "ul_pre_device_no", 'src_fieldname': "38", 'type': "number"},
                    {'fieldname': "prel_device_in", 'src_fieldname': "39", 'type': "varchar2"},
                    {'fieldname': "ul_media_info_type", 'src_fieldname': "40", 'type': "number"},
                    {'fieldname': "us_skill_id_of_call", 'src_fieldname': "41", 'type': "number"},
                    {'fieldname': "us_location_id", 'src_fieldname': "42", 'type': "number"},
                    {'fieldname': "ul_bill_info1", 'src_fieldname': "43", 'type': "number"},
                    {'fieldname': "ul_bill_info2", 'src_fieldname': "44", 'type': "number"},
                    {'fieldname': "ul_bill_info3", 'src_fieldname': "45", 'type': "number"},
                    {'fieldname': "ul_bill_info4", 'src_fieldname': "46", 'type': "number"},
                    {'fieldname': "sz_obs_service_id", 'src_fieldname': "47", 'type': "varchar2"},
                    {'fieldname': "sz_obs_unique_id", 'src_fieldname': "48", 'type': "varchar2"},
                    {'fieldname': "us_current_skill_id", 'src_fieldname': "49", 'type': "number"},
                    {'fieldname': "uap_id", 'src_fieldname': "50", 'type': "number"},
                    {'fieldname': "net_ent_id", 'src_fieldname': "51", 'type': "number"},
                    {'fieldname': "uc_sub_media_type", 'src_fieldname': "52", 'type': "varchar2"},
                    {'fieldname': "init_vdn_id", 'src_fieldname': "53", 'type': "number"},
                    {'fieldname': "filename", 'src_fieldname': "filename", 'type': "varchar2", 'to_reload': 1, 'reload_argument': '{filename}'},
                    {'fieldname': "server", 'src_fieldname': "server_ip", 'type': "varchar2", 'to_reload': 1, 'reload_argument': '{server_ip}'},
                ]
            },
            'agentstat': {
                'id': '3',
                'name': 'agentstat',
                'server_id': 'cdr',
                'work_dir': "/share/0/bdi_sftp/fail/dbErr/AgentStat",
                'file_pattern': 'AgentStat(.{13})_[0-9]+.txt',
                'file_date_format': '%Y%m%d_%H%M',
                'file_delimiter': '|',
                'skip_lines': 0,
                'chunk_limit': 1000,
                'tablename': "aicc_cdrs_agentstat",
                'queue_id': "cdr.agentstat",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                "msg_send_filename": True,
                "msg_send_granularity": True,
                'm_group': 'cdr',
                'fields': [
                    {'fieldname': "ul_statistic_starttime", 'src_fieldname': "0", 'type': "date"},
                    {'fieldname': "ul_working_agt_num", 'src_fieldname': "1", 'type': "number"},
                    {'fieldname': "ul_for_agt_num", 'src_fieldname': "2", 'type': "number"},
                    {'fieldname': "ul_common_agt_num", 'src_fieldname': "3", 'type': "number"},
                    {'fieldname': "ul_idle_agt_num", 'src_fieldname': "4", 'type': "number"},
                    {'fieldname': "ul_talking_agt_num", 'src_fieldname': "5", 'type': "number"},
                    {'fieldname': "ul_waiting_agt_num", 'src_fieldname': "6", 'type': "number"},
                    {'fieldname': "ul_rest_agt_num", 'src_fieldname': "7", 'type': "number"},
                    {'fieldname': "ul_busy_agt_num", 'src_fieldname': "8", 'type': "number"},
                    {'fieldname': "ul_work_state_agt_num", 'src_fieldname': "9", 'type': "number"},
                    {'fieldname': "ul_adjust_agt_num", 'src_fieldname': "10", 'type': "number"},
                    {'fieldname': "ul_study_agt_num", 'src_fieldname': "11", 'type': "number"},
                    {'fieldname': "ul_other_state_num", 'src_fieldname': "12", 'type': "number"},
                    {'fieldname': "us_vdnid", 'src_fieldname': "13", 'type': "number"},
                    {'fieldname': "us_subccno", 'src_fieldname': "14", 'type': "number"},
                    {'fieldname': "ul_login_acd_num", 'src_fieldname': "15", 'type': "number"},
                    {'fieldname': "ul_logout_acd_num", 'src_fieldname': "16", 'type': "number"},
                    {'fieldname': "filename", 'src_fieldname': "filename", 'type': "varchar2", 'to_reload': 1, 'reload_argument': '{filename}'},
                    {'fieldname': "server", 'src_fieldname': "server_ip", 'type': "varchar2", 'to_reload': 1, 'reload_argument': '{server_ip}'},
                ]
            }
        }

        self.config_by_id = {
            "1": {
                "server_id": "cdr",
                "server_ip": "10.189.0.154",
                'm_group': 'oplist',
                'queue_id': "cdr.oplist",
            },
            "2": {
                "server_id": "cdr",
                "server_ip": "10.189.0.154",
                'm_group': 'prm',
                'queue_id': "cdr.prm",
            },
            "3": {
                "server_id": "cdr",
                "server_ip": "10.189.0.154",
                'm_group': 'agentstat',
                'queue_id': "cdr.agentstat",
            },
            "4": {
                'name': 'oplist_02',
                "server_id": "cdr_02",
                "server_ip": "10.189.0.155",
                'm_group': 'oplist',
                'queue_id': "cdr_02.oplist",
            },
            "5": {
                'name': 'prm_02',
                "server_id": "cdr_02",
                "server_ip": "10.189.0.155",
                'm_group': 'prm',
                'queue_id': "cdr_02.prm",
            },
            "6": {
                'name': 'agentstat_02',
                "server_id": "cdr_02",
                "server_ip": "10.189.0.155",
                'm_group': 'agentstat',
                'queue_id': "cdr_02.agentstat",
            },
            "7": {
                'name': 'oplist_03',
                "server_id": "cdr_03",
                "server_ip": "10.189.16.149",
                'm_group': 'oplist',
                'queue_id': "cdr_03.oplist",
            },
            "8": {
                'name': 'prm_03',
                "server_id": "cdr_03",
                "server_ip": "10.189.16.149",
                'm_group': 'prm',
                'queue_id': "cdr_03.prm",
            },
            "9": {
                'name': 'agentstat_03',
                "server_id": "cdr_03",
                "server_ip": "10.189.16.149",
                'm_group': 'agentstat',
                'queue_id': "cdr_03.agentstat",
            },
            "10": {
                'name': 'oplist_04',
                "server_id": "cdr_04",
                "server_ip": "10.189.16.150",
                'm_group': 'oplist',
                'queue_id': "cdr_04.oplist",
            },
            "11": {
                'name': 'prm_04',
                "server_id": "cdr_04",
                "server_ip": "10.189.16.150",
                'm_group': 'prm',
                'queue_id': "cdr_04.prm",
            },
            "12": {
                'name': 'agentstat_04',
                "server_id": "cdr_04",
                "server_ip": "10.189.16.150",
                'm_group': 'agentstat',
                'queue_id': "cdr_04.agentstat",
            },
        }

        config_ids = list(self.config_by_id.keys())
        for config_id in config_ids:
            group = self.config_by_id[config_id]['m_group']
            row = {**self.config_by_group[group], **self.config_by_id[config_id]}
            row['id'] = config_id
            self.config_by_id[config_id] = row
