from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryU2000ConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'alarm-log-auto',
                'type': 'stats',
                'server_id': 'default',
                'work_dir': '/opt/oss/server/var/neftpboot/ftproot/{date}',
                'file_pattern': '([0-9]{14})-alarm-log-auto-[0-9]+.csv',
                'file_date_format': '%Y%m%d%H%M%S',
                'limit_to_commit': 5000,
                'tablename': "U2000_ALARMAS_5MIN",
                'queue_id': "fija.alarm_5min",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "log_serial_number", 'src_fieldname': "0", 'type': "number", 'to_reload': None},
                    {'fieldname': "object_identity_name", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "object_identity", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "product_name", 'src_fieldname': "3", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ne_type", 'src_fieldname': "4", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ne_object_identity", 'src_fieldname': "5", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_source", 'src_fieldname': "6", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "equipment_alarmserialnumber", 'src_fieldname': "7", 'type': "number", 'to_reload': None},
                    {'fieldname': "alarmname", 'src_fieldname': "8", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "type", 'src_fieldname': "9", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "severity", 'src_fieldname': "10", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "status", 'src_fieldname': "11", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "occurrencetime", 'src_fieldname': "12", 'type': "date", 'map_with': "{'' if value == '' else dt.datetime.strptime(value.replace(' GMT-05:00','').replace(' DST',''), '%Y/%m/%d %H:%M:%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "acknowledgementtime", 'src_fieldname': "13", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clearancetime", 'src_fieldname': "14", 'type': "date", 'map_with': "{'' if value == '' else dt.datetime.strptime(value.replace(' GMT-05:00','').replace(' DST',''), '%Y/%m/%d %H:%M:%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "un_acknowledgementoperator", 'src_fieldname': "15", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clearance_operator", 'src_fieldname': "16", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "locationinformation", 'src_fieldname': "17", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "linkfdn", 'src_fieldname': "18", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "linkname", 'src_fieldname': "19", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "linktype", 'src_fieldname': "20", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_identifier", 'src_fieldname': "21", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_id", 'src_fieldname': "22", 'type': "number", 'to_reload': None},
                    {'fieldname': "object_instance_type", 'src_fieldname': "23", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "auto_clear", 'src_fieldname': "24", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarm_clear_type", 'src_fieldname': "25", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "business_affected", 'src_fieldname': "26", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "addtional_text", 'src_fieldname': "27", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "arrivedutctime", 'src_fieldname': "28", 'type': "date", 'map_with': "{'' if value == '' else dt.datetime.strptime(value.replace(' GMT-05:00','').replace(' DST',''), '%Y/%m/%d %H:%M:%S').strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "list_id", 'src_fieldname': "29", 'type': "number", 'to_reload': None},
                    {'fieldname': "related_logid", 'src_fieldname': "30", 'type': "number", 'to_reload': None},
                    {'fieldname': "agent_id", 'src_fieldname': "31", 'type': "number", 'to_reload': None},
                    {'fieldname': "root_id", 'src_fieldname': "32", 'type': "number", 'to_reload': None},
                    {'fieldname': "show_flag", 'src_fieldname': "33", 'type': "number", 'to_reload': None},
                    {'fieldname': "collectiontime", 'src_fieldname': "0", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1}
                ],
            },
            "2": {
                'id': '2',
                'name': 'CPU Occupancy Profile',
                'type': 'stats',
                'server_id': 'default',
                'work_dir': '/opt/oss/server/var/neftpboot/ftproot/{date}',
                'file_pattern': 'PM_IG80002_15_([0-9]{12})_[0-9]+.csv',
                'file_date_format': '%Y%m%d%H%M',
                'skip_lines': 2,
                'limit_to_commit': 5000,
                'tablename': "U2000_cpu_occ_profile_15min",
                'queue_id': "fija.cpu_occ_15min",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "deviceid", 'src_fieldname': "0", 'type': "number", 'to_reload': None},
                    {'fieldname': "devicename", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "resourcename", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "collectiontime", 'src_fieldname': "3", 'type': "date", 'to_reload': 1},
                    {'fieldname': "granularityperiod", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "cpu_occupancy", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                ]
            },
            "3": {
                'id': '3',
                'name': 'Memory Occupancy Profile',
                'type': 'stats',
                'server_id': 'default',
                'work_dir': '/opt/oss/server/var/neftpboot/ftproot/{date}',
                'file_pattern': 'PM_IG80100_15_([0-9]{12})_[0-9]+.csv',
                'file_date_format': '%Y%m%d%H%M',
                'skip_lines': 2,
                'limit_to_commit': 5000,
                'tablename': "U2000_mem_occ_profile_15min",
                'queue_id': "fija.mem_occ_15min",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "deviceid", 'src_fieldname': "0", 'type': "number", 'to_reload': None},
                    {'fieldname': "devicename", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "resourcename", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "collectiontime", 'src_fieldname': "3", 'type': "date", 'to_reload': 1},
                    {'fieldname': "granularityperiod", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "memory_occupancy", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                ]
            },
            "4": {
                'id': '4',
                'name': 'Slot Temperature Profile',
                'type': 'stats',
                'server_id': 'default',
                'work_dir': '/opt/oss/server/var/neftpboot/ftproot/{date}',
                'file_pattern': 'PM_IG80336_15_([0-9]{12})_[0-9]+.csv',
                'file_date_format': '%Y%m%d%H%M',
                'skip_lines': 2,
                'limit_to_commit': 5000,
                'tablename': "U2000_SLOT_TEMP_PROFILE_15MIN",
                'queue_id': "fija.slot_temp_15min",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': "group",
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"minutes": 1}',
                'steps': None,
                'event_format': 'mxm',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "deviceid", 'src_fieldname': "0", 'type': "number", 'to_reload': None},
                    {'fieldname': "devicename", 'src_fieldname': "1", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "resourcename", 'src_fieldname': "2", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "collectiontime", 'src_fieldname': "3", 'type': "date", 'to_reload': 1},
                    {'fieldname': "granularityperiod", 'src_fieldname': "4", 'type': "number", 'to_reload': None},
                    {'fieldname': "slot_temperature", 'src_fieldname': "5", 'type': "number", 'to_reload': None},
                ]
            }
        }