from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryNetecoConfigRepository(InMemoryConfigRepository):
    def __init__(self, db):
        self.db = db
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'managed_object',
                'type': 'inventory',
                # 'server_id': 'zte',
                'work_dir': 'openapi/neteco/nbi/v2/mo',
                'src_type': "paginated-api",
                # 'wk_date_format': '%Y%m%d',
                'file_pattern': 'managed_object_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "neteco_managed_object_temp",
                'queue_id': "neteco.managed_object",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    MERGE INTO neteco_managed_object A
                    USING (SELECT * FROM neteco_managed_object_temp
                    WHERE RESULT_TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS')) B
                    ON (A.DN = B.DN)
                    WHEN MATCHED THEN UPDATE SET
                        a.CREATETIME = b.CREATETIME,
                        a.TYPENAME = b.TYPENAME,
                        a.NAME = b.NAME,
                        a.TYPEID = b.TYPEID,
                        a.ISROOTDEV = b.ISROOTDEV,
                        a.EXTENDEDATTRS = b.EXTENDEDATTRS,
                        a.TYPEVERID = b.TYPEVERID,
                        a.CATEGORY = b.CATEGORY,
                        a.SUBDEVDNS = b.SUBDEVDNS,
                        a.PARENTDN = b.PARENTDN,
                        a.STATUS = b.STATUS,
                        a.fecha_actualizacion = sysdate,
                        a.estado_seg = 1
                    WHEN NOT MATCHED THEN INSERT(CREATETIME, TYPENAME, NAME, TYPEID, DN, ISROOTDEV,
                    EXTENDEDATTRS, TYPEVERID, CATEGORY, SUBDEVDNS, PARENTDN, STATUS, fecha_insercion, estado_seg)
                    VALUES(b.CREATETIME, b.TYPENAME, b.NAME, b.TYPEID, b.DN, b.ISROOTDEV,
                    b.EXTENDEDATTRS, b.TYPEVERID, b.CATEGORY, b.SUBDEVDNS, b.PARENTDN, b.STATUS, sysdate, 1);
                    commit;

                    UPDATE neteco_managed_object SET estado_seg = 0
                    WHERE DN NOT IN (SELECT DN FROM neteco_managed_object_temp
                        WHERE RESULT_TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS')
                        GROUP BY DN
                    );
                    COMMIT;

                    DELETE FROM neteco_managed_object_temp;
                    COMMIT;
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'inventory',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "createTime", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "createTime", 'src_fieldname': "createTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "typeName", 'src_fieldname': "typeName", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "name", 'src_fieldname': "name", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "isRootDev", 'src_fieldname': "isRootDev", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "extendedAttrs", 'src_fieldname': "extendedAttrs", 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                    {'fieldname': "typeVerId", 'src_fieldname': "typeVerId", 'type': "number", 'to_reload': None},
                    {'fieldname': "category", 'src_fieldname': "category", 'type': "number", 'to_reload': None},
                    {'fieldname': "subDevDns", 'src_fieldname': "subDevDns", 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "status", 'src_fieldname': "status", 'type': "number", 'to_reload': None}
                ]
            },
            "2": {
                'id': '2',
                'name': 'managed_object_type',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/motype',
                'src_type': "paginated-api",
                'file_pattern': 'managed_object_type_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "neteco_managed_object_type_temp",
                'queue_id': "neteco.managed_object_type",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """BEGIN
                    MERGE INTO neteco_managed_object_type A
                    USING (SELECT * FROM neteco_managed_object_type_temp
                    WHERE RESULT_TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS')) B
                    ON (A.typeId = B.typeId)
                    WHEN MATCHED THEN UPDATE SET
                        a.VERSIONDESC = b.VERSIONDESC,
                        a.PARENTTYPES = b.PARENTTYPES,
                        a.VENDOR = b.VENDOR,
                        a.TYPENAME = b.TYPENAME,
                        --a.TYPEID = b.TYPEID,
                        a.TYPEVERID = b.TYPEVERID,
                        a.PROTOCOLTYPE = b.PROTOCOLTYPE,
                        a.FECHA_ACTUALIZACION = sysdate,
                        a.ESTADO_SEG = 1
                    WHEN NOT MATCHED THEN INSERT(VERSIONDESC, PARENTTYPES, VENDOR, TYPENAME,
                    TYPEID, TYPEVERID, PROTOCOLTYPE, FECHA_INSERCION, ESTADO_SEG)
                    VALUES(b.VERSIONDESC, b.PARENTTYPES, b.VENDOR, b.TYPENAME,
                    b.TYPEID, b.TYPEVERID, b.PROTOCOLTYPE, sysdate, 1);
                    commit;

                    UPDATE neteco_managed_object_type SET estado_seg = 0
                    WHERE typeId NOT IN (SELECT typeId FROM neteco_managed_object_type_temp
                        WHERE RESULT_TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS')
                        GROUP BY typeId
                    );
                    COMMIT;

                    DELETE FROM neteco_managed_object_type_temp;
                    COMMIT;
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'inventory',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "versionDesc", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "versionDesc", 'src_fieldname': "versionDesc", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentTypes", 'src_fieldname': "parentTypes", 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                    {'fieldname': "vendor", 'src_fieldname': "vendor", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeName", 'src_fieldname': "typeName", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "typeVerId", 'src_fieldname': "typeVerId", 'type': "number", 'to_reload': None},
                    {'fieldname': "protocolType", 'src_fieldname': "protocolType", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "3": {
                'id': '3',
                'name': 'alarm_history',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/alarm/history',
                'src_type': "paginated-api",
                'file_pattern': 'alarm_history_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 5000,
                'tablename': "neteco_alarm_history",
                'queue_id': "neteco.alarm_history",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 3}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "clearedType", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "clearedType", 'src_fieldname': "clearedType", 'type': "number", 'to_reload': None},
                    {'fieldname': "ackTime", 'src_fieldname': "ackTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "locationInfo", 'src_fieldname': "locationInfo", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "userData", 'src_fieldname': "userData", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "isMaintenanceAlarm", 'src_fieldname': "isMaintenanceAlarm", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clearTime", 'src_fieldname': "clearTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "isInvalidAlarm", 'src_fieldname': "isInvalidAlarm", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "additionalText", 'src_fieldname': "additionalText", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "siteDn", 'src_fieldname': "siteDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "thresholdConfig", 'src_fieldname': "thresholdConfig", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ackUser", 'src_fieldname': "ackUser", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "moName", 'src_fieldname': "moName", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "path", 'src_fieldname': "path", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "insId", 'src_fieldname': "insId", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clearedClass", 'src_fieldname': "clearedClass", 'type': "number", 'to_reload': None},
                    {'fieldname': "alarmValue", 'src_fieldname': "alarmValue", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "reasonId", 'src_fieldname': "reasonId", 'type': "number", 'to_reload': None},
                    {'fieldname': "probableCause", 'src_fieldname': "probableCause", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmSn", 'src_fieldname': "alarmSn", 'type': "number", 'to_reload': None},
                    {'fieldname': "alarmId", 'src_fieldname': "alarmId", 'type': "number", 'to_reload': None},
                    {'fieldname': "additionalInfo", 'src_fieldname': "additionalInfo", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmSource", 'src_fieldname': "alarmSource", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmSeverity", 'src_fieldname': "alarmSeverity", 'type': "number", 'to_reload': None},
                    {'fieldname': "comments", 'src_fieldname': "comments", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmTime", 'src_fieldname': "alarmTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "latestLogTime", 'src_fieldname': "latestLogTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': None},
                    {'fieldname': "clearStatus", 'src_fieldname': "clearStatus", 'type': "number", 'to_reload': None},
                    {'fieldname': "commentUser", 'src_fieldname': "commentUser", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmName", 'src_fieldname': "alarmName", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "eventType", 'src_fieldname': "eventType", 'type': "number", 'to_reload': None},
                    {'fieldname': "commentTime", 'src_fieldname': "commentTime", 'type': "number", 'to_reload': None},
                    {'fieldname': "thresholdInfo", 'src_fieldname': "thresholdInfo", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "alarmSourceDn", 'src_fieldname': "alarmSourceDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "ackStatus", 'src_fieldname': "ackStatus", 'type': "number", 'to_reload': None},
                    {'fieldname': "signalId", 'src_fieldname': "signalId", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "proposedRepairActions", 'src_fieldname': "proposedRepairActions", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "clearUser", 'src_fieldname': "clearUser", 'type': "varchar2", 'to_reload': None},
                ]
            },
            "4": {
                'id': '4',
                'name': 'signal_info',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/info',
                'src_type': "paginated-api",
                'file_pattern': 'signal_info_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 5000,
                'tablename': "neteco_signal_info_temp",
                'queue_id': "neteco.signal_info",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': "file",
                'exec_after_st': """DECLARE
                    V_COUNTER number;
                    CURSOR CUR_TEMP IS
                    SELECT * FROM neteco_signal_info_temp
                    WHERE RESULT_TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS');
                BEGIN
                    FOR b IN CUR_TEMP LOOP
                        SELECT COUNT(*) INTO V_COUNTER FROM neteco_signal_info A
                        WHERE a.signalId = b.signalId AND a.typeId = b.typeId;
                        IF V_COUNTER > 0 THEN
                            UPDATE neteco_signal_info a SET
                            a.signalName = b.signalName,
                            a.signalDataType = b.signalDataType,
                            a.period = b.period,
                            a.signalAttr = b.signalAttr,
                            --a.signalId = b.signalId,
                            a.signalType = b.signalType,
                            a.precision = b.precision,
                            --a.typeId = b.typeId,
                            a.signalUnit = b.signalUnit,
                            a.typeVerId = b.typeVerId,
                            a.signalEnumInfo = b.signalEnumInfo,
                            a.FECHA_ACTUALIZACION = sysdate,
                            a.ESTADO_SEG = 1
                            WHERE a.signalId = b.signalId AND a.typeId = b.typeId;
                            COMMIT;
                        ELSE
                            INSERT INTO neteco_signal_info(signalName, signalDataType, period, signalAttr,
                            signalId, signalType, precision, typeId, signalUnit, typeVerId, signalEnumInfo,
                            FECHA_INSERCION, ESTADO_SEG)
                            VALUES(b.signalName, b.signalDataType, b.period, b.signalAttr,
                            b.signalId, b.signalType, b.precision, b.typeId, b.signalUnit, b.typeVerId, b.signalEnumInfo,
                            sysdate, 1);
                            COMMIT;
                        END IF;
                    END LOOP;

                    UPDATE neteco_signal_info SET estado_seg = 0
                    WHERE (signalId, typeId) NOT IN (SELECT signalId, typeId FROM neteco_signal_info_temp
                        WHERE RESULT_TIME = TO_DATE('{str_filedate}', 'YYYY-MM-DD HH24:MI:SS')
                        GROUP BY signalId, typeId
                    );
                    COMMIT;

                    DELETE FROM neteco_signal_info_temp;
                    COMMIT;
                END;""",
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'inventory',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalName", 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "signalName", 'src_fieldname': "signalName", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "signalDataType", 'src_fieldname': "signalDataType", 'type': "number", 'to_reload': None},
                    {'fieldname': "period", 'src_fieldname': "period", 'type': "number", 'to_reload': None},
                    {'fieldname': "signalAttr", 'src_fieldname': "signalAttr", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "signalId", 'src_fieldname': "signalId", 'type': "number", 'to_reload': None},
                    {'fieldname': "signalType", 'src_fieldname': "signalType", 'type': "number", 'to_reload': None},
                    {'fieldname': "precision", 'src_fieldname': "precision", 'type': "number", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "signalUnit", 'src_fieldname': "signalUnit", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeVerId", 'src_fieldname': "typeVerId", 'type': "number", 'to_reload': None},
                    {'fieldname': "signalEnumInfo", 'src_fieldname': "signalEnumInfo", 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                ]
            },
            "5": {
                'id': '5',
                'name': 'signal_stats_main_hour',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {
                    "typeIds": [60001],
                    #"signalIds": [30026, 30013, 30002, 30006]
                    "signalIds": [30026, 30013]
                },
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_main_hour_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 5000,
                'tablename': "neteco_signal_stats_main_hour",
                'queue_id': "neteco.signal_stats_main_hour",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "energy_consumption_hour", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30013') is None else row['30013']}", 'to_reload': None},
                    {'fieldname': "supply_duration_hour", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30026') is None else row['30026']}", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': 'signal_stats_main_uponchange',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {
                    "typeIds": [60001],
                    "signalIds": [30002, 30006]
                },
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_main_uponchange_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 5000,
                'tablename': "neteco_signal_stats_main_uponchange",
                'queue_id': "neteco.signal_stats_main_uponchange",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "ac_voltage", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30002') is None else row['30002']}", 'to_reload': None},
                    {'fieldname': "ac_current", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30006') is None else row['30006']}", 'to_reload': None},
                ]
            },
            "7": {
                'id': '7',
                'name': 'signal_stats_rectifier_1min',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60040], "signalIds": [30001, 64001]},
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_rectifier_1min_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_signal_stats_rectifier_1min",
                'queue_id': "neteco.signal_stats_rectifier_1min",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "real_time_efficiency", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30001') is None else row['30001']}", 'to_reload': None},
                    {'fieldname': "temperature", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('64001') is None else row['64001']}", 'to_reload': None},
                ]
            },
            "8": {
                'id': '8',
                'name': 'signal_stats_batterygroup_hour',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60016], "signalIds": [30021]},
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_batterygroup_hour_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_signal_stats_batterygroup_hour",
                'queue_id': "neteco.signal_stats_batterygroup_hour",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "discharged_capacity_hour", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30021') is None else row['30021']}", 'to_reload': None},
                ]
            },
            "9": {
                'id': '9',
                'name': 'signal_stats_batterygroup_uponchange',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60016], "signalIds": [30001, 30004]},
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_batterygroup_uponchange_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_signal_stats_batterygroup_uponchange",
                'queue_id': "neteco.signal_stats_batterygroup_uponchange",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "battery_state", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30001') is None else row['30001']}", 'to_reload': None},
                    {'fieldname': "temperature", 'src_fieldname': "dn", 'type': "number", 'map_with': "{'' if row.get('30004') is None else row['30004']}", 'to_reload': None},
                ]
            },
            "10": {
                'id': '10',
                'name': 'signal_stats_batterygroup_permanent',
                'type': 'inventory',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60016], "signalIds": [30019]},
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_batterygroup_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_signal_stats_batterygroup_permanent",
                'queue_id': "neteco.signal_stats_batterygroup_permanent",
                'status': 0,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_discharge_times", 'src_fieldname': "30019", 'type': 'number', 'to_reload': None},
                ]
            },
            "11": {
                'id': '11',
                'name': 'signal_stats_site_hour',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [59991], "signalIds": [30006, 30005, 30008, 30004]},
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_site_hour_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_signal_stats_site_hour",
                'queue_id': "neteco.signal_stats_site_hour",
                'status': 0,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "nr_energy_consumption_hour", 'src_fieldname': "30008", 'type': 'number', 'to_reload': None},
                    {'fieldname': "lte_energy_consumption_hour", 'src_fieldname': "30006", 'type': 'number', 'to_reload': None},
                    {'fieldname': "gsm_energy_consumption_hour", 'src_fieldname': "30004", 'type': 'number', 'to_reload': None},
                    {'fieldname': "umts_energy_consumption_hour", 'src_fieldname': "30005", 'type': 'number', 'to_reload': None},
                ]
            },
            "12": {
                'id': '12',
                'name': 'signal_stats_site_15min',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [59991], "signalIds": [30002, 30001, 30003, 30007]},
                'src_type': "signal-statistic",
                'file_pattern': 'signal_stats_site_15min_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_signal_stats_site_15min",
                'queue_id': "neteco.signal_stats_site_15min",
                'status': 0,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "umts_energy_consumption", 'src_fieldname': "30002", 'type': 'number', 'to_reload': None},
                    {'fieldname': "nr_energy_consumption", 'src_fieldname': "30007", 'type': 'number', 'to_reload': None},
                    {'fieldname': "lte_energy_consumption", 'src_fieldname': "30003", 'type': 'number', 'to_reload': None},
                    {'fieldname': "gsm_energy_consumption", 'src_fieldname': "30001", 'type': 'number', 'to_reload': None},
                ]
            },
            "13": {
                'id': '13',
                'name': 'stats_dc_output_dist_hour',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60009], "signalIds": [30013]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_dc_output_dist_hour_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_dc_output_dist_hour",
                'queue_id': "neteco.stats_dc_output_dist_hour",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "dc_load_energy_consumption", 'src_fieldname': "30013", 'type': 'number', 'to_reload': None},
                ]
            },
            "14": {
                'id': '14',
                'name': 'stats_dc_output_dist_day',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60009], "signalIds": [30014]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_dc_output_dist_day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_dc_output_dist_day",
                'queue_id': "neteco.stats_dc_output_dist_day",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "dc_load_energy_consumption", 'src_fieldname': "30014", 'type': 'number', 'to_reload': None},
                ]
            },
            "15": {
                'id': '15',
                'name': 'stats_dc_output_dist_permanent',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60009], "signalIds": [30004]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_dc_output_dist_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_dc_output_dist_permanent",
                'queue_id': "neteco.stats_dc_output_dist_permanent",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_dc_load_energy_consumption", 'src_fieldname': "30004", 'type': 'number', 'to_reload': None},
                ]
            },
            "16": {
                'id': '16',
                'name': 'stats_li_battery_group_uponchange',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60014], "signalIds": [30001, 30004]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_li_battery_group_uponchange_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_li_battery_group_uponchange",
                'queue_id': "neteco.stats_li_battery_group_uponchange",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "battery_state", 'src_fieldname': "30001", 'type': 'number', 'to_reload': None},
                    {'fieldname': "avg_temperature", 'src_fieldname': "30004", 'type': 'number', 'to_reload': None},
                ]
            },
            "17": {
                'id': '17',
                'name': 'stats_li_battery_group_day',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60014], "signalIds": [30009, 30014]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_li_battery_group_day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_li_battery_group_day",
                'queue_id': "neteco.stats_li_battery_group_day",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "discharge_duration", 'src_fieldname': "30009", 'type': 'number', 'to_reload': None},
                    {'fieldname': "longest_discharge_duration", 'src_fieldname': "30014", 'type': 'number', 'to_reload': None},
                ]
            },
            "18": {
                'id': '18',
                'name': 'stats_ac_input_dist_hour',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60013], "signalIds": [30020]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_ac_input_dist_hour_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_ac_input_dist_hour",
                'queue_id': "neteco.stats_ac_input_dist_hour",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "ac_energy_consumption", 'src_fieldname': "30020", 'type': 'number', 'to_reload': None},
                ]
            },
            "19": {
                'id': '19',
                'name': 'stats_ac_input_dist_day',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60013], "signalIds": [30019]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_ac_input_dist_day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_ac_input_dist_day",
                'queue_id': "neteco.stats_ac_input_dist_day",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 38}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "ac_energy_consumption", 'src_fieldname': "30019", 'type': 'number', 'to_reload': None},
                ]
            },
            "20": {
                'id': '20',
                'name': 'stats_ac_input_dist_permanent',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60013], "signalIds": [30012]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_ac_input_dist_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_ac_input_dist_permanent",
                'queue_id': "neteco.stats_ac_input_dist_permanent",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_ac_energy_consumption", 'src_fieldname': "30012", 'type': 'number', 'to_reload': None},
                ]
            },
            "21": {
                'id': '21',
                'name': 'stats_battery_group_day',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60016], "signalIds": [30009, 30013]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_battery_group_day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_battery_group_day",
                'queue_id': "neteco.stats_battery_group_day",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 38}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "discharge_duration", 'src_fieldname': "30009", 'type': 'number', 'to_reload': None},
                    {'fieldname': "longest_discharge_duration", 'src_fieldname': "30013", 'type': 'number', 'to_reload': None},
                ]
            },
            "22": {
                'id': '22',
                'name': 'stats_rectifier_group_permanent',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60039], "signalIds": [30005, 30010]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_rectifier_group_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_rectifier_group_permanent",
                'queue_id': "neteco.stats_rectifier_group_permanent",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_input_energy", 'src_fieldname': "30005", 'type': 'number', 'to_reload': None},
                    {'fieldname': "total_output_energy", 'src_fieldname': "30010", 'type': 'number', 'to_reload': None},
                ]
            },
            "23": {
                'id': '23',
                'name': 'stats_site_unit_permanent',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60067], "signalIds": [30005]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_site_unit_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_site_unit_permanent",
                'queue_id': "neteco.stats_site_unit_permanent",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_ac_input_energy_consumption", 'src_fieldname': "30005", 'type': 'number', 'to_reload': None},
                ]
            },
            "24": {
                'id': '24',
                'name': 'stats_dc_dist_unit_permanent',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60069], "signalIds": [30002]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_dc_dist_unit_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_dc_dist_unit_permanent",
                'queue_id': "neteco.stats_dc_dist_unit_permanent",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_dc_load_energy_consumption", 'src_fieldname': "30002", 'type': 'number', 'to_reload': None},
                ]
            },
            "25": {
                'id': '25',
                'name': 'stats_power_5min',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [69999], "signalIds": [30019]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_power_5min_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_power_5min",
                'queue_id': "neteco.stats_power_5min",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "dc_load_energy_consumption", 'src_fieldname': "30019", 'type': 'number', 'to_reload': None},
                ]
            },
            "26": {
                'id': '26',
                'name': 'stats_power_hour',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [69999], "signalIds": [30022, 30018]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_power_hour_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_power_hour",
                'queue_id': "neteco.stats_power_hour",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "ac_input_energy_consumption", 'src_fieldname': "30022", 'type': 'number', 'to_reload': None},
                    {'fieldname': "dc_load_energy_consumption", 'src_fieldname': "30018", 'type': 'number', 'to_reload': None},
                ]
            },
            "27": {
                'id': '27',
                'name': 'stats_power_day',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [69999], "signalIds": [30021, 30017]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_power_day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_power_day",
                'queue_id': "neteco.stats_power_day",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "ac_input_energy_consumption", 'src_fieldname': "30021", 'type': 'number', 'to_reload': None},
                    {'fieldname': "dc_load_energy_consumption", 'src_fieldname': "30017", 'type': 'number', 'to_reload': None},
                ]
            },
            "28": {
                'id': '28',
                'name': 'stats_power_permanent',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [69999], "signalIds": [30016, 30020]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_power_permanent_([0-9]{10}).json',
                'file_date_format': '%Y%m%d%H',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_power_permanent",
                'queue_id': "neteco.stats_power_permanent",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 1}',
                'loop_time': '{"hours": 1}',
                'steps': None,
                'event_format': 'hxh',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "total_dc_load_energy_consumption", 'src_fieldname': "30016", 'type': 'number', 'to_reload': None},
                    {'fieldname': "total_ac_input_energy_consumption", 'src_fieldname': "30020", 'type': 'number', 'to_reload': None},
                ]
            },
            "29": {
                'id': '29',
                'name': 'stats_main_day',
                'type': 'stats',
                'work_dir': 'openapi/neteco/nbi/v2/signal/statistic',
                'api_params': {"typeIds": [60001], "signalIds": [30028]},
                'src_type': "signal-statistic",
                'file_pattern': 'stats_main_day_([0-9]{8}).json',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 20000,
                'tablename': "neteco_stats_main_day",
                'queue_id': "neteco.stats_main_day",
                'status': 1,
                'reload_by': "file",
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 93}',
                'loop_time': '{"days": 1}',
                'steps': None,
                'event_format': 'dxd',
                'm_group': 'stats',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': "signalResultTime", 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value)/1000).strftime('%Y-%m-%d %H:%M:%S')}", 'to_reload': 1},
                    {'fieldname': "dn", 'src_fieldname': "dn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "parentDn", 'src_fieldname': "parentDn", 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "typeId", 'src_fieldname': "typeId", 'type': "number", 'to_reload': None},
                    {'fieldname': "fault_duration", 'src_fieldname': "30028", 'type': 'number', 'to_reload': None},
                ]
            }
        }