from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryWeplanCloudConfigRepository(InMemoryConfigRepository):
    def __init__(self):
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'active_cell_data',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'active_cell_data/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_active_cell_data",
                'queue_id': "weplan.active_cell_data",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 5, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 6, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 20, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 21, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 26, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 27, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 28, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call_status", 'src_fieldname': 29, 'type': "int", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 30, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 31, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 32, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 33, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 34, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 35, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 38, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 39, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 40, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 41, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps", 'src_fieldname': 42, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location_status", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell", 'src_fieldname': 44, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 45, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 46, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 47, 'type': "varchar2", 'to_reload': None},
                ]
            },
            "2": {
                'id': '2',
                'name': 'passive_cell_data',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'passive_cell_data/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_passive_cell_data",
                'queue_id': "weplan.passive_cell_data",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration", 'src_fieldname': 5, 'type': "int", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "loss_time", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 21, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bytes", 'src_fieldname': 26, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 27, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 28, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 29, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 30, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 31, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call_status", 'src_fieldname': 32, 'type': "int", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 33, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 34, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 35, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call_classification", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 38, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 39, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 40, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 41, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 42, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 44, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps", 'src_fieldname': 45, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location_status", 'src_fieldname': 46, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell", 'src_fieldname': 47, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 48, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 49, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None}
                ]
            },
            "3": {
                'id': '3',
                'name': 'passive_throughput',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'passive_throughput/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_passive_throughput",
                'queue_id': "weplan.passive_throughput",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 2}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration", 'src_fieldname': 5, 'type': "int", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 21, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 26, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 27, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bytes", 'src_fieldname': 28, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "throughput", 'src_fieldname': 29, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "session", 'src_fieldname': 30, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 31, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 32, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 33, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 34, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 35, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 38, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 39, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 40, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 41, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 42, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 44, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps", 'src_fieldname': 45, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location_status", 'src_fieldname': 46, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell", 'src_fieldname': 47, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 48, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 49, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None}
                ]
            },
            "4": {
                'id': '4',
                'name': 'phone_call',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'phone_call/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_phone_call",
                'queue_id': "weplan.phone_call",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 3}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration", 'src_fieldname': 5, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm_start", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr_start", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr_start", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate_start", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance_start", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi_start", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp_start", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq_start", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_start", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range_start", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp_start", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq_start", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr_start", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "cdma_ecio_start", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "evdo_snr_start", 'src_fieldname': 21, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type_start", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type_start", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type_start", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm_end", 'src_fieldname': 25, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr_end", 'src_fieldname': 26, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr_end", 'src_fieldname': 27, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate_end", 'src_fieldname': 28, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance_end", 'src_fieldname': 29, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi_end", 'src_fieldname': 30, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp_end", 'src_fieldname': 31, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq_end", 'src_fieldname': 32, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_end", 'src_fieldname': 33, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range_end", 'src_fieldname': 34, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp_end", 'src_fieldname': 35, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq_end", 'src_fieldname': 36, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr_end", 'src_fieldname': 37, 'type': "number", 'to_reload': None},
                    {'fieldname': "cdma_ecio_end", 'src_fieldname': 38, 'type': "number", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "evdo_snr_end", 'src_fieldname': 39, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type_end", 'src_fieldname': 40, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type_end", 'src_fieldname': 41, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type_end", 'src_fieldname': 42, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash_start", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash_end", 'src_fieldname': 44, 'type': "varchar2", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "secondary_start", 'src_fieldname': 45, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary_end", 'src_fieldname': 46, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 47, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 48, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 49, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call_classification", 'src_fieldname': 51, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 52, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 53, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 54, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 55, 'type': "number", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 56, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 57, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps_start", 'src_fieldname': 58, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "gps_end", 'src_fieldname': 59, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location_status", 'src_fieldname': 60, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_start", 'src_fieldname': 61, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_end", 'src_fieldname': 62, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 63, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 64, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 65, 'type': "varchar2", 'to_reload': None}
                ]
            },
            "5": {
                'id': '5',
                'name': 'ping',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'ping/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_ping",
                'queue_id': "weplan.ping",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 3}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 5, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 6, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 20, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 21, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 26, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "jitter", 'src_fieldname': 27, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "latency", 'src_fieldname': 28, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "packet", 'src_fieldname': 29, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "response", 'src_fieldname': 30, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 31, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 32, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 33, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 34, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 35, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 38, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 39, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 40, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 41, 'type': "number", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 42, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "exit_value", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 44, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 45, 'type': "date", 'map_with': "{value[:19] if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps", 'src_fieldname': 46, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "location_status", 'src_fieldname': 47, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell", 'src_fieldname': 48, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 49, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 51, 'type': "varchar2", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': 'daily_district_aggregate',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'exports/daily_district_aggregate/Peru/{date}',
                'wk_date_format': '%Y%m%d',
                'file_pattern': 'daily_district_aggregate_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_daily_district_aggregate",
                'queue_id': "weplan.daily_district_aggregate",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": False,
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "adm_level_1_code", 'src_fieldname': 1, 'type': "int", 'to_reload': None},
                    {'fieldname': "adm_level_1_name", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2_code", 'src_fieldname': 3, 'type': "int", 'to_reload': None},
                    {'fieldname': "adm_level_2_name", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3_code", 'src_fieldname': 5, 'type': "int", 'to_reload': None},
                    {'fieldname': "adm_level_3_name", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_carrier", 'src_fieldname': 7, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "avg_tg_download_3G", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_upload_3G", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_download_4G", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_upload_4G", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_download_5G_NSA", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_upload_5G_NSA", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_latency_3G", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_latency_4G", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_latency_5G_NSA", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_packet_loss_3G", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_packet_loss_4G", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_jitter_3G", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_jitter_4G", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_3G", 'src_fieldname': 21, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_4G", 'src_fieldname': 22, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_5G_NSA", 'src_fieldname': 23, 'type': "number", 'to_reload': None},
                    {'fieldname': "total_num_meas", 'src_fieldname': 24, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_download_3G_meas", 'src_fieldname': 25, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_upload_3G_meas", 'src_fieldname': 26, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_download_4G_meas", 'src_fieldname': 27, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_upload_4G_meas", 'src_fieldname': 28, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_download_5G_NSA_meas", 'src_fieldname': 29, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_upload_5G_NSA_meas", 'src_fieldname': 30, 'type': "number", 'to_reload': None},
                    {'fieldname': "lat_3G_meas", 'src_fieldname': 31, 'type': "number", 'to_reload': None},
                    {'fieldname': "lat_4G_meas", 'src_fieldname': 32, 'type': "number", 'to_reload': None},
                    {'fieldname': "lat_5G_NSA_meas", 'src_fieldname': 33, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_loss_3G_meas", 'src_fieldname': 34, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_loss_4G_meas", 'src_fieldname': 35, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_total_seconds", 'src_fieldname': 36, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_4G_seconds", 'src_fieldname': 37, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_3G_seconds", 'src_fieldname': 38, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_transmitted_3G", 'src_fieldname': 39, 'type': "number", 'to_reload': None},
                    {'fieldname': "lost_packets_3G", 'src_fieldname': 40, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_transmitted_4G", 'src_fieldname': 41, 'type': "number", 'to_reload': None},
                    {'fieldname': "lost_packets_4G", 'src_fieldname': 42, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_5G_NSA_seconds", 'src_fieldname': 43, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_total_meas", 'src_fieldname': 44, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_3G_meas", 'src_fieldname': 45, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_4G_meas", 'src_fieldname': 46, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_5G_NSA_meas", 'src_fieldname': 47, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_transmitted_5G_NSA", 'src_fieldname': 48, 'type': "number", 'to_reload': None},
                    {'fieldname': "lost_packets_5G_NSA", 'src_fieldname': 49, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_loss_5G_NSA_meas", 'src_fieldname': 50, 'type': "number", 'to_reload': None},
                ]
            }
        }