from src.shared.carga.repository import InMemoryConfigRepository

class InMemoryWeplanCloudConfigRepository(InMemoryConfigRepository):
    def __init__(self):
        self.config_by_id = {
            "1": {
                'id': '1',
                'name': 'active_cell_data',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'active_cell_data/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_active_cell_data",
                'queue_id': "weplan.active_cell_data",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 5, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 6, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 20, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 21, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 26, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 27, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 28, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_status", 'src_fieldname': 29, 'type': "int", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 30, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 31, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 32, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 33, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 34, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 35, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 38, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 39, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 40, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 41, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps_latitude", 'src_fieldname': 42, 'type': "number", "map_with": "{value['latitude'] if value.get('latitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_longitude", 'src_fieldname': 42, 'type': "number", "map_with": "{value['longitude'] if value.get('longitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_speed", 'src_fieldname': 42, 'type': "number", "map_with": "{value['speed'] if value.get('speed', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_altitude", 'src_fieldname': 42, 'type': "number", "map_with": "{value['altitude'] if value.get('altitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_elapsed_time", 'src_fieldname': 42, 'type': "number", "map_with": "{value['elapsed_time'] if value.get('elapsed_time', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_accuracy", 'src_fieldname': 42, 'type': "number", "map_with": "{value['accuracy'] if value.get('accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing", 'src_fieldname': 42, 'type': "number", "map_with": "{value['bearing'] if value.get('bearing', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing_accuracy", 'src_fieldname': 42, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_vertical_accuracy", 'src_fieldname': 42, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_model", 'src_fieldname': 43, 'type': "varchar2", "map_with": "{value['model'] if value.get('model', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_geohash", 'src_fieldname': 43, 'type': "varchar2", "map_with": "{value['geohash'] if value.get('geohash', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_non_encrypted", 'src_fieldname': 44, 'type': "varchar2", "map_with": "{value['id_non_encrypted'] if value.get('id_non_encrypted', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id", 'src_fieldname': 44, 'type': "number", "map_with": "{value['id'] if value.get('id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_long", 'src_fieldname': 44, 'type': "varchar2", "map_with": "{value['id_long'] if value.get('id_long', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_type", 'src_fieldname': 44, 'type': "number", "map_with": "{value['type'] if value.get('type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_band", 'src_fieldname': 44, 'type': "number", "map_with": "{value['band'] if value.get('band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_frequency_band", 'src_fieldname': 44, 'type': "varchar2", "map_with": "{value['frequency_band'] if value.get('frequency_band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_bandwidth", 'src_fieldname': 44, 'type': "number", "map_with": "{value['bandwidth'] if value.get('bandwidth', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_enodeb", 'src_fieldname': 44, 'type': "number", "map_with": "{value['enodeb'] if value.get('enodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_lac", 'src_fieldname': 44, 'type': "number", "map_with": "{value['lac'] if value.get('lac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_tac", 'src_fieldname': 44, 'type': "number", "map_with": "{value['tac'] if value.get('tac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mcc", 'src_fieldname': 44, 'type': "number", "map_with": "{value['mcc'] if value.get('mcc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mnc", 'src_fieldname': 44, 'type': "number", "map_with": "{value['mnc'] if value.get('mnc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_gnodeb", 'src_fieldname': 44, 'type': "number", "map_with": "{value['gnodeb'] if value.get('gnodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_pci", 'src_fieldname': 44, 'type': "number", "map_with": "{value['pci'] if value.get('pci', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_earfcn", 'src_fieldname': 44, 'type': "number", "map_with": "{value['earfcn'] if value.get('earfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_uarfcn", 'src_fieldname': 44, 'type': "number", "map_with": "{value['uarfcn'] if value.get('uarfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_arfcn", 'src_fieldname': 44, 'type': "number", "map_with": "{value['arfcn'] if value.get('arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_nr_arfcn", 'src_fieldname': 44, 'type': "number", "map_with": "{value['nr_arfcn'] if value.get('nr_arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_base_station_id", 'src_fieldname': 44, 'type': "number", "map_with": "{value['base_station_id'] if value.get('base_station_id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 45, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 46, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 47, 'type': "varchar2", 'to_reload': None},
                ]
            },
            "2": {
                'id': '2',
                'name': 'passive_cell_data',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'passive_cell_data/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_passive_cell_data",
                'queue_id': "weplan.passive_cell_data",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration", 'src_fieldname': 5, 'type': "int", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "loss_time", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 21, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 25, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "bytes_in", 'src_fieldname': 26, 'type': "int", "map_with": "{value['in'] if value.get('in', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "bytes_out", 'src_fieldname': 26, 'type': "int", "map_with": "{value['out'] if value.get('out', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "bytes_total", 'src_fieldname': 26, 'type': "int", "map_with": "{value['total'] if value.get('total', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 27, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 28, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 29, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 30, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 31, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_status", 'src_fieldname': 32, 'type': "int", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 33, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 34, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 35, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call_classification", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 38, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 39, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 40, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 41, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 42, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 43, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 44, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps_latitude", 'src_fieldname': 45, 'type': "number", "map_with": "{value['latitude'] if value.get('latitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_longitude", 'src_fieldname': 45, 'type': "number", "map_with": "{value['longitude'] if value.get('longitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_speed", 'src_fieldname': 45, 'type': "number", "map_with": "{value['speed'] if value.get('speed', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_altitude", 'src_fieldname': 45, 'type': "number", "map_with": "{value['altitude'] if value.get('altitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_elapsed_time", 'src_fieldname': 45, 'type': "number", "map_with": "{value['elapsed_time'] if value.get('elapsed_time', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_accuracy", 'src_fieldname': 45, 'type': "number", "map_with": "{value['accuracy'] if value.get('accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing", 'src_fieldname': 45, 'type': "number", "map_with": "{value['bearing'] if value.get('bearing', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing_accuracy", 'src_fieldname': 45, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_vertical_accuracy", 'src_fieldname': 45, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_model", 'src_fieldname': 46, 'type': "varchar2", "map_with": "{value['model'] if value.get('model', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_geohash", 'src_fieldname': 46, 'type': "varchar2", "map_with": "{value['geohash'] if value.get('geohash', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_non_encrypted", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['id_non_encrypted'] if value.get('id_non_encrypted', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id", 'src_fieldname': 47, 'type': "int", "map_with": "{int(float(value['id'])) if value.get('id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_long", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['id_long'] if value.get('id_long', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_type", 'src_fieldname': 47, 'type': "number", "map_with": "{value['type'] if value.get('type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_band", 'src_fieldname': 47, 'type': "number", "map_with": "{value['band'] if value.get('band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_frequency_band", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['frequency_band'] if value.get('frequency_band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_bandwidth", 'src_fieldname': 47, 'type': "number", "map_with": "{value['bandwidth'] if value.get('bandwidth', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_enodeb", 'src_fieldname': 47, 'type': "number", "map_with": "{value['enodeb'] if value.get('enodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_lac", 'src_fieldname': 47, 'type': "number", "map_with": "{value['lac'] if value.get('lac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_tac", 'src_fieldname': 47, 'type': "number", "map_with": "{value['tac'] if value.get('tac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mcc", 'src_fieldname': 47, 'type': "number", "map_with": "{value['mcc'] if value.get('mcc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mnc", 'src_fieldname': 47, 'type': "number", "map_with": "{value['mnc'] if value.get('mnc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_gnodeb", 'src_fieldname': 47, 'type': "number", "map_with": "{value['gnodeb'] if value.get('gnodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_pci", 'src_fieldname': 47, 'type': "number", "map_with": "{value['pci'] if value.get('pci', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_earfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['earfcn'] if value.get('earfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_uarfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['uarfcn'] if value.get('uarfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_arfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['arfcn'] if value.get('arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_nr_arfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['nr_arfcn'] if value.get('nr_arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_base_station_id", 'src_fieldname': 47, 'type': "number", "map_with": "{value['base_station_id'] if value.get('base_station_id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 48, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 49, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None}
                ]
            },
            "3": {
                'id': '3',
                'name': 'passive_throughput',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'passive_throughput/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_passive_throughput",
                'queue_id': "weplan.passive_throughput",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration", 'src_fieldname': 5, 'type': "int", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 21, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 26, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 27, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "bytes_in", 'src_fieldname': 28, 'type': "number", "map_with": "{value['in'] if value.get('in', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "bytes_out", 'src_fieldname': 28, 'type': "number", "map_with": "{value['out'] if value.get('out', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "bytes_total", 'src_fieldname': 28, 'type': "number", "map_with": "{value['total'] if value.get('total', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "throughput_in", 'src_fieldname': 29, 'type': "number", "map_with": "{value['in'] if value.get('in', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "throughput_out", 'src_fieldname': 29, 'type': "number", "map_with": "{value['out'] if value.get('out', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_min", 'src_fieldname': 30, 'type': "int", "map_with": "{value['min'] if value.get('min', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_avg", 'src_fieldname': 30, 'type': "number", "map_with": "{value['avg'] if value.get('avg', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_median", 'src_fieldname': 30, 'type': "number", "map_with": "{value['median'] if value.get('median', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_max", 'src_fieldname': 30, 'type': "number", "map_with": "{value['max'] if value.get('max', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_sdev", 'src_fieldname': 30, 'type': "number", "map_with": "{value['sdev'] if value.get('sdev', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_count", 'src_fieldname': 30, 'type': "int", "map_with": "{value['count'] if value.get('count', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "session_sum", 'src_fieldname': 30, 'type': "int", "map_with": "{value['sum'] if value.get('sum', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 31, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 32, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 33, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 34, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 35, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 38, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 39, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 40, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 41, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 42, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 43, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 44, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps_latitude", 'src_fieldname': 45, 'type': "number", "map_with": "{value['latitude'] if value.get('latitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_longitude", 'src_fieldname': 45, 'type': "number", "map_with": "{value['longitude'] if value.get('longitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_speed", 'src_fieldname': 45, 'type': "number", "map_with": "{value['speed'] if value.get('speed', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_altitude", 'src_fieldname': 45, 'type': "number", "map_with": "{value['altitude'] if value.get('altitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_elapsed_time", 'src_fieldname': 45, 'type': "number", "map_with": "{value['elapsed_time'] if value.get('elapsed_time', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_accuracy", 'src_fieldname': 45, 'type': "number", "map_with": "{value['accuracy'] if value.get('accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing", 'src_fieldname': 45, 'type': "number", "map_with": "{value['bearing'] if value.get('bearing', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing_accuracy", 'src_fieldname': 45, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_vertical_accuracy", 'src_fieldname': 45, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_model", 'src_fieldname': 46, 'type': "varchar2", "map_with": "{value['model'] if value.get('model', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_geohash", 'src_fieldname': 46, 'type': "varchar2", "map_with": "{value['geohash'] if value.get('geohash', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_non_encrypted", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['id_non_encrypted'] if value.get('id_non_encrypted', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id", 'src_fieldname': 47, 'type': "int", "map_with": "{int(float(value['id'])) if value.get('id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_long", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['id_long'] if value.get('id_long', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_type", 'src_fieldname': 47, 'type': "number", "map_with": "{value['type'] if value.get('type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_band", 'src_fieldname': 47, 'type': "number", "map_with": "{value['band'] if value.get('band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_frequency_band", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['frequency_band'] if value.get('frequency_band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_bandwidth", 'src_fieldname': 47, 'type': "number", "map_with": "{value['bandwidth'] if value.get('bandwidth', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_enodeb", 'src_fieldname': 47, 'type': "number", "map_with": "{value['enodeb'] if value.get('enodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_lac", 'src_fieldname': 47, 'type': "number", "map_with": "{value['lac'] if value.get('lac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_tac", 'src_fieldname': 47, 'type': "number", "map_with": "{value['tac'] if value.get('tac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mcc", 'src_fieldname': 47, 'type': "number", "map_with": "{value['mcc'] if value.get('mcc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mnc", 'src_fieldname': 47, 'type': "number", "map_with": "{value['mnc'] if value.get('mnc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_gnodeb", 'src_fieldname': 47, 'type': "number", "map_with": "{value['gnodeb'] if value.get('gnodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_pci", 'src_fieldname': 47, 'type': "number", "map_with": "{value['pci'] if value.get('pci', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_earfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['earfcn'] if value.get('earfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_uarfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['uarfcn'] if value.get('uarfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_arfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['arfcn'] if value.get('arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_nr_arfcn", 'src_fieldname': 47, 'type': "number", "map_with": "{value['nr_arfcn'] if value.get('nr_arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_base_station_id", 'src_fieldname': 47, 'type': "number", "map_with": "{value['base_station_id'] if value.get('base_station_id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 48, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 49, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None}
                ]
            },
            "4": {
                'id': '4',
                'name': 'phone_call',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'phone_call/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_phone_call",
                'queue_id': "weplan.phone_call",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 4}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "duration_time_unknown", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_unknown'] if value.get('time_unknown', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "duration_time_2g", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_2g'] if value.get('time_2g', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "duration_time_3g", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_3g'] if value.get('time_3g', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "duration_time_4g", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_4g'] if value.get('time_4g', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "duration_time_wifi", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_wifi'] if value.get('time_wifi', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "duration_time_real", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_real'] if value.get('time_real', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "duration_time_5g", 'src_fieldname': 5, 'type': "int", "map_with": "{value['time_5g'] if value.get('time_5g', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_connected", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['connected'] if value.get('connected', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_type", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['type'] if value.get('type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_state_type", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['state_type'] if value.get('state_type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_tech", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['tech'] if value.get('tech', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_tech_detail", 'src_fieldname': 6, 'type': "int", "map_with": "{value['tech_detail'] if value.get('tech_detail', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_handover_count", 'src_fieldname': 6, 'type': "int", "map_with": "{value['handover_count'] if value.get('handover_count', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_csfb", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['csfb'] if value.get('csfb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_semi_pure_4g", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['semi_pure_4g'] if value.get('semi_pure_4g', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_pure_4g", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['pure_4g'] if value.get('pure_4g', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_srvcc", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['srvcc'] if value.get('srvcc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_pure_wifi", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['pure_wifi'] if value.get('pure_wifi', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_lte_wifi", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['lte_wifi'] if value.get('lte_wifi', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "call_wifi_lte", 'src_fieldname': 6, 'type': "varchar2", "map_with": "{value['wifi_lte'] if value.get('wifi_lte', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "dbm_start", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr_start", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr_start", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate_start", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance_start", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi_start", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp_start", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq_start", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_start", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range_start", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp_start", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq_start", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr_start", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "cdma_ecio_start", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "evdo_snr_start", 'src_fieldname': 21, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type_start", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type_start", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type_start", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm_end", 'src_fieldname': 25, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr_end", 'src_fieldname': 26, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr_end", 'src_fieldname': 27, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate_end", 'src_fieldname': 28, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance_end", 'src_fieldname': 29, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi_end", 'src_fieldname': 30, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp_end", 'src_fieldname': 31, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq_end", 'src_fieldname': 32, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_end", 'src_fieldname': 33, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range_end", 'src_fieldname': 34, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp_end", 'src_fieldname': 35, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq_end", 'src_fieldname': 36, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr_end", 'src_fieldname': 37, 'type': "number", 'to_reload': None},
                    {'fieldname': "cdma_ecio_end", 'src_fieldname': 38, 'type': "number", 'to_reload': None},
                    {'fieldname': "evdo_snr_end", 'src_fieldname': 39, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type_end", 'src_fieldname': 40, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type_end", 'src_fieldname': 41, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type_end", 'src_fieldname': 42, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash_start", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash_end", 'src_fieldname': 44, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary_start", 'src_fieldname': 45, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "secondary_end", 'src_fieldname': 46, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 48, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 49, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "call_classification", 'src_fieldname': 51, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 52, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 53, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 54, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 55, 'type': "number", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 56, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 57, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps_start_latitude", 'src_fieldname': 58, 'type': "number", "map_with": "{value['latitude'] if value.get('latitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_longitude", 'src_fieldname': 58, 'type': "number", "map_with": "{value['longitude'] if value.get('longitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_speed", 'src_fieldname': 58, 'type': "number", "map_with": "{value['speed'] if value.get('speed', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_altitude", 'src_fieldname': 58, 'type': "number", "map_with": "{value['altitude'] if value.get('altitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_elapsed_time", 'src_fieldname': 58, 'type': "number", "map_with": "{value['elapsed_time'] if value.get('elapsed_time', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_accuracy", 'src_fieldname': 58, 'type': "number", "map_with": "{value['accuracy'] if value.get('accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_bearing", 'src_fieldname': 58, 'type': "number", "map_with": "{value['bearing'] if value.get('bearing', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_bearing_accuracy", 'src_fieldname': 58, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_start_vertical_accuracy", 'src_fieldname': 58, 'type': "number", "map_with": "{value['vertical_accuracy'] if value.get('vertical_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_latitude", 'src_fieldname': 59, 'type': "number", "map_with": "{value['latitude'] if value.get('latitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_longitude", 'src_fieldname': 59, 'type': "number", "map_with": "{value['longitude'] if value.get('longitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_speed", 'src_fieldname': 59, 'type': "number", "map_with": "{value['speed'] if value.get('speed', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_altitude", 'src_fieldname': 59, 'type': "number", "map_with": "{value['altitude'] if value.get('altitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_elapsed_time", 'src_fieldname': 59, 'type': "number", "map_with": "{value['elapsed_time'] if value.get('elapsed_time', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_accuracy", 'src_fieldname': 59, 'type': "number", "map_with": "{value['accuracy'] if value.get('accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_bearing", 'src_fieldname': 59, 'type': "number", "map_with": "{value['bearing'] if value.get('bearing', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_bearing_accuracy", 'src_fieldname': 59, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_end_vertical_accuracy", 'src_fieldname': 59, 'type': "number", "map_with": "{value['vertical_accuracy'] if value.get('vertical_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_model", 'src_fieldname': 60, 'type': "varchar2", "map_with": "{value['model'] if value.get('model', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_geohash", 'src_fieldname': 60, 'type': "varchar2", "map_with": "{value['geohash'] if value.get('geohash', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_id_non_encrypted", 'src_fieldname': 61, 'type': "varchar2", "map_with": "{value['id_non_encrypted'] if value.get('id_non_encrypted', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_id", 'src_fieldname': 61, 'type': "int", "map_with": "{value['id'] if value.get('id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_id_long", 'src_fieldname': 61, 'type': "varchar2", "map_with": "{value['id_long'] if value.get('id_long', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_type", 'src_fieldname': 61, 'type': "number", "map_with": "{value['type'] if value.get('type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_band", 'src_fieldname': 61, 'type': "number", "map_with": "{value['band'] if value.get('band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_frequency_band", 'src_fieldname': 61, 'type': "varchar2", "map_with": "{value['frequency_band'] if value.get('frequency_band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_bandwidth", 'src_fieldname': 61, 'type': "number", "map_with": "{value['bandwidth'] if value.get('bandwidth', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_enodeb", 'src_fieldname': 61, 'type': "number", "map_with": "{value['enodeb'] if value.get('enodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_lac", 'src_fieldname': 61, 'type': "number", "map_with": "{value['lac'] if value.get('lac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_tac", 'src_fieldname': 61, 'type': "number", "map_with": "{value['tac'] if value.get('tac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_mcc", 'src_fieldname': 61, 'type': "number", "map_with": "{value['mcc'] if value.get('mcc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_mnc", 'src_fieldname': 61, 'type': "number", "map_with": "{value['mnc'] if value.get('mnc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_gnodeb", 'src_fieldname': 61, 'type': "number", "map_with": "{value['gnodeb'] if value.get('gnodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_pci", 'src_fieldname': 61, 'type': "number", "map_with": "{value['pci'] if value.get('pci', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_earfcn", 'src_fieldname': 61, 'type': "number", "map_with": "{value['earfcn'] if value.get('earfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_uarfcn", 'src_fieldname': 61, 'type': "number", "map_with": "{value['uarfcn'] if value.get('uarfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_arfcn", 'src_fieldname': 61, 'type': "number", "map_with": "{value['arfcn'] if value.get('arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_nr_arfcn", 'src_fieldname': 61, 'type': "number", "map_with": "{value['nr_arfcn'] if value.get('nr_arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_start_base_station_id", 'src_fieldname': 61, 'type': "number", "map_with": "{value['base_station_id'] if value.get('base_station_id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_end", 'src_fieldname': 62, 'type': "varchar2", "map_with": "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 63, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 64, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 65, 'type': "varchar2", 'to_reload': None}
                ]
            },
            "5": {
                'id': '5',
                'name': 'ping',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'ping/sdk_client=Weplan/{date}',
                'wk_date_format': 'year=%Y/month=%m/day=%d',
                'file_pattern': '([0-9]{8})_part-.+.snappy.parquet',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_ping",
                'queue_id': "weplan.ping",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 3}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": True,
                'm_group': '1',
                'fields': [
                    {'fieldname': "result_time", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "filename", 'src_fieldname': 0, 'type': "varchar2", 'map_with': "{env['filename']}", 'to_reload': 1, "reload_argument": "{filename}"},
                    {'fieldname': "date_to_proccess", 'src_fieldname': 0, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timestamp", 'src_fieldname': 1, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "timezone", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "operator_name", 'src_fieldname': 3, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "client_radio_tech_type", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "geohash", 'src_fieldname': 5, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "dbm", 'src_fieldname': 6, 'type': "number", 'to_reload': None},
                    {'fieldname': "rssnr", 'src_fieldname': 7, 'type': "number", 'to_reload': None},
                    {'fieldname': "snr", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "bit_error_rate", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "timing_advance", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "cqi", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrp", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "rsrq", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "signal_strength_range", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrp", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_rsrq", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "ss_sinr", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "asu_level", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "network_type", 'src_fieldname': 20, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cell_network_type", 'src_fieldname': 21, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_technology", 'src_fieldname': 22, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "connection_type", 'src_fieldname': 23, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "cdma_ecio", 'src_fieldname': 24, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "evdo_snr", 'src_fieldname': 25, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "secondary", 'src_fieldname': 26, 'type': "varchar2", 'map_with': "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "jitter_min", 'src_fieldname': 27, 'type': "number", 'map_with': "{value.get('min') if value.get('min', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "jitter_avg", 'src_fieldname': 27, 'type': "number", 'map_with': "{value.get('avg') if value.get('avg', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "jitter_max", 'src_fieldname': 27, 'type': "number", 'map_with': "{value.get('max') if value.get('max', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "latency_min", 'src_fieldname': 28, 'type': "number", 'map_with': "{value.get('min') if value.get('min', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "latency_avg", 'src_fieldname': 28, 'type': "number", 'map_with': "{value.get('avg') if value.get('avg', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "latency_max", 'src_fieldname': 28, 'type': "number", 'map_with': "{value.get('max') if value.get('max', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "packet_transmitted", 'src_fieldname': 29, 'type': "number", 'map_with': "{value.get('transmitted') if value.get('transmitted', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "packet_received", 'src_fieldname': 29, 'type': "number", 'map_with': "{value.get('received') if value.get('received', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "packet_loss", 'src_fieldname': 29, 'type': "number", 'map_with': "{value.get('loss') if value.get('loss', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "response", 'src_fieldname': 30, 'type': "varchar2", 'map_with': "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "wifi", 'src_fieldname': 31, 'type': "varchar2", 'map_with': "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sim", 'src_fieldname': 32, 'type': "varchar2", 'map_with': "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "device", 'src_fieldname': 33, 'type': "varchar2", 'map_with': "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "sdk_version", 'src_fieldname': 34, 'type': "int", 'to_reload': None},
                    {'fieldname': "uuid", 'src_fieldname': 35, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "data_roaming", 'src_fieldname': 36, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "preferred_network", 'src_fieldname': 37, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "record_timestamp", 'src_fieldname': 38, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "power_saver_mode", 'src_fieldname': 39, 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                    {'fieldname': "carrier_aggregation", 'src_fieldname': 40, 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                    {'fieldname': "rssi", 'src_fieldname': 41, 'type': "number", 'to_reload': None},
                    {'fieldname': "is_data_subscription", 'src_fieldname': 42, 'type': "varchar2", 'map_with': "{json.dumps(value)}", 'to_reload': None},
                    {'fieldname': "exit_value", 'src_fieldname': 43, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "bandwidth_list", 'src_fieldname': 44, 'type': "varchar2", 'map_with': "{json.dumps(value) if value is not None else ''}", 'to_reload': None},
                    {'fieldname': "timestamp_local", 'src_fieldname': 45, 'type': "date", 'map_with': "{dt.datetime.fromtimestamp(int(value/1000)) if value is not None else None}", 'to_reload': None},
                    {'fieldname': "gps_latitude", 'src_fieldname': 46, 'type': "number", "map_with": "{value['latitude'] if value.get('latitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_longitude", 'src_fieldname': 46, 'type': "number", "map_with": "{value['longitude'] if value.get('longitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_speed", 'src_fieldname': 46, 'type': "number", "map_with": "{value['speed'] if value.get('speed', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_altitude", 'src_fieldname': 46, 'type': "number", "map_with": "{value['altitude'] if value.get('altitude', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_elapsed_time", 'src_fieldname': 46, 'type': "number", "map_with": "{value['elapsed_time'] if value.get('elapsed_time', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_accuracy", 'src_fieldname': 46, 'type': "number", "map_with": "{value['accuracy'] if value.get('accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing", 'src_fieldname': 46, 'type': "number", "map_with": "{value['bearing'] if value.get('bearing', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_bearing_accuracy", 'src_fieldname': 46, 'type': "number", "map_with": "{value['bearing_accuracy'] if value.get('bearing_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "gps_vertical_accuracy", 'src_fieldname': 46, 'type': "number", "map_with": "{value['vertical_accuracy'] if value.get('vertical_accuracy', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_model", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['model'] if value.get('model', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "location_status_geohash", 'src_fieldname': 47, 'type': "varchar2", "map_with": "{value['geohash'] if value.get('geohash', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_non_encrypted", 'src_fieldname': 48, 'type': "varchar2", "map_with": "{value['id_non_encrypted'] if value.get('id_non_encrypted', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id", 'src_fieldname': 48, 'type': "int", "map_with": "{value['id'] if value.get('id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_id_long", 'src_fieldname': 48, 'type': "varchar2", "map_with": "{value['id_long'] if value.get('id_long', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_type", 'src_fieldname': 48, 'type': "number", "map_with": "{value['type'] if value.get('type', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_band", 'src_fieldname': 48, 'type': "number", "map_with": "{value['band'] if value.get('band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_frequency_band", 'src_fieldname': 48, 'type': "varchar2", "map_with": "{value['frequency_band'] if value.get('frequency_band', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_bandwidth", 'src_fieldname': 48, 'type': "number", "map_with": "{value['bandwidth'] if value.get('bandwidth', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_enodeb", 'src_fieldname': 48, 'type': "number", "map_with": "{value['enodeb'] if value.get('enodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_lac", 'src_fieldname': 48, 'type': "number", "map_with": "{value['lac'] if value.get('lac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_tac", 'src_fieldname': 48, 'type': "number", "map_with": "{value['tac'] if value.get('tac', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mcc", 'src_fieldname': 48, 'type': "number", "map_with": "{value['mcc'] if value.get('mcc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_mnc", 'src_fieldname': 48, 'type': "number", "map_with": "{value['mnc'] if value.get('mnc', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_gnodeb", 'src_fieldname': 48, 'type': "number", "map_with": "{value['gnodeb'] if value.get('gnodeb', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_pci", 'src_fieldname': 48, 'type': "number", "map_with": "{value['pci'] if value.get('pci', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_earfcn", 'src_fieldname': 48, 'type': "number", "map_with": "{value['earfcn'] if value.get('earfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_uarfcn", 'src_fieldname': 48, 'type': "number", "map_with": "{value['uarfcn'] if value.get('uarfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_arfcn", 'src_fieldname': 48, 'type': "number", "map_with": "{value['arfcn'] if value.get('arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_nr_arfcn", 'src_fieldname': 48, 'type': "number", "map_with": "{value['nr_arfcn'] if value.get('nr_arfcn', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "cell_base_station_id", 'src_fieldname': 48, 'type': "number", "map_with": "{value['base_station_id'] if value.get('base_station_id', None) is not None else ''}", 'to_reload': None},
                    {'fieldname': "adm_level_1", 'src_fieldname': 49, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2", 'src_fieldname': 50, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3", 'src_fieldname': 51, 'type': "varchar2", 'to_reload': None},
                ]
            },
            "6": {
                'id': '6',
                'name': 'daily_district_aggregate',
                'type': 'stats',
                'server_id': None,
                "src_bucket": "claro-pe-pro-storage",
                'work_dir': 'exports/daily_district_aggregate/Peru/{date}',
                'wk_date_format': '%Y%m%d',
                'file_pattern': 'daily_district_aggregate_([0-9]{8}).csv',
                'file_date_format': '%Y%m%d',
                'limit_to_commit': 10000,
                'tablename': "weplan.weplan_daily_district_aggregate",
                'queue_id': "weplan.daily_district_aggregate",
                'status': 1,
                'reload_by': "file",
                'reload_validation': True,
                'exec_after_by': None,
                'exec_after_st': None,
                'files_permission': None,
                'search_time_ago': '{"days": 7}',
                'loop_time': '{"days": 1}',
                'steps': "parquet",
                'event_format': 'dxd',
                "msg_send_filename": False,
                'm_group': '1',
                'fields': [
                    {'fieldname': "fecha", 'src_fieldname': 0, 'type': "date", 'map_with': "{env['str_filedate']}", 'to_reload': 1},
                    {'fieldname': "adm_level_1_code", 'src_fieldname': 1, 'type': "int", 'to_reload': None},
                    {'fieldname': "adm_level_1_name", 'src_fieldname': 2, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_2_code", 'src_fieldname': 3, 'type': "int", 'to_reload': None},
                    {'fieldname': "adm_level_2_name", 'src_fieldname': 4, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "adm_level_3_code", 'src_fieldname': 5, 'type': "int", 'to_reload': None},
                    {'fieldname': "adm_level_3_name", 'src_fieldname': 6, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "network_carrier", 'src_fieldname': 7, 'type': "varchar2", 'to_reload': None},
                    {'fieldname': "avg_tg_download_3G", 'src_fieldname': 8, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_upload_3G", 'src_fieldname': 9, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_download_4G", 'src_fieldname': 10, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_upload_4G", 'src_fieldname': 11, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_download_5G_NSA", 'src_fieldname': 12, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_tg_upload_5G_NSA", 'src_fieldname': 13, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_latency_3G", 'src_fieldname': 14, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_latency_4G", 'src_fieldname': 15, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_latency_5G_NSA", 'src_fieldname': 16, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_packet_loss_3G", 'src_fieldname': 17, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_packet_loss_4G", 'src_fieldname': 18, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_jitter_3G", 'src_fieldname': 19, 'type': "number", 'to_reload': None},
                    {'fieldname': "avg_jitter_4G", 'src_fieldname': 20, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_3G", 'src_fieldname': 21, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_4G", 'src_fieldname': 22, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_5G_NSA", 'src_fieldname': 23, 'type': "number", 'to_reload': None},
                    {'fieldname': "total_num_meas", 'src_fieldname': 24, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_download_3G_meas", 'src_fieldname': 25, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_upload_3G_meas", 'src_fieldname': 26, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_download_4G_meas", 'src_fieldname': 27, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_upload_4G_meas", 'src_fieldname': 28, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_download_5G_NSA_meas", 'src_fieldname': 29, 'type': "number", 'to_reload': None},
                    {'fieldname': "tg_upload_5G_NSA_meas", 'src_fieldname': 30, 'type': "number", 'to_reload': None},
                    {'fieldname': "lat_3G_meas", 'src_fieldname': 31, 'type': "number", 'to_reload': None},
                    {'fieldname': "lat_4G_meas", 'src_fieldname': 32, 'type': "number", 'to_reload': None},
                    {'fieldname': "lat_5G_NSA_meas", 'src_fieldname': 33, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_loss_3G_meas", 'src_fieldname': 34, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_loss_4G_meas", 'src_fieldname': 35, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_total_seconds", 'src_fieldname': 36, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_4G_seconds", 'src_fieldname': 37, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_3G_seconds", 'src_fieldname': 38, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_transmitted_3G", 'src_fieldname': 39, 'type': "number", 'to_reload': None},
                    {'fieldname': "lost_packets_3G", 'src_fieldname': 40, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_transmitted_4G", 'src_fieldname': 41, 'type': "number", 'to_reload': None},
                    {'fieldname': "lost_packets_4G", 'src_fieldname': 42, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_5G_NSA_seconds", 'src_fieldname': 43, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_total_meas", 'src_fieldname': 44, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_3G_meas", 'src_fieldname': 45, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_4G_meas", 'src_fieldname': 46, 'type': "number", 'to_reload': None},
                    {'fieldname': "time_pct_5G_NSA_meas", 'src_fieldname': 47, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_transmitted_5G_NSA", 'src_fieldname': 48, 'type': "number", 'to_reload': None},
                    {'fieldname': "lost_packets_5G_NSA", 'src_fieldname': 49, 'type': "number", 'to_reload': None},
                    {'fieldname': "packet_loss_5G_NSA_meas", 'src_fieldname': 50, 'type': "number", 'to_reload': None},
                ]
            }
        }