CREATE DATABASE IF NOT EXISTS spam ENGINE = Atomic;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL1
(
    VALOR String,
    FECHA_INSERCION DateTime64(6, 'America/Lima'),
    FECHA_MODIFICACION DateTime64(6, 'America/Lima')
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL1__INCOMING
(
    VALOR String
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL1__NEXT
AS spam.UCEPRTC_LVL1;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL2
(
    VALOR String,
    FECHA_INSERCION DateTime64(6, 'America/Lima'),
    FECHA_MODIFICACION DateTime64(6, 'America/Lima')
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL2__INCOMING
(
    VALOR String
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL2__NEXT
AS spam.UCEPRTC_LVL2;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL3
(
    VALOR String,
    FECHA_INSERCION DateTime64(6, 'America/Lima'),
    FECHA_MODIFICACION DateTime64(6, 'America/Lima')
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL3__INCOMING
(
    VALOR String
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LVL3__NEXT
AS spam.UCEPRTC_LVL3;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LST_BCK
(
    VALOR String,
    FECHA_INSERCION DateTime64(6, 'America/Lima'),
    FECHA_MODIFICACION DateTime64(6, 'America/Lima')
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LST_BCK__INCOMING
(
    VALOR String
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_LST_BCK__NEXT
AS spam.UCEPRTC_LST_BCK;

-- Se conserva el nombre UCEPRCT_LST_WHT solicitado originalmente.
CREATE TABLE IF NOT EXISTS spam.UCEPRCT_LST_WHT
(
    VALOR String,
    FECHA_INSERCION DateTime64(6, 'America/Lima'),
    FECHA_MODIFICACION DateTime64(6, 'America/Lima')
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRCT_LST_WHT__INCOMING
(
    VALOR String
)
ENGINE = MergeTree
ORDER BY VALOR;

CREATE TABLE IF NOT EXISTS spam.UCEPRCT_LST_WHT__NEXT
AS spam.UCEPRCT_LST_WHT;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_ASN
(
    POSICION UInt32,
    TENDENCIA LowCardinality(String),
    SPAM_SCORE Float64,
    IMPACTOS UInt64,
    PROVEEDOR String,
    ASN String,
    FECHA_INSERCION DateTime64(6, 'America/Lima'),
    FECHA_MODIFICACION DateTime64(6, 'America/Lima')
)
ENGINE = MergeTree
ORDER BY ASN;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_ASN__INCOMING
(
    POSICION UInt32,
    TENDENCIA LowCardinality(String),
    SPAM_SCORE Float64,
    IMPACTOS UInt64,
    PROVEEDOR String,
    ASN String
)
ENGINE = MergeTree
ORDER BY ASN;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_ASN__NEXT
AS spam.UCEPRTC_ASN;

CREATE TABLE IF NOT EXISTS spam.UCEPRTC_AUDITORIA
(
    ID_EJECUCION UUID,
    FUENTE LowCardinality(String),
    TABLA_DESTINO String,
    FECHA_INICIO DateTime64(6, 'America/Lima'),
    FECHA_FIN DateTime64(6, 'America/Lima'),
    ESTADO LowCardinality(String),
    REGISTROS_FUENTE UInt64,
    INSERTADOS UInt64,
    ACTUALIZADOS UInt64,
    ELIMINADOS UInt64,
    SIN_CAMBIOS UInt64,
    DETALLE_ERROR String
)
ENGINE = MergeTree
ORDER BY (FECHA_INICIO, ID_EJECUCION);
