-- Ejecutar una sola vez en el esquema usado por las pruebas manuales.
-- Es independiente del log de producción; no modifica datos existentes.
CREATE TABLE AIVO_WHATSAPP_TEST_LOG
(
    ID_ENVIO                  VARCHAR2(36 CHAR) NOT NULL,
    ID_PRUEBA                 VARCHAR2(64 CHAR) NOT NULL,
    DESTINO_CLAVE             VARCHAR2(20 CHAR) NOT NULL,
    MODO                      VARCHAR2(12 CHAR) DEFAULT 'PRUEBA' NOT NULL,
    PLANTILLA                 VARCHAR2(40 CHAR) NOT NULL,
    INCIDENCIA                VARCHAR2(128 CHAR) NOT NULL,
    FECHA_INICIO_AVERIA        TIMESTAMP(6) NOT NULL,
    FECHA_ESTIMADA_SOLUCION    TIMESTAMP(6),
    FECHA_SOLUCION             TIMESTAMP(6),
    NRO_DOCUMENTO             VARCHAR2(64 CHAR),
    NOMBRE_CLIENTE            VARCHAR2(256 CHAR) NOT NULL,
    NUMERO_CLIENTE            VARCHAR2(20 CHAR) NOT NULL,
    NUMERO_DESTINO            VARCHAR2(20 CHAR) NOT NULL,
    ESTADO                    VARCHAR2(20 CHAR) NOT NULL,
    INTENTOS                  NUMBER(1) DEFAULT 0 NOT NULL,
    HTTP_STATUS               NUMBER(3),
    SOLICITUD_JSON            CLOB NOT NULL,
    RESPUESTA_JSON            CLOB,
    ERROR_DETALLE             VARCHAR2(2000 CHAR),
    FECHA_REGISTRO            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AIVO_WA_TLOG PRIMARY KEY (ID_ENVIO),
    CONSTRAINT UQ_AIVO_WA_TEST UNIQUE (ID_PRUEBA, PLANTILLA, DESTINO_CLAVE),
    CONSTRAINT CK_AIVO_WA_TMODE CHECK (MODO = 'PRUEBA'),
    CONSTRAINT CK_AIVO_WA_TCOUNT CHECK (INTENTOS IN (0, 1)),
    CONSTRAINT CK_AIVO_WA_TSTATE CHECK
        (ESTADO IN ('RESERVADO', 'ENVIANDO', 'ACEPTADO', 'ERROR_AUTH', 'ERROR_HTTP', 'INCIERTO')),
    CONSTRAINT CK_AIVO_WA_TTPL CHECK
        (PLANTILLA IN ('averia_diagnosticada', 'averia_solucionada'))
);

COMMENT ON TABLE AIVO_WHATSAPP_TEST_LOG IS
    'Pruebas manuales: máximo un intento por ronda, plantilla y destino normalizado.';
