CREATE TABLE ROUTERS_ELOG
(
    ROUTERS_UNICOS  NUMBER(10, 0)                    NOT NULL,
    FECHA_MEDICION  TIMESTAMP(6)                     NOT NULL,
    FECHA_CARGA     TIMESTAMP(6) WITH TIME ZONE
                    DEFAULT SYSTIMESTAMP              NOT NULL,
    CONSTRAINT PK_ROUTERS_ELOG PRIMARY KEY (FECHA_MEDICION),
    CONSTRAINT CK_ROUT_ELOG_COUNT CHECK (ROUTERS_UNICOS >= 0)
);

CREATE INDEX IX_ROUTERS_ELOG_CARGA
    ON ROUTERS_ELOG (FECHA_CARGA);
