-- Ejecutar UNA SOLA VEZ en el esquema de AIVO_WHATSAPP_LOG.
-- Detener las ejecuciones de prueba y mantener el DAG pausado hasta finalizar.
-- No se eliminan registros: los intentos existentes pertenecen a PRUEBA.
ALTER TABLE AIVO_WHATSAPP_LOG ADD (
    MODO VARCHAR2(12 CHAR) DEFAULT 'PRUEBA' NOT NULL
);

ALTER TABLE AIVO_WHATSAPP_LOG DROP CONSTRAINT UQ_AIVO_WA_EVENTO;
ALTER TABLE AIVO_WHATSAPP_LOG ADD CONSTRAINT UQ_AIVO_WA_EVENTO
    UNIQUE (MODO, NUMERO_CLIENTE, FECHA_INICIO_AVERIA, PLANTILLA);

ALTER TABLE AIVO_WHATSAPP_LOG DROP CONSTRAINT UQ_AIVO_WA_PRUEBA;
ALTER TABLE AIVO_WHATSAPP_LOG DROP CONSTRAINT CK_AIVO_WA_DESTINO;
ALTER TABLE AIVO_WHATSAPP_LOG ADD CONSTRAINT CK_AIVO_WA_MODO
    CHECK (MODO IN ('PRUEBA', 'PRODUCCION'));
ALTER TABLE AIVO_WHATSAPP_LOG MODIFY (MODO DEFAULT 'PRODUCCION');

COMMENT ON TABLE AIVO_WHATSAPP_LOG IS
    'Reservas y respuestas Aivo. Clave por modo, cliente, inicio y plantilla.';
COMMENT ON COLUMN AIVO_WHATSAPP_LOG.NUMERO_DESTINO IS
    'Celular real enviado en el POST; datos del origen Oracle en PRODUCCION.';
COMMENT ON COLUMN AIVO_WHATSAPP_LOG.MODO IS
    'PRUEBA conserva intentos al destino de prueba; PRODUCCION envía al origen.';

-- AIVO_WA_TEST_GUARD se conserva como historial y deja de usarse.
COMMIT;
